// Generated by CoffeeScript 2.7.0
(function() {
  var CoffeeScript, _, bold, build, buildAndTest, buildAnnotatedSource, buildDocTests, buildDocs, buildExceptParser, buildParser, exec, execSync, fs, green, header, helpers, log, majorVersion, os, path, red, reset, run, runTests, spawn, spawnNodeProcess, testBuiltCode, transpile, watchAndBuildAndTest, yellow,
    indexOf = [].indexOf;

  fs = require('fs');

  os = require('os');

  path = require('path');

  _ = require('underscore');

  ({spawn, exec, execSync} = require('child_process'));

  CoffeeScript = require('./lib/coffeescript');

  helpers = require('./lib/coffeescript/helpers');

  // ANSI Terminal Colors.
  bold = red = green = yellow = reset = '';

  if (!process.env.NODE_DISABLE_COLORS) {
    bold = '\x1B[0;1m';
    red = '\x1B[0;31m';
    green = '\x1B[0;32m';
    yellow = '\x1B[0;33m';
    reset = '\x1B[0m';
  }

  // Built file header.
  header = `/**
 * CoffeeScript Compiler v${CoffeeScript.VERSION}
 * https://coffeescript.org
 *
 * Copyright 2011-${new Date().getFullYear()}, Jeremy Ashkenas
 * Released under the MIT License
 */`;

  // Used in folder names like `docs/v1`.
  majorVersion = parseInt(CoffeeScript.VERSION.split('.')[0], 10);

  // Log a message with a color.
  log = function(message, color, explanation) {
    return console.log(color + message + reset + ' ' + (explanation || ''));
  };

  spawnNodeProcess = function(args, output = 'stderr', callback) {
    var proc, relayOutput;
    relayOutput = function(buffer) {
      return console.log(buffer.toString());
    };
    proc = spawn('node', args);
    if (output === 'both' || output === 'stdout') {
      proc.stdout.on('data', relayOutput);
    }
    if (output === 'both' || output === 'stderr') {
      proc.stderr.on('data', relayOutput);
    }
    return proc.on('exit', function(status) {
      if (typeof callback === 'function') {
        return callback(status);
      }
    });
  };

  // Run a CoffeeScript through our node/coffee interpreter.
  run = function(args, callback) {
    return spawnNodeProcess(['bin/coffee'].concat(args), 'stderr', function(status) {
      if (status !== 0) {
        process.exit(1);
      }
      if (typeof callback === 'function') {
        return callback();
      }
    });
  };

  // Build the CoffeeScript language from source.
  buildParser = function() {
    var Generator, grammar, language, parser, syntax;
    helpers.extend(global, require('util'));
    switch (1) {
      case 1:
        grammar = require('./lib/coffeescript/grammar');
        language = {
          bnf: grammar.bnf,
          operators: grammar.operators
        };
        break;
      case 2:
        syntax = require('./lib/coffeescript/syntax');
        language = {
          grammar: syntax.grammar,
          operators: syntax.operators
        };
    }
    ({Generator} = require('./solar.coffee'));
    parser = Generator(language).generate({
      compress: !true
    });
    return fs.writeFileSync('lib/coffeescript/parser.js', parser);
  };

  buildExceptParser = function(callback) {
    var file, files;
    files = fs.readdirSync('src');
    files = (function() {
      var i, len, results;
      results = [];
      for (i = 0, len = files.length; i < len; i++) {
        file = files[i];
        if (file.match(/\.(lit)?coffee$/)) {
          results.push('src/' + file);
        }
      }
      return results;
    })();
    return run(['-c', '-o', 'lib/coffeescript'].concat(files), callback);
  };

  build = function(callback) {
    buildParser();
    return buildExceptParser(callback);
  };

  transpile = function(code, options = {}) {
    var babel, babelOptions, presets;
    options.minify = process.env.MINIFY !== 'false';
    options.transform = process.env.TRANSFORM !== 'false';
    if (options.sourceType == null) {
      options.sourceType = 'script';
    }
    babel = require('@babel/core');
    presets = [];
    if (options.transform) {
      // Exclude the `modules` plugin in order to not break the `}(this));`
      // at the end of the `build:browser` code block.
      presets.push([
        '@babel/env',
        {
          modules: false
        }
      ]);
    }
    if (options.minify) {
      presets.push([
        'minify',
        {
          mangle: false,
          evaluate: false,
          removeUndefined: false
        }
      ]);
    }
    babelOptions = {
      presets: presets,
      compact: options.minify,
      minified: options.minify,
      comments: !options.minify,
      sourceType: options.sourceType
    };
    if (presets.length !== 0) {
      ({code} = babel.transformSync(code, babelOptions));
    }
    return code;
  };

  testBuiltCode = function(watch = false) {
    var csDir, csPath, mod, testResults;
    csPath = './lib/coffeescript';
    csDir = path.dirname(require.resolve(csPath));
    for (mod in require.cache) {
      if (csDir === mod.slice(0, csDir.length)) {
        delete require.cache[mod];
      }
    }
    testResults = runTests(require(csPath));
    if (!watch) {
      if (!testResults) {
        return process.exit(1);
      }
    }
  };

  buildAndTest = function(includingParser = true, harmony = false) {
    var buildArgs;
    process.stdout.write('\x1Bc'); // Clear terminal screen.
    execSync('git checkout lib/*', {
      stdio: 'inherit' // Reset the generated compiler.
    });
    buildArgs = ['bin/cake'];
    buildArgs.push(includingParser ? 'build' : 'build:except-parser');
    log(`building${includingParser ? ', including parser' : ''}...`, green);
    return spawnNodeProcess(buildArgs, 'both', function() {
      var testArgs;
      log('testing...', green);
      testArgs = harmony ? ['--harmony'] : [];
      testArgs = testArgs.concat(['bin/cake', 'test']);
      return spawnNodeProcess(testArgs, 'both');
    });
  };

  watchAndBuildAndTest = function(harmony = false) {
    buildAndTest(true, harmony);
    fs.watch('src/', {
      interval: 200
    }, function(eventType, filename) {
      if (eventType === 'change') {
        log(`src/${filename} changed, rebuilding...`);
        return buildAndTest(filename === 'grammar.coffee', harmony);
      }
    });
    return fs.watch('test/', {
      interval: 200,
      recursive: true
    }, function(eventType, filename) {
      if (eventType === 'change') {
        log(`test/${filename} changed, rebuilding...`);
        return buildAndTest(false, harmony);
      }
    });
  };

  task('build', 'build the CoffeeScript compiler from source', build);

  task('build:parser', 'build the Jison parser only', buildParser);

  task('build:except-parser', 'build the CoffeeScript compiler, except for the Jison parser', buildExceptParser);

  task('build:full', 'build the CoffeeScript compiler from source twice, and run the tests', function() {
    return build(function() {
      return build(testBuiltCode);
    });
  });

  task('build:browser', 'merge the built scripts into a single file for use in a browser', function() {
    var code, i, j, len, len1, moduleCode, name, outputFolder, outputFolders, ref, results, scriptCode;
    code = `require['../../package.json'] = (function() {
  return ${fs.readFileSync("./package.json")};
})();`;
    ref = ['helpers', 'rewriter', 'lexer', 'parser', 'scope', 'nodes', 'sourcemap', 'coffeescript', 'browser'];
    for (i = 0, len = ref.length; i < len; i++) {
      name = ref[i];
      code += `require['./${name}'] = (function() {
  var exports = {}, module = {exports: exports};
  ${fs.readFileSync(`lib/coffeescript/${name}.js`)}
  return module.exports;
})();`;
    }
    // From here, we generate two outputs: a legacy script output for all browsers
    // and a module output for browsers that support `<script type="module">`.
    code = `var CoffeeScript = function() {
  function require(path){ return require[path]; }
  ${code}
  return require['./browser'];
}();`;
    scriptCode = transpile(`(function(root) {
  ${code}

  if (typeof define === 'function' && define.amd) {
    define(function() { return CoffeeScript; });
  } else {
    root.CoffeeScript = CoffeeScript;
  }
}(this));`);
    moduleCode = transpile(`${code}

export default CoffeeScript;
const { VERSION, compile, eval: evaluate, load, run, runScripts } = CoffeeScript;
export { VERSION, compile, evaluate as eval, load, run, runScripts };`, {
      sourceType: 'module'
    });
    outputFolders = [`docs/v${majorVersion}/browser-compiler-legacy`, `docs/v${majorVersion}/browser-compiler-modern`, "lib/coffeescript-browser-compiler-legacy", "lib/coffeescript-browser-compiler-modern"];
    results = [];
    for (j = 0, len1 = outputFolders.length; j < len1; j++) {
      outputFolder = outputFolders[j];
      if (!fs.existsSync(outputFolder)) {
        fs.mkdirSync(outputFolder);
      }
      results.push(fs.writeFileSync(`${outputFolder}/coffeescript.js`, `${header}
${outputFolder.includes('legacy') ? scriptCode : moduleCode}`));
    }
    return results;
  });

  task('build:browser:full', 'merge the built scripts into a single file for use in a browser, and test it', function() {
    invoke('build:browser');
    console.log("built ... running browser tests:");
    return invoke('test:browser');
  });

  task('build:watch', 'watch and continually rebuild the CoffeeScript compiler, running tests on each build', function() {
    return watchAndBuildAndTest();
  });

  task('build:watch:harmony', 'watch and continually rebuild the CoffeeScript compiler, running harmony tests on each build', function() {
    return watchAndBuildAndTest(true);
  });

  buildDocs = function(watch = false) {
    var changelogSourceFolder, codeFor, examplesSourceFolder, exception, htmlFor, i, include, includeScript, indexFile, len, outputFolder, ref, releaseHeader, renderIndex, sectionsSourceFolder, siteSourceFolder, target;
    // Constants
    indexFile = 'documentation/site/index.html';
    siteSourceFolder = "documentation/site";
    sectionsSourceFolder = 'documentation/sections';
    changelogSourceFolder = 'documentation/sections/changelog';
    examplesSourceFolder = 'documentation/examples';
    outputFolder = `docs/v${majorVersion}`;
    // Helpers
    releaseHeader = function(date, version, prevVersion) {
      return `<h3>${prevVersion && `<a href=\"https://github.com/jashkenas/coffeescript/compare/${prevVersion}...${version}\">${version}</a>` || version}
  <span class="timestamp"> &mdash; <time datetime="${date}">${date}</time></span>
</h3>`;
    };
    codeFor = require("./documentation/site/code.coffee");
    htmlFor = function() {
      var defaultFence, hljs, markdownRenderer;
      hljs = require('highlight.js');
      hljs.configure({
        classPrefix: ''
      });
      markdownRenderer = require('markdown-it')({
        html: true,
        typographer: true,
        highlight: function(str, language) {
          var ex;
          // From https://github.com/markdown-it/markdown-it#syntax-highlighting
          if (language && hljs.getLanguage(language)) {
            try {
              return hljs.highlight(str, {language}).value;
            } catch (error1) {
              ex = error1;
            }
          }
          return ''; // No syntax highlighting
        }
      });
      
      // Add some custom overrides to Markdown-It’s rendering, per
      // https://github.com/markdown-it/markdown-it/blob/master/docs/architecture.md#renderer
      defaultFence = markdownRenderer.renderer.rules.fence;
      markdownRenderer.renderer.rules.fence = function(tokens, idx, options, env, slf) {
        var code;
        code = tokens[idx].content;
        if (code.indexOf('codeFor(') === 0 || code.indexOf('releaseHeader(') === 0) {
          return `<%= ${code} %>`;
        } else {
          return `<blockquote class=\"uneditable-code-block\">${defaultFence.apply(this, arguments)}</blockquote>`;
        }
      };
      return function(file, bookmark) {
        var html, md;
        md = fs.readFileSync(`${sectionsSourceFolder}/${file.replace(/\//g, path.sep)}.md`, 'utf-8');
        md = md.replace(/<%= releaseHeader %>/g, releaseHeader);
        md = md.replace(/<%= majorVersion %>/g, majorVersion);
        md = md.replace(/<%= fullVersion %>/g, CoffeeScript.VERSION);
        html = markdownRenderer.render(md);
        return html = _.template(html)({
          codeFor: codeFor(),
          releaseHeader: releaseHeader
        });
      };
    };
    includeScript = function() {
      return function(file) {
        var code;
        if (indexOf.call(file, '/') < 0) {
          file = `${siteSourceFolder}/${file}`;
        }
        code = fs.readFileSync(file, 'utf-8');
        code = CoffeeScript.compile(code);
        code = transpile(code);
        return code;
      };
    };
    include = function() {
      return function(file) {
        var output, render;
        if (indexOf.call(file, '/') < 0) {
          file = `${siteSourceFolder}/${file}`;
        }
        output = fs.readFileSync(file, 'utf-8');
        if (/\.html$/.test(file)) {
          render = _.template(output);
          output = render({
            releaseHeader: releaseHeader,
            majorVersion: majorVersion,
            fullVersion: CoffeeScript.VERSION,
            htmlFor: htmlFor(),
            codeFor: codeFor(),
            include: include(),
            includeScript: includeScript()
          });
        }
        return output;
      };
    };
    // Task
    (renderIndex = function() {
      var output, render;
      render = _.template(fs.readFileSync(indexFile, 'utf-8'));
      output = render({
        include: include()
      });
      fs.writeFileSync(`${outputFolder}/index.html`, output);
      return log('compiled', green, `${indexFile} → ${outputFolder}/index.html`);
    })();
    try {
      fs.symlinkSync(`v${majorVersion}/index.html`, 'docs/index.html');
    } catch (error1) {
      exception = error1;
    }
    if (watch) {
      ref = [indexFile, siteSourceFolder, examplesSourceFolder, sectionsSourceFolder, changelogSourceFolder];
      for (i = 0, len = ref.length; i < len; i++) {
        target = ref[i];
        fs.watch(target, {
          interval: 200
        }, renderIndex);
      }
      return log('watching...', green);
    }
  };

  task('doc:site', 'build the documentation for the website', function() {
    return buildDocs();
  });

  task('doc:site:watch', 'watch and continually rebuild the documentation for the website', function() {
    return buildDocs(true);
  });

  buildDocTests = function(watch = false) {
    var i, len, outputFolder, ref, renderTest, target, testFile, testHelpers, testsInScriptBlocks, testsSourceFolder;
    // Constants
    testFile = 'documentation/site/test.html';
    testsSourceFolder = 'test';
    outputFolder = `docs/v${majorVersion}`;
    // Included in test.html
    testHelpers = fs.readFileSync('test/support/helpers.coffee', 'utf-8').replace(/exports\./g, '@');
    // Helpers
    testsInScriptBlocks = function() {
      var filename, i, len, output, ref, type;
      output = '';
      ref = fs.readdirSync(testsSourceFolder).sort();
      for (i = 0, len = ref.length; i < len; i++) {
        filename = ref[i];
        if (filename.indexOf('.coffee') !== -1) {
          type = 'coffeescript';
        } else if (filename.indexOf('.litcoffee') !== -1) {
          type = 'literate-coffeescript';
        } else {
          continue;
        }
        // Set the type to text/x-coffeescript or text/x-literate-coffeescript
        // to prevent the browser compiler from automatically running the script
        output += `<script type="text/x-${type}" class="test" id="${filename.split('.')[0]}">
${fs.readFileSync(`test/${filename}`, 'utf-8')}
</script>\n`;
      }
      return output;
    };
    // Task
    (renderTest = function() {
      var output, render;
      render = _.template(fs.readFileSync(testFile, 'utf-8'));
      output = render({
        testHelpers: testHelpers,
        tests: testsInScriptBlocks()
      });
      fs.writeFileSync(`${outputFolder}/test.html`, output);
      return log('compiled', green, `${testFile} → ${outputFolder}/test.html`);
    })();
    if (watch) {
      ref = [testFile, testsSourceFolder];
      for (i = 0, len = ref.length; i < len; i++) {
        target = ref[i];
        fs.watch(target, {
          interval: 200
        }, renderTest);
      }
      return log('watching...', green);
    }
  };

  task('doc:test', 'build the browser-based tests', function() {
    return buildDocTests();
  });

  task('doc:test:watch', 'watch and continually rebuild the browser-based tests', function() {
    return buildDocTests(true);
  });

  buildAnnotatedSource = function(watch = false) {
    var generateAnnotatedSource;
    (generateAnnotatedSource = function() {
      exec(`cd src && ../node_modules/docco/bin/docco *.*coffee --output ../docs/v${majorVersion}/annotated-source`, function(err) {
        if (err) {
          throw err;
        }
      });
      return log('generated', green, `annotated source in docs/v${majorVersion}/annotated-source/`);
    })();
    if (watch) {
      fs.watch('src/', {
        interval: 200
      }, generateAnnotatedSource);
      return log('watching...', green);
    }
  };

  task('doc:source', 'build the annotated source documentation', function() {
    return buildAnnotatedSource();
  });

  task('doc:source:watch', 'watch and continually rebuild the annotated source documentation', function() {
    return buildAnnotatedSource(true);
  });

  task('release', 'update dependencies, build and test the CoffeeScript source, and build the documentation', function() {
    return execSync(`npm install --silent
cake build:full
cake build:browser
cake doc:test
cake test:browser:node
cake test:browser
cake test:integrations
cake doc:site
cake doc:source`, {
      stdio: 'inherit'
    });
  });

  task('bench', 'quick benchmark of compilation time', function() {
    var Rewriter, coffee, fmt, js, litcoffee, littokens, nodes, now, sources, time, tokens, total;
    ({Rewriter} = require('./lib/coffeescript/rewriter'));
    sources = ['coffeescript', 'grammar', 'helpers', 'lexer', 'nodes', 'rewriter'];
    coffee = sources.map(function(name) {
      return fs.readFileSync(`src/${name}.coffee`);
    }).join('\n');
    litcoffee = fs.readFileSync("src/scope.litcoffee").toString();
    fmt = function(ms) {
      return ` ${bold}${`   ${ms}`.slice(-4)}${reset} ms`;
    };
    total = 0;
    now = Date.now();
    time = function() {
      var ms;
      total += ms = -(now - (now = Date.now()));
      return fmt(ms);
    };
    tokens = CoffeeScript.tokens(coffee, {
      rewrite: false
    });
    littokens = CoffeeScript.tokens(litcoffee, {
      rewrite: false,
      literate: true
    });
    tokens = tokens.concat(littokens);
    console.log(`Lex    ${time()} (${tokens.length} tokens)`);
    tokens = new Rewriter().rewrite(tokens);
    console.log(`Rewrite${time()} (${tokens.length} tokens)`);
    nodes = CoffeeScript.nodes(tokens);
    console.log(`Parse  ${time()}`);
    js = nodes.compile({
      bare: true
    });
    console.log(`Compile${time()} (${js.length} chars)`);
    return console.log(`total  ${fmt(total)}`);
  });

  // Run the CoffeeScript test suite.
  runTests = function(CoffeeScript) {
    var allFiles, asyncTests, code, currentFile, error, file, filename, files, func, i, len, literate, name, onFail, ref, skipUnless, startTime, testFilesToSkip;
    if (!global.testingBrowser) {
      CoffeeScript.register();
    }
    // These are attached to `global` so that they’re accessible from within
    // `test/async.coffee`, which has an async-capable version of
    // `global.test`.
    global.currentFile = null;
    global.passedTests = 0;
    global.failures = [];
    ref = require('assert');
    for (name in ref) {
      func = ref[name];
      global[name] = func;
    }
    // Convenience aliases.
    global.CoffeeScript = CoffeeScript;
    global.Repl = require('./lib/coffeescript/repl');
    global.bold = bold;
    global.red = red;
    global.green = green;
    global.yellow = yellow;
    global.reset = reset;
    asyncTests = [];
    onFail = function(description, fn, err) {
      return failures.push({
        filename: global.currentFile,
        error: err,
        description: description,
        source: fn.toString != null ? fn.toString() : void 0
      });
    };
    // Our test helper function for delimiting different test cases.
    global.test = function(description, fn) {
      var err, result;
      try {
        fn.test = {description, currentFile};
        result = fn.call(fn);
        if (result instanceof Promise) { // An async test.
          asyncTests.push(result);
          return result.then(function() {
            return passedTests++;
          }).catch(function(err) {
            return onFail(description, fn, err);
          });
        } else {
          return passedTests++;
        }
      } catch (error1) {
        err = error1;
        return onFail(description, fn, err);
      }
    };
    helpers.extend(global, require('./test/support/helpers'));
    // When all the tests have run, collect and print errors.
    // If a stacktrace is available, output the compiled function source.
    process.on('exit', function() {
      var description, error, fail, filename, i, len, message, source, time;
      time = ((Date.now() - startTime) / 1000).toFixed(2);
      message = `passed ${passedTests} tests in ${time} seconds${reset}`;
      if (!failures.length) {
        return log(message, green);
      }
      log(`failed ${failures.length} and ${message}`, red);
      for (i = 0, len = failures.length; i < len; i++) {
        fail = failures[i];
        ({error, filename, description, source} = fail);
        console.log('');
        if (description) {
          log(`  ${description}`, red);
        }
        log(`  ${error.stack}`, red);
        if (source) {
          console.log(`  ${source}`);
        }
      }
    });
    // Run every test in the `test` folder, recording failures, except for files
    // we’re skipping because the features to be tested are unsupported in the
    // current Node runtime.
    testFilesToSkip = [];
    skipUnless = function(featureDetect, filenames) {
      if (!((function() {
        try {
          return new Function(featureDetect);
        } catch (error1) {}
      })())) {
        return testFilesToSkip = testFilesToSkip.concat(filenames);
      }
    };
    skipUnless('async () => {}', ['async.coffee', 'async_iterators.coffee']);
    skipUnless('async function* generator() { yield 42; }', ['async_iterators.coffee']);
    skipUnless('var a = 2 ** 2; a **= 3', ['exponentiation.coffee']);
    skipUnless('var {...a} = {}', ['object_rest_spread.coffee']);
    skipUnless('/foo.bar/s.test("foo\tbar")', ['regex_dotall.coffee']);
    skipUnless('1_2_3', ['numeric_literal_separators.coffee']);
    skipUnless('1n', ['numbers_bigint.coffee']);
    skipUnless('async () => { await import(\'data:application/json,{"foo":"bar"}\', { assert: { type: "json" } }) }', ['import_assertions.coffee']);
    allFiles = fs.readdirSync('test');
    if (process.env.DEBUG_CS3) {
      console.log(`[DEBUG] All files in test/: ${allFiles.length}`);
    }
    files = allFiles.filter(function(filename) {
      var result;
      result = indexOf.call(testFilesToSkip, filename) < 0;
      if (process.env.DEBUG_CS3 && filename.endsWith('.coffee')) {
        console.log(`[DEBUG] Filter ${filename}: ${result} (skip list has ${testFilesToSkip.length} items)`);
      }
      return result;
    });
    if (process.env.DEBUG_CS3) {
      console.log(`[DEBUG] Found ${files.length} test files after filter`);
    }
    startTime = Date.now();
    for (i = 0, len = files.length; i < len; i++) {
      file = files[i];
      if (!(helpers.isCoffee(file))) {
        continue;
      }
      if (process.env.DEBUG_CS3) {
        console.log(`[DEBUG] Running test file: ${file}`);
      }
      literate = helpers.isLiterate(file);
      currentFile = filename = path.join('test', file);
      code = fs.readFileSync(filename);
      try {
        CoffeeScript.run(code.toString(), {filename, literate});
      } catch (error1) {
        error = error1;
        failures.push({filename, error});
      }
    }
    return Promise.all(asyncTests).then(function() {
      if (failures.length !== 0) {
        return Promise.reject();
      }
    });
  };

  task('test', 'run the CoffeeScript language test suite', function() {
    return runTests(CoffeeScript).catch(function() {
      return process.exit(1);
    });
  });

  task('test:cs3', 'run the CoffeeScript test suite using CS3/ES5 backend', function() {
    console.log("Running tests with CS3/ES5 backend...");
    process.env.COFFEESCRIPT_CS3 = 'true';
    return runTests(CoffeeScript).catch(function() {
      return process.exit(1);
    });
  });

  task('test:browser', 'run the test suite against the modern browser compiler in a headless browser', function() {
    var http, serveFile, server;
    // Create very simple web server to serve the two files we need.
    http = require('http');
    serveFile = function(res, fileToServe, mimeType) {
      res.statusCode = 200;
      res.setHeader('Content-Type', mimeType);
      return fs.createReadStream(fileToServe).pipe(res);
    };
    server = http.createServer(function(req, res) {
      if (req.url === '/') {
        return serveFile(res, path.join(__dirname, 'docs', `v${majorVersion}`, 'test.html'), 'text/html');
      } else if (req.url === '/browser-compiler-modern/coffeescript.js') {
        // The `text/javascript` MIME type is required for an ES module file to be
        // loaded in a browser.
        return serveFile(res, path.join(__dirname, 'docs', `v${majorVersion}`, 'browser-compiler-modern', 'coffeescript.js'), 'text/javascript');
      } else {
        res.statusCode = 404;
        return res.end();
      }
    });
    return server.listen(8080, async function() {
      var browser, e, element, page, puppeteer, result;
      puppeteer = require('puppeteer');
      browser = (await puppeteer.launch());
      page = (await browser.newPage());
      result = "";
      try {
        await page.goto('http://localhost:8080/');
        element = (await page.waitForSelector('#result', {
          visible: true,
          polling: 'mutation',
          timeout: 60000
        }));
        result = (await page.evaluate(((el) => {
          return el.textContent;
        }), element));
      } catch (error1) {
        e = error1;
        log(e, red);
      } finally {
        try {
          browser.close();
        } catch (error1) {}
        server.close();
      }
      if (result && !result.includes('failed')) {
        return log(result, green);
      } else {
        log(result, red);
        return process.exit(1);
      }
    });
  });

  task('test:browser:node', 'run the test suite against the legacy browser compiler in Node', function() {
    var result, source;
    source = fs.readFileSync("lib/coffeescript-browser-compiler-legacy/coffeescript.js", 'utf-8');
    result = {};
    global.testingBrowser = true;
    (function() {
      return eval(source);
    }).call(result);
    return runTests(CoffeeScript).catch(function() {
      return process.exit(1);
    });
  });

  task('test:integrations', 'test the module integrated with other libraries and environments', function() {
    var major, minor, tmpdir, webpack;
    // Tools like Webpack and Browserify generate builds intended for a browser
    // environment where Node modules are not available. We want to ensure that
    // the CoffeeScript module as presented by the `browser` key in `package.json`
    // can be built by such tools; if such a build succeeds, it verifies that no
    // Node modules are required as part of the compiler (as opposed to the tests)
    // and that therefore the compiler will run in a browser environment.
    // Webpack 5 requires Node >= 10.13.0.
    [major, minor] = process.versions.node.split('.').map(function(n) {
      return parseInt(n, 10);
    });
    if (major < 10 || (major === 10 && minor < 13)) {
      return;
    }
    tmpdir = os.tmpdir();
    webpack = require('webpack');
    return webpack({
      entry: './',
      optimization: {
        // Webpack’s minification causes the CoffeeScript module to fail some tests.
        minimize: false
      },
      output: {
        path: tmpdir,
        filename: 'coffeescript.js',
        library: 'CoffeeScript',
        libraryTarget: 'commonjs2'
      }
    }, function(err, stats) {
      var builtCompiler, error, i, j, len, len1, ref, ref1, testResults, warning;
      if (err || stats.hasErrors()) {
        if (err) {
          console.error(err.stack || err);
          if (err.details) {
            console.error(err.details);
          }
        }
        if (stats.hasErrors()) {
          ref = stats.compilation.errors;
          for (i = 0, len = ref.length; i < len; i++) {
            error = ref[i];
            console.error(error);
          }
        }
        if (stats.hasWarnings()) {
          ref1 = stats.compilation.warnings;
          for (j = 0, len1 = ref1.length; j < len1; j++) {
            warning = ref1[j];
            console.warn(warning);
          }
        }
        process.exit(1);
      }
      builtCompiler = path.join(tmpdir, 'coffeescript.js');
      ({CoffeeScript} = require(builtCompiler));
      global.testingBrowser = true;
      testResults = runTests(CoffeeScript);
      fs.unlinkSync(builtCompiler);
      if (!testResults) {
        return process.exit(1);
      }
    });
  });

}).call(this);
