// Generated by CoffeeScript 2.7.0
(function() {
  //!/usr/bin/env coffee

  // ==============================================================================
  // CS3 ES5 Backend - Bridge CS3 Data Nodes to CoffeeScript's Existing Compiler
  // ==============================================================================

  // This backend converts CS3 data-oriented AST nodes back into CoffeeScript's
  // class-based nodes, then uses the existing CoffeeScript compiler to generate
  // JavaScript. This gives us an immediate working pipeline!

  // Once this works perfectly and passes all tests, we can evolve it into a
  // true ES6 backend with modern JavaScript features.
  // ==============================================================================

  // Import CoffeeScript's node classes
  var ES5Backend, nodes;

  nodes = require('../../lib/coffeescript/nodes');

  ES5Backend = class ES5Backend {
    constructor(options1 = {}) {
      var ref, ref1, ref2, ref3;
      this.options = options1;
      // Options will be passed to CoffeeScript's compile
      this.compileOptions = {
        bare: (ref = this.options.bare) != null ? ref : true,
        header: (ref1 = this.options.header) != null ? ref1 : false,
        sourceMap: (ref2 = this.options.sourceMap) != null ? ref2 : false,
        inlineMap: (ref3 = this.options.inlineMap) != null ? ref3 : false
      };
    }

    // Main entry point - convert CS3 data node to JavaScript
    generate(dataNode) {
      var classNode, result;
      // Convert CS3 data node to CoffeeScript class node
      classNode = this.dataToClass(dataNode);
      // Use CoffeeScript's existing compile method
      result = classNode.compile(this.compileOptions);
      // Return either the code string or {js, sourceMap} object
      if (this.compileOptions.sourceMap) {
        return result;
      } else {
        return result;
      }
    }

    // Convert CS3 data nodes to CoffeeScript class nodes
    dataToClass(node) {
      var accessNode, accessor, args, assertions, attempt, base, body, bodyNodes, cases, catch_, clause, condition, conditions, context, converted, defaultBinding, defaultLocationData, elseBody, ensure, expr, expression, expressionNodes, expressions, first, flip, forNode, from, funcGlyph, generated, guard, i, ifNode, index, indexNode, item, len, name, namedImports, obj, objNode, objects, op, options, otherwise, p, params, parent, parts, prop, properties, quote, recovery, ref, ref1, ref2, result, second, soak, source, sourceObj, splat, subject, tag, to, value, variable;
      if (!node) {
        return null;
      }
      // Handle primitives
      if ((ref = typeof node) === 'string' || ref === 'number' || ref === 'boolean') {
        return node;
      }
      // Handle arrays
      if (Array.isArray(node)) {
        return node.map((item) => {
          return this.dataToClass(item);
        });
      }
      if (!node.type) {
        // Must be an object with a type
        return null;
      }
      // Convert based on node type
      switch (node.type) {
        // Root and structural nodes
        case 'Root':
          // Root expects a Block, not an array
          bodyNodes = Array.isArray(node.body) ? node.body.map((item) => {
            return this.dataToClass(item);
          }) : node.body ? [this.dataToClass(node.body)] : [];
          body = new nodes.Block(bodyNodes);
          return new nodes.Root(body);
        case 'Block':
          expressions = node.expressions ? this.dataToClass(node.expressions) : node.body ? this.dataToClass(node.body) : [];
          return new nodes.Block(expressions);
        // Literals
        case 'NumberLiteral':
          return new nodes.NumberLiteral(node.value, node.parsedValue);
        case 'StringLiteral':
          // StringLiteral expects the raw string content (without quotes)
          // and a quote character to be provided
          // Default to double quotes if not specified
          quote = node.quote || '"';
          // Ensure we have the actual string value
          value = node.value || '';
          return new nodes.StringLiteral(value, {quote});
        case 'Literal':
          // Generic literal node (used for tokens, operators, etc.)
          return new nodes.Literal(node.value);
        case 'BooleanLiteral':
          return new nodes.BooleanLiteral(node.value);
        case 'NullLiteral':
          return new nodes.NullLiteral();
        case 'UndefinedLiteral':
          return new nodes.UndefinedLiteral();
        case 'InfinityLiteral':
          return new nodes.InfinityLiteral(node.value);
        case 'NaNLiteral':
          return new nodes.NaNLiteral();
        case 'IdentifierLiteral':
          return new nodes.IdentifierLiteral(node.value);
        case 'PropertyName':
          return new nodes.PropertyName(node.value);
        case 'StatementLiteral':
          return new nodes.StatementLiteral(node.value);
        case 'ThisLiteral':
          return new nodes.ThisLiteral(node.value || 'this');
        case 'Super':
          accessor = this.dataToClass(node.accessor);
          return new nodes.Super(accessor);
        case 'RegexLiteral':
          return new nodes.RegexLiteral(node.value, {
            delimiter: node.delimiter,
            heregexCommentTokens: node.heregexCommentTokens
          });
        case 'PassthroughLiteral':
          return new nodes.PassthroughLiteral(node.value, {
            here: node.here,
            generated: node.generated
          });
        // Values and properties
        case 'Value':
          base = this.dataToClass(node.val || node.base || node.value);
          properties = node.properties ? node.properties.map((prop) => {
            return this.dataToClass(prop);
          }) : [];
          return new nodes.Value(base, properties);
        case 'Access':
          name = this.dataToClass(node.name);
          accessNode = new nodes.Access(name);
          if (node.soak) {
            accessNode.soak = node.soak;
          }
          if (node.shorthand) {
            accessNode.shorthand = node.shorthand;
          }
          return accessNode;
        case 'Index':
          index = this.dataToClass(node.object || node.name);
          indexNode = new nodes.Index(index);
          if (node.soak) {
            indexNode.soak = node.soak;
          }
          return indexNode;
        // Assignment
        case 'Assign':
          // Handle object property assignments differently
          if (node.context === 'object' && node.expression) {
            // Object property: node.value is the key, node.expression is the value
            variable = this.dataToClass(node.value);
            value = this.dataToClass(node.expression);
          } else {
            // Regular assignment
            variable = this.dataToClass(node.variable);
            value = this.dataToClass(node.value);
          }
          context = node.context;
          options = {};
          if (node.param) {
            options.param = node.param;
          }
          if (node.subpattern) {
            options.subpattern = node.subpattern;
          }
          // Handle operatorToken carefully - it might be a data node
          if (node.operatorToken) {
            if (typeof node.operatorToken === 'object' && node.operatorToken.type) {
              // It's a data node, just use its value
              options.operatorToken = {
                value: node.operatorToken.value,
                locationData: node.operatorToken.locationData
              };
            } else {
              options.operatorToken = this.dataToClass(node.operatorToken);
            }
          }
          if (node.moduleDeclaration) {
            options.moduleDeclaration = node.moduleDeclaration;
          }
          return new nodes.Assign(variable, value, context, options);
        // Operations
        case 'Op':
          // CS3 uses args: [operator, first, second, ...] format
          if (node.args) {
            [op, first, second, flip] = node.args;
            if (typeof op === 'object') {
              op = op.toString();
            }
            first = this.dataToClass(first);
            if (second) {
              second = this.dataToClass(second);
            }
            return new nodes.Op(op, first, second, flip);
          } else {
            // Fallback to named properties
            op = node.operator || node.op;
            first = this.dataToClass(node.first);
            if (node.second) {
              second = this.dataToClass(node.second);
            }
            return new nodes.Op(op, first, second, node.flip);
          }
          break;
        case 'Existence':
          expression = this.dataToClass(node.expression);
          return new nodes.Existence(expression);
        // Functions and calls
        case 'Code':
          params = node.params ? node.params.map((param) => {
            return this.dataToClass(param);
          }) : [];
          // Code expects a Block for body
          bodyNodes = Array.isArray(node.body) ? node.body.map((item) => {
            return this.dataToClass(item);
          }) : node.body ? [this.dataToClass(node.body)] : [];
          body = new nodes.Block(bodyNodes);
          funcGlyph = ((ref1 = node.funcGlyph) != null ? ref1.glyph : void 0) || '->';
          tag = funcGlyph === '=>' && 'boundfunc' || null;
          return new nodes.Code(params, body, tag);
        case 'Param':
          name = this.dataToClass(node.name);
          if (node.value) {
            value = this.dataToClass(node.value);
          }
          splat = node.splat;
          return new nodes.Param(name, value, splat);
        case 'FuncGlyph':
          // This is metadata, not a real node
          return node;
        case 'Call':
          variable = this.dataToClass(node.variable);
          args = node.args ? node.args.map((arg) => {
            return this.dataToClass(arg);
          }) : [];
          soak = node.soak;
          return new nodes.Call(variable, args, soak);
        case 'SuperCall':
          args = node.args ? node.args.map((arg) => {
            return this.dataToClass(arg);
          }) : [];
          return new nodes.SuperCall(args);
        // Arrays and objects
        case 'Arr':
          objects = (function() {
            var i, len, ref2;
            if (node.objects) {
              // Flatten and process the objects array
              result = [];
              ref2 = node.objects;
              for (i = 0, len = ref2.length; i < len; i++) {
                obj = ref2[i];
                // Handle nested arrays (from the parser)
                if (Array.isArray(obj)) {
                  // Unwrap single-element arrays
                  if (obj.length === 1) {
                    converted = this.dataToClass(obj[0]);
                    if (converted) {
                      result.push(converted);
                    }
                  }
                } else if (typeof obj === 'object' && Object.keys(obj).length > 0) {
                  // Non-empty objects
                  converted = this.dataToClass(obj);
                  if (converted) {
                    result.push(converted);
                  }
                }
              }
              return result;
            } else if (node.value) {
              // Handle value array (e.g., empty array case)
              if (Array.isArray(node.value)) {
                // Filter out empty objects
                return node.value.filter(function(v) {
                  return !(typeof v === 'object' && Object.keys(v).length === 0);
                }).map((v) => {
                  return this.dataToClass(v);
                });
              } else {
                return [this.dataToClass(node.value)];
              }
            } else {
              return [];
            }
          }).call(this);
          return new nodes.Arr(objects);
        case 'Obj':
          properties = (function() {
            var i, j, len, len1, ref2;
            if (node.properties) {
              // Flatten properties array in case it contains nested arrays
              result = [];
              ref2 = node.properties;
              for (i = 0, len = ref2.length; i < len; i++) {
                prop = ref2[i];
                if (Array.isArray(prop)) {
// Flatten nested array
                  for (j = 0, len1 = prop.length; j < len1; j++) {
                    item = prop[j];
                    converted = this.dataToClass(item);
                    if (converted) {
                      result.push(converted);
                    }
                  }
                } else if (prop) {
                  converted = this.dataToClass(prop);
                  if (converted) {
                    result.push(converted);
                  }
                }
              }
              return result;
            } else {
              return [];
            }
          }).call(this);
          generated = node.generated;
          return new nodes.Obj(properties, generated);
        case 'Range':
          from = this.dataToClass(node.from);
          to = this.dataToClass(node.to);
          tag = node.exclusive ? 'exclusive' : 'inclusive';
          return new nodes.Range(from, to, tag);
        // Control flow
        case 'If':
        case 'if':
        case 'unless':
          condition = this.dataToClass(node.condition);
          // Convert array of nodes to Block with converted nodes
          body = Array.isArray(node.body) ? (bodyNodes = node.body.map((n) => {
            return this.dataToClass(n);
          }), new nodes.Block(bodyNodes)) : this.dataToClass(node.body);
          options = {};
          if (node.type) {
            options.type = node.type;
          }
          if (node.postfix) {
            options.postfix = node.postfix;
          }
          // Create the If node
          ifNode = new nodes.If(condition, body, options);
          // If there's an else clause, add it
          if (node.elseBody) {
            elseBody = Array.isArray(node.elseBody) ? (bodyNodes = node.elseBody.map((n) => {
              return this.dataToClass(n);
            }), new nodes.Block(bodyNodes)) : this.dataToClass(node.elseBody);
            ifNode.elseBody = elseBody;
            ifNode.isChain = elseBody instanceof nodes.If;
          }
          return ifNode;
        case 'While':
          condition = this.dataToClass(node.condition);
          if (node.guard) {
            guard = this.dataToClass(node.guard);
          }
          body = Array.isArray(node.body) ? new nodes.Block(this.dataToClass(node.body)) : this.dataToClass(node.body);
          return new nodes.While(condition, guard).addBody(body);
        case 'For':
          // Convert body first
          body = Array.isArray(node.body) ? (bodyNodes = node.body.map((n) => {
            converted = this.dataToClass(n);
            if (converted) {
              // Ensure each node has locationData
              if (converted.locationData == null) {
                converted.locationData = {
                  first_line: 0,
                  first_column: 0,
                  last_line: 0,
                  last_column: 0,
                  range: [0, 0]
                };
              }
            }
            return converted;
          }), new nodes.Block(bodyNodes)) : node.body ? this.dataToClass(node.body) : new nodes.Block([]);
          // Add dummy locationData to body to prevent errors
          defaultLocationData = {
            first_line: 0,
            first_column: 0,
            last_line: 0,
            last_column: 0,
            range: [0, 0]
          };
          if (body.locationData == null) {
            body.locationData = defaultLocationData;
          }
          
          // Ensure expressions have locationData too
          if (body.expressions) {
            ref2 = body.expressions;
            for (i = 0, len = ref2.length; i < len; i++) {
              expr = ref2[i];
              if (expr.locationData == null) {
                expr.locationData = defaultLocationData;
              }
            }
          }
          // Convert source and build ForSource object
          sourceObj = {};
          if (node.source) {
            sourceObj.source = this.dataToClass(node.source);
          }
          if (node.guard) {
            sourceObj.guard = this.dataToClass(node.guard);
          }
          if (node.step) {
            sourceObj.step = this.dataToClass(node.step);
          }
          if (node.name) {
            sourceObj.name = this.dataToClass(node.name);
          }
          if (node.index) {
            sourceObj.index = this.dataToClass(node.index);
          }
          if (node.object) {
            sourceObj.object = node.object;
          }
          if (node.from) {
            sourceObj.from = node.from;
          }
          if (node.own) {
            sourceObj.own = node.own;
          }
          if (node.await) {
            sourceObj.await = node.await;
          }
          if (node.awaitTag) {
            sourceObj.awaitTag = this.dataToClass(node.awaitTag);
          }
          if (node.ownTag) {
            sourceObj.ownTag = this.dataToClass(node.ownTag);
          }
          
          // Create For node with body and source object
          forNode = new nodes.For(body, sourceObj);
          return forNode;
        case 'Source':
          // Source is a wrapper node in CS3 - unwrap it
          return this.dataToClass(node.value);
        case 'Switch':
          subject = this.dataToClass(node.subject);
          cases = node.cases ? node.cases.map((c) => {
            return this.dataToClass(c);
          }) : [];
          if (node.otherwise) {
            otherwise = this.dataToClass(node.otherwise);
          }
          return new nodes.Switch(subject, cases, otherwise);
        case 'SwitchWhen':
          conditions = this.dataToClass(node.conditions);
          body = this.dataToClass(node.body);
          return new nodes.SwitchWhen(conditions, body);
        case 'Try':
          attempt = this.dataToClass(node.attempt);
          if (node.catch) {
            catch_ = this.dataToClass(node.catch);
          }
          if (node.ensure) {
            ensure = this.dataToClass(node.ensure);
          }
          return new nodes.Try(attempt, catch_, ensure);
        case 'Catch':
          recovery = this.dataToClass(node.recovery || node.body);
          if (node.variable) {
            variable = this.dataToClass(node.variable);
          }
          return new nodes.Catch(recovery, variable);
        case 'Throw':
          expression = this.dataToClass(node.expression);
          return new nodes.Throw(expression);
        case 'Return':
          if (node.expression) {
            expression = this.dataToClass(node.expression);
          }
          return new nodes.Return(expression);
        case 'YieldReturn':
          if (node.expression) {
            expression = this.dataToClass(node.expression);
          }
          return new nodes.YieldReturn(expression);
        case 'AwaitReturn':
          if (node.expression) {
            expression = this.dataToClass(node.expression);
          }
          return new nodes.AwaitReturn(expression);
        // Classes
        case 'Class':
          if (node.variable) {
            variable = this.dataToClass(node.variable);
          }
          if (node.parent) {
            parent = this.dataToClass(node.parent);
          }
          // Body is an array of nodes
          body = (function() {
            var j, k, l, len1, len2, len3, ref3, ref4, ref5;
            if (Array.isArray(node.body)) {
              // Check if the body contains an Obj node (which holds the methods)
              // CS3 represents class methods as an object literal
              bodyNodes = [];
              ref3 = node.body;
              for (j = 0, len1 = ref3.length; j < len1; j++) {
                item = ref3[j];
                if (item.type === 'Value' && ((ref4 = item.val) != null ? ref4.type : void 0) === 'Obj') {
                  // Extract the properties from the Obj node as individual methods
                  objNode = item.val;
                  if (objNode.properties) {
                    ref5 = objNode.properties;
                    for (k = 0, len2 = ref5.length; k < len2; k++) {
                      prop = ref5[k];
                      if (Array.isArray(prop)) {
// Handle nested arrays (multi-line objects)
                        for (l = 0, len3 = prop.length; l < len3; l++) {
                          p = prop[l];
                          converted = this.dataToClass(p);
                          if (converted) {
                            bodyNodes.push(converted);
                          }
                        }
                      } else if (prop) {
                        converted = this.dataToClass(prop);
                        if (converted) {
                          bodyNodes.push(converted);
                        }
                      }
                    }
                  }
                } else {
                  // Regular body node
                  converted = this.dataToClass(item);
                  if (converted) {
                    bodyNodes.push(converted);
                  }
                }
              }
              return new nodes.Block(bodyNodes);
            } else if (node.body) {
              return this.dataToClass(node.body);
            } else {
              return new nodes.Block([]);
            }
          }).call(this);
          return new nodes.Class(variable, parent, body);
        // Splats and expansions
        case 'Splat':
          name = this.dataToClass(node.name || node.body);
          return new nodes.Splat(name);
        case 'Expansion':
          return new nodes.Expansion();
        // Parentheticals
        case 'Parens':
          // If body is an array, wrap in Block
          body = Array.isArray(node.body) ? (bodyNodes = node.body.map((n) => {
            return this.dataToClass(n);
          }), new nodes.Block(bodyNodes)) : this.dataToClass(node.body);
          return new nodes.Parens(body);
        // String interpolation
        case 'StringWithInterpolations':
          // The body should be a Block containing the parts
          body = node.body ? (parts = node.body.map((part) => {
            return this.dataToClass(part);
          }), new nodes.Block(parts)) : new nodes.Block([]);
          quote = node.quote || '"';
          return new nodes.StringWithInterpolations(body, {quote});
        case 'Interpolation':
          // For single-element arrays, just use the element
          // Wrap multiple expressions in Block
          expression = Array.isArray(node.expression) ? node.expression.length === 1 ? this.dataToClass(node.expression[0]) : (expressionNodes = node.expression.map((n) => {
            return this.dataToClass(n);
          }), new nodes.Block(expressionNodes)) : node.expression ? this.dataToClass(node.expression) : new nodes.Block([]);
          return new nodes.Interpolation(expression);
        // Import/Export
        case 'ImportDeclaration':
          if (node.clause) {
            clause = this.dataToClass(node.clause);
          }
          source = this.dataToClass(node.source);
          if (node.assertions) {
            assertions = this.dataToClass(node.assertions);
          }
          return new nodes.ImportDeclaration(clause, source, assertions);
        case 'ImportClause':
          if (node.defaultBinding) {
            defaultBinding = this.dataToClass(node.defaultBinding);
          }
          if (node.namedImports) {
            namedImports = this.dataToClass(node.namedImports);
          }
          return new nodes.ImportClause(defaultBinding, namedImports);
        case 'ExportDeclaration':
          // Handle various export types
          return new nodes.ExportDeclaration(this.dataToClass(node.clause));
        default:
          // Default case - warn and return a comment
          console.warn(`Unknown CS3 node type: ${node.type}`);
          return new nodes.PassthroughLiteral(`/* Unknown node type: ${node.type} */`);
      }
    }

  };

  // Export the backend
  module.exports = ES5Backend;

}).call(this);
