// Generated by CoffeeScript 2.7.0
(function() {
  //!/usr/bin/env coffee

  // ==============================================================================
  // CS3 ES5 Backend - Clean Room Implementation
  // ==============================================================================

  // Converts CS3 data-oriented AST nodes to CoffeeScript's class-based AST nodes
  // Then uses the existing CoffeeScript compiler to generate JavaScript

  // Key fixes in this version:
  // 1. Loop variable conflict prevention
  // 2. Proper super call handling
  // 3. Array elision support
  // ==============================================================================
  var ES5Backend, nodes;

  nodes = require('../../lib/coffeescript/nodes');

  ES5Backend = class ES5Backend {
    constructor(options1 = {}) {
      var ref, ref1, ref2, ref3;
      this.options = options1;
      this.compileOptions = {
        bare: (ref = this.options.bare) != null ? ref : true,
        header: (ref1 = this.options.header) != null ? ref1 : false,
        sourceMap: (ref2 = this.options.sourceMap) != null ? ref2 : false,
        inlineMap: (ref3 = this.options.inlineMap) != null ? ref3 : false,
        // Signal to nodes compiler that we're in CS3 pipeline, so it can relax
        // early "this-before-super" checks to let our lowering run.
        cs3: true
      };
    }

    // Main entry point - convert CS3 data node to JavaScript
    generate(dataNode) {
      var classNode;
      classNode = this.dataToClass(dataNode);
      return classNode.compile(this.compileOptions);
    }

    // Helper to create default locationData
    defaultLocationData() {
      return {
        first_line: 0,
        first_column: 0,
        last_line: 0,
        last_column: 0,
        last_line_exclusive: 0,
        last_column_exclusive: 0,
        range: [0, 0]
      };
    }

    // Helper to ensure value is a proper node
    ensureNode(value) {
      if (value == null) {
        return null;
      }
      if (value.compileToFragments || value instanceof nodes.Base) {
        return value;
      }
      // Wrap primitives in Literal
      return new nodes.Literal(String(value));
    }

    // Helper to filter and ensure all items are nodes
    filterNodes(array) {
      var i, item, len, node, result;
      if (array == null) {
        return [];
      }
      result = [];
      for (i = 0, len = array.length; i < len; i++) {
        item = array[i];
        node = this.ensureNode(this.dataToClass(item));
        if (node != null) {
          result.push(node);
        }
      }
      return result;
    }

    // Convert CS3 data nodes to CoffeeScript class nodes
    dataToClass(node) {
      var access, accessNode, accessor, arg, args, assertions, assignments, atParam, atParams, attempt, attemptNode, base, body, bodyNode, bodyNodes, cases, catch_, clause, codeNode, condition, conditions, context, converted, defaultBinding, elision, elseBody, ensure, ensureNode, expr, expression, expressionNodes, expressions, first, flatParams, flip, from, funcGlyph, generated, guard, i, ifNode, index, indexNode, isAtParam, item, j, k, l, left, len, len1, len2, len3, len4, m, meta, name, nameNode, namedImports, obj, objNode, objects, op, options, otherwise, otherwiseNode, p, param, params, parent, parts, processedParams, prop, propName, properties, property, quote, range, recovery, recoveryNode, ref, ref1, ref2, ref3, ref4, ref5, ref6, ref7, ref8, ref9, result, returnKeyword, right, second, simpleParam, soak, source, sourceObj, splat, stringNode, subject, tag, thisLit, to, value, valueNode, variable;
      if (node == null) {
        return null;
      }
      if ((ref = typeof node) === 'string' || ref === 'number' || ref === 'boolean') {
        // Handle primitives
        return node;
      }
      // Handle arrays
      if (Array.isArray(node)) {
        return node.map((item) => {
          return this.dataToClass(item);
        });
      }
      if (!(node != null ? node.type : void 0)) {
        // Must be an object with a type
        return null;
      }
      switch (node.type) {
        // ============================================================
        // Root and Structural Nodes
        // ============================================================
        case 'Root':
          bodyNodes = Array.isArray(node.body) ? this.filterNodes(node.body) : node.body ? (converted = this.dataToClass(node.body), converted != null ? [converted] : []) : [];
          return new nodes.Root(new nodes.Block(bodyNodes));
        case 'Block':
          expressions = node.expressions ? (converted = this.dataToClass(node.expressions), Array.isArray(converted) ? converted.filter(function(item) {
            return item != null;
          }) : converted != null ? [converted] : []) : node.body ? (converted = this.dataToClass(node.body), Array.isArray(converted) ? converted.filter(function(item) {
            return item != null;
          }) : converted != null ? [converted] : []) : [];
          return new nodes.Block(expressions);
        // ============================================================
        // Literals
        // ============================================================
        case 'NumberLiteral':
          return new nodes.NumberLiteral(node.value, node.parsedValue);
        case 'StringLiteral':
          quote = node.quote || '"';
          value = node.value || '';
          stringNode = new nodes.StringLiteral(value, {quote});
          // Critical: Must have locationData and originalValue
          stringNode.locationData = node.locationData || this.defaultLocationData();
          stringNode.originalValue = value;
          return stringNode;
        case 'Literal':
          return new nodes.Literal(node.value);
        case 'BooleanLiteral':
          return new nodes.BooleanLiteral(node.value);
        case 'NullLiteral':
          return new nodes.NullLiteral();
        case 'UndefinedLiteral':
          return new nodes.UndefinedLiteral();
        case 'InfinityLiteral':
          return new nodes.InfinityLiteral(node.value);
        case 'NaNLiteral':
          return new nodes.NaNLiteral();
        case 'IdentifierLiteral':
          return new nodes.IdentifierLiteral(node.value);
        case 'PropertyName':
          return new nodes.PropertyName(node.value);
        case 'StatementLiteral':
          return new nodes.StatementLiteral(node.value);
        case 'ThisLiteral':
          return new nodes.ThisLiteral(node.value || 'this');
        case 'RegexLiteral':
          return new nodes.RegexLiteral(node.value, {
            delimiter: node.delimiter,
            heregexCommentTokens: node.heregexCommentTokens
          });
        case 'PassthroughLiteral':
          return new nodes.PassthroughLiteral(node.value, {
            here: node.here,
            generated: node.generated
          });
        // ============================================================
        // Values and Properties
        // ============================================================
        case 'Value':
          base = this.dataToClass(node.val || node.base || node.value);
          if (!base) {
            // Handle empty Value nodes (like in "yield" without operand)
            base = new nodes.UndefinedLiteral();
          }
          properties = (function() {
            var i, j, len, len1, ref1;
            if (node.properties) {
              result = [];
              ref1 = node.properties;
              for (i = 0, len = ref1.length; i < len; i++) {
                prop = ref1[i];
                if (Array.isArray(prop)) {
// Handle nested arrays (like [[Access, Access]] for ::)
                  for (j = 0, len1 = prop.length; j < len1; j++) {
                    item = prop[j];
                    converted = this.dataToClass(item);
                    if (converted) {
                      result.push(converted);
                    }
                  }
                } else {
                  converted = this.dataToClass(prop);
                  if (converted) {
                    result.push(converted);
                  }
                }
              }
              return result;
            } else {
              return [];
            }
          }).call(this);
          return new nodes.Value(base, properties);
        case 'Access':
          name = this.dataToClass(node.name);
          accessNode = new nodes.Access(name);
          if (node.soak) {
            accessNode.soak = node.soak;
          }
          if (node.shorthand) {
            accessNode.shorthand = node.shorthand;
          }
          return accessNode;
        case 'Index':
          index = this.dataToClass(node.object || node.name);
          indexNode = new nodes.Index(index);
          if (node.soak) {
            indexNode.soak = node.soak;
          }
          return indexNode;
        // ============================================================
        // Assignment
        // ============================================================
        case 'Assign':
          // Handle object property assignments
          if (node.context === 'object' && node.expression) {
            variable = this.dataToClass(node.value);
            value = this.dataToClass(node.expression);
          } else {
            variable = this.dataToClass(node.variable);
            value = this.dataToClass(node.value);
          }
          if (!((variable != null) && (value != null))) {
            return null;
          }
          context = node.context;
          options = {};
          if (node.param) {
            options.param = node.param;
          }
          if (node.subpattern) {
            options.subpattern = node.subpattern;
          }
          if (node.operatorToken) {
            if (typeof node.operatorToken === 'object' && node.operatorToken.type) {
              options.operatorToken = {
                value: node.operatorToken.value,
                locationData: node.operatorToken.locationData
              };
            } else {
              options.operatorToken = this.dataToClass(node.operatorToken);
            }
          }
          if (node.moduleDeclaration) {
            options.moduleDeclaration = node.moduleDeclaration;
          }
          return new nodes.Assign(variable, value, context, options);
        // ============================================================
        // Operations
        // ============================================================
        case 'Op':
          if (node.args) {
            [op, first, second, flip] = node.args;
            if (typeof op === 'object') {
              op = op.toString();
            }
            first = this.dataToClass(first);
            if (second) {
              second = this.dataToClass(second);
            }
            // Critical: Pass invertOperator and originalOperator
            options = {};
            if (node.invertOperator) {
              options.invertOperator = node.invertOperator;
            }
            if (node.originalOperator) {
              options.originalOperator = node.originalOperator;
            }
            return new nodes.Op(op, first, second, flip, options);
          } else {
            op = node.operator || node.op;
            first = this.dataToClass(node.first);
            if (node.second) {
              second = this.dataToClass(node.second);
            }
            return new nodes.Op(op, first, second, node.flip);
          }
          break;
        case 'Existence':
          expression = this.dataToClass(node.expression);
          return new nodes.Existence(expression);
        // ============================================================
        // Functions and Calls
        // ============================================================
        case 'Code':
          // First, flatten params and collect @params to generate thisAssignments
          flatParams = [];
          atParams = []; // Track @params to lower and assign in body
          if (node.params) {
            ref1 = node.params;
            for (i = 0, len = ref1.length; i < len; i++) {
              param = ref1[i];
              if (Array.isArray(param)) {
                for (j = 0, len1 = param.length; j < len1; j++) {
                  p = param[j];
                  flatParams.push(p);
                }
              } else {
                flatParams.push(param);
              }
            }
          }
          // Process params, handling @params by lowering them to plain params
          processedParams = [];
          for (k = 0, len2 = flatParams.length; k < len2; k++) {
            param = flatParams[k];
            // Check if this is an @param that needs special handling
            isAtParam = (param != null ? param.type : void 0) === 'Param' && ((ref2 = param.name) != null ? ref2.type : void 0) === 'Value' && ((ref3 = param.name.val) != null ? ref3.type : void 0) === 'ThisLiteral' && ((ref4 = param.name.properties) != null ? ref4.length : void 0) > 0;
            if (isAtParam) {
              // Convert @name to regular name parameter for all functions
              propName = param.name.properties[0].name.value;
              // Create a simple param directly with nodes classes
              nameNode = new nodes.IdentifierLiteral(propName);
              // Handle default values if present
              if (param.value) {
                valueNode = this.dataToClass(param.value);
                simpleParam = new nodes.Param(nameNode, valueNode);
              } else {
                simpleParam = new nodes.Param(nameNode);
              }
              // Handle splat if present
              if (param.splat) {
                simpleParam.splat = param.splat;
              }
              processedParams.push(simpleParam);
              // Save assignment to be applied in body (ideally after super)
              atParams.push({
                name: propName
              });
            } else {
              // Regular param
              converted = this.dataToClass(param);
              if (converted) {
                processedParams.push(converted);
              }
            }
          }
          params = processedParams;
          bodyNodes = Array.isArray(node.body) ? this.filterNodes(node.body) : node.body ? (converted = this.dataToClass(node.body), converted != null ? [converted] : []) : [];
          // Build a nodes.Code and attach thisAssignments; compiler will inject
          // them after super() when possible via expandCtorSuper.
          body = new nodes.Block(bodyNodes);
          funcGlyph = ((ref5 = node.funcGlyph) != null ? ref5.glyph : void 0) || '->';
          tag = funcGlyph === '=>' ? 'boundfunc' : null;
          codeNode = new nodes.Code(params, body, tag);
          if (atParams.length > 0) {
            assignments = [];
            for (l = 0, len3 = atParams.length; l < len3; l++) {
              atParam = atParams[l];
              thisLit = new nodes.ThisLiteral();
              access = new nodes.Access(new nodes.PropertyName(atParam.name));
              left = new nodes.Value(thisLit, [access]);
              right = new nodes.IdentifierLiteral(atParam.name);
              assignments.push(new nodes.Assign(left, right));
            }
            codeNode.thisAssignments = assignments;
          }
          return codeNode;
        case 'Param':
          name = this.dataToClass(node.name);
          if (node.value) {
            value = this.dataToClass(node.value);
          }
          splat = node.splat;
          return new nodes.Param(name, value, splat);
        case 'Call':
          variable = this.dataToClass(node.variable);
          args = node.args ? this.filterNodes(node.args) : [];
          soak = node.soak;
          return new nodes.Call(variable, args, soak);
        case 'Super':
          if (node.accessor) {
            accessor = this.dataToClass(node.accessor);
          }
          return new nodes.Super(accessor);
        case 'SuperCall':
          // SuperCall extends Call(variable, args, soak)
          // The variable should be a Super node
          variable = node.variable ? this.dataToClass(node.variable) : new nodes.Super();
          // Process arguments, filtering out empty objects
          args = (function() {
            var len4, m, ref6;
            if (node.args) {
              result = [];
              ref6 = node.args;
              for (m = 0, len4 = ref6.length; m < len4; m++) {
                arg = ref6[m];
                // Skip empty objects
                if ((arg != null) && (arg.type || Object.keys(arg).length > 0)) {
                  converted = this.dataToClass(arg);
                  if (converted) {
                    result.push(converted);
                  }
                }
              }
              return result;
            } else {
              return [];
            }
          }).call(this);
          // Create SuperCall with Super as variable and filtered args
          return new nodes.SuperCall(variable, args, node.soak);
        // ============================================================
        // Arrays and Objects
        // ============================================================
        case 'Arr':
          objects = (function() {
            var len4, len5, len6, m, o, q, ref6, ref7;
            if (node.objects) {
              result = [];
              ref6 = node.objects;
              for (m = 0, len4 = ref6.length; m < len4; m++) {
                obj = ref6[m];
                if (Array.isArray(obj)) {
// Process all elements in nested arrays (happens with elisions)
                  for (o = 0, len5 = obj.length; o < len5; o++) {
                    item = obj[o];
                    if ((item != null ? item.type : void 0) === 'Elision') {
                      // Handle elisions - create actual hole/empty slot
                      result.push(new nodes.Elision());
                    } else {
                      converted = this.dataToClass(item);
                      if (converted) {
                        result.push(converted);
                      }
                    }
                  }
                } else if ((obj != null ? obj.type : void 0) === 'Elision') {
                  // Handle elisions - create actual hole/empty slot
                  result.push(new nodes.Elision());
                } else if (typeof obj === 'object' && Object.keys(obj).length > 0) {
                  converted = this.dataToClass(obj);
                  if (converted) {
                    result.push(converted);
                  }
                }
              }
              // Handle trailing elisions stored in separate elisions property
              // Only process elisions that have type: 'Elision', not empty objects
              if (node.elisions) {
                ref7 = node.elisions;
                for (q = 0, len6 = ref7.length; q < len6; q++) {
                  elision = ref7[q];
                  if ((elision != null ? elision.type : void 0) === 'Elision') {
                    result.push(new nodes.Elision());
                  }
                }
              }
              return result;
            } else if (node.value) {
              if (Array.isArray(node.value)) {
                return node.value.filter(function(v) {
                  return !(typeof v === 'object' && Object.keys(v).length === 0);
                }).map((v) => {
                  return this.dataToClass(v);
                });
              } else {
                return [this.dataToClass(node.value)];
              }
            } else {
              return [];
            }
          }).call(this);
          return new nodes.Arr(objects);
        case 'Obj':
          properties = (function() {
            var len4, len5, m, o, ref6;
            if (node.properties) {
              result = [];
              ref6 = node.properties;
              for (m = 0, len4 = ref6.length; m < len4; m++) {
                prop = ref6[m];
                if (Array.isArray(prop)) {
                  for (o = 0, len5 = prop.length; o < len5; o++) {
                    item = prop[o];
                    converted = this.dataToClass(item);
                    if ((converted != null) && converted instanceof nodes.Base) {
                      result.push(converted);
                    }
                  }
                } else if (prop != null) {
                  converted = this.dataToClass(prop);
                  if ((converted != null) && converted instanceof nodes.Base) {
                    result.push(converted);
                  }
                }
              }
              return result;
            } else {
              return [];
            }
          }).call(this);
          generated = node.generated;
          return new nodes.Obj(properties, generated);
        case 'Range':
          from = node.from ? this.dataToClass(node.from) : null;
          to = node.to ? this.dataToClass(node.to) : null;
          tag = node.exclusive ? 'exclusive' : 'inclusive';
          return new nodes.Range(from, to, tag);
        case 'Slice':
          // Create a Slice with its range
          if (node.range) {
            range = this.dataToClass(node.range);
            return new nodes.Slice(range);
          } else {
            console.warn("Slice without range:", node);
            return null;
          }
          break;
        case 'Splat':
          name = this.dataToClass(node.name || node.body || node.value);
          return new nodes.Splat(name);
        case 'Expansion':
          return new nodes.Expansion();
        case 'Elision':
          // Support array elisions - create actual hole/empty slot
          return new nodes.Elision();
        // ============================================================
        // Control Flow
        // ============================================================
        case 'If':
        case 'if':
        case 'unless':
          condition = this.dataToClass(node.condition);
          body = Array.isArray(node.body) ? (bodyNodes = node.body.map((n) => {
            return this.dataToClass(n);
          }), new nodes.Block(bodyNodes)) : this.dataToClass(node.body);
          options = {};
          if (node.type) {
            options.type = node.type;
          }
          if (node.postfix) {
            options.postfix = node.postfix;
          }
          ifNode = new nodes.If(condition, body, options);
          if (node.elseBody) {
            elseBody = Array.isArray(node.elseBody) ? (bodyNodes = node.elseBody.map((n) => {
              return this.dataToClass(n);
            }), new nodes.Block(bodyNodes)) : this.dataToClass(node.elseBody);
            ifNode.elseBody = elseBody;
            ifNode.isChain = elseBody instanceof nodes.If;
          }
          return ifNode;
        case 'While':
          condition = this.dataToClass(node.condition);
          if (node.guard) {
            guard = this.dataToClass(node.guard);
          }
          body = Array.isArray(node.body) ? new nodes.Block(this.dataToClass(node.body)) : this.dataToClass(node.body);
          return new nodes.While(condition, guard).addBody(body);
        case 'For':
          // Convert body
          body = Array.isArray(node.body) ? (bodyNodes = node.body.map((n) => {
            converted = this.dataToClass(n);
            if (converted) {
              if (converted.locationData == null) {
                converted.locationData = this.defaultLocationData();
              }
            }
            return converted;
          }), new nodes.Block(bodyNodes)) : node.body ? this.dataToClass(node.body) : new nodes.Block([]);
          // Ensure locationData
          if (body.locationData == null) {
            body.locationData = this.defaultLocationData();
          }
          if (body.expressions) {
            ref6 = body.expressions;
            for (m = 0, len4 = ref6.length; m < len4; m++) {
              expr = ref6[m];
              if (expr.locationData == null) {
                expr.locationData = this.defaultLocationData();
              }
            }
          }
          // Build source object
          sourceObj = {};
          if (node.source) {
            sourceObj.source = this.dataToClass(node.source);
          }
          if (node.guard) {
            sourceObj.guard = this.dataToClass(node.guard);
          }
          if (node.step) {
            sourceObj.step = this.dataToClass(node.step);
          }
          if (node.name) {
            sourceObj.name = this.dataToClass(node.name);
          }
          if (node.index) {
            sourceObj.index = this.dataToClass(node.index);
          }
          if (node.object) {
            sourceObj.object = node.object;
          }
          if (node.from) {
            sourceObj.from = node.from;
          }
          if (node.own) {
            sourceObj.own = node.own;
          }
          if (node.await) {
            sourceObj.await = node.await;
          }
          if (node.awaitTag) {
            sourceObj.awaitTag = this.dataToClass(node.awaitTag);
          }
          if (node.ownTag) {
            sourceObj.ownTag = this.dataToClass(node.ownTag);
          }
          // FIX: Loop variable conflicts
          // The For node constructor will handle variable allocation
          // We just need to pass the correct source configuration
          return new nodes.For(body, sourceObj);
        case 'Switch':
          subject = this.dataToClass(node.subject);
          cases = node.cases ? node.cases.map((c) => {
            return this.dataToClass(c);
          }) : [];
          otherwise = node.otherwise ? (otherwiseNode = this.dataToClass(node.otherwise), otherwiseNode instanceof nodes.Block ? otherwiseNode : Array.isArray(otherwiseNode) ? new nodes.Block(otherwiseNode) : otherwiseNode != null ? new nodes.Block([otherwiseNode]) : null) : null;
          return new nodes.Switch(subject, cases, otherwise);
        case 'SwitchWhen':
          conditions = this.dataToClass(node.conditions);
          body = node.body ? (bodyNode = this.dataToClass(node.body), bodyNode instanceof nodes.Block ? bodyNode : Array.isArray(bodyNode) ? new nodes.Block(bodyNode) : bodyNode != null ? new nodes.Block([bodyNode]) : new nodes.Block([])) : new nodes.Block([]);
          return new nodes.SwitchWhen(conditions, body);
        case 'Try':
          attempt = node.attempt ? (attemptNode = this.dataToClass(node.attempt), attemptNode instanceof nodes.Block ? attemptNode : Array.isArray(attemptNode) ? new nodes.Block(attemptNode) : attemptNode != null ? new nodes.Block([attemptNode]) : new nodes.Block([])) : new nodes.Block([]);
          if (node.catch) {
            catch_ = this.dataToClass(node.catch);
          }
          ensure = node.ensure ? (ensureNode = this.dataToClass(node.ensure), ensureNode instanceof nodes.Block ? ensureNode : Array.isArray(ensureNode) ? new nodes.Block(ensureNode) : ensureNode != null ? new nodes.Block([ensureNode]) : null) : null;
          return new nodes.Try(attempt, catch_, ensure);
        case 'Catch':
          recovery = node.recovery || node.body ? (recoveryNode = this.dataToClass(node.recovery || node.body), recoveryNode instanceof nodes.Block ? recoveryNode : Array.isArray(recoveryNode) ? new nodes.Block(recoveryNode) : recoveryNode != null ? new nodes.Block([recoveryNode]) : new nodes.Block([])) : new nodes.Block([]);
          if (node.variable) {
            variable = this.dataToClass(node.variable);
          }
          return new nodes.Catch(recovery, variable);
        case 'Throw':
          expression = this.dataToClass(node.expression);
          return new nodes.Throw(expression);
        case 'Return':
          if (node.expression) {
            expression = this.dataToClass(node.expression);
          }
          return new nodes.Return(expression);
        case 'YieldReturn':
          if (node.expression) {
            expression = this.dataToClass(node.expression);
          }
          if (node.returnKeyword) {
            returnKeyword = this.dataToClass(node.returnKeyword);
          }
          return new nodes.YieldReturn(expression, {returnKeyword});
        case 'AwaitReturn':
          if (node.expression) {
            expression = this.dataToClass(node.expression);
          }
          if (node.returnKeyword) {
            returnKeyword = this.dataToClass(node.returnKeyword);
          }
          return new nodes.AwaitReturn(expression, {returnKeyword});
        // ============================================================
        // Classes
        // ============================================================
        case 'Class':
          if (node.variable) {
            variable = this.dataToClass(node.variable);
          }
          if (node.parent) {
            parent = this.dataToClass(node.parent);
          }
          body = (function() {
            var len5, len6, len7, o, q, r, ref7, ref8, ref9;
            if (Array.isArray(node.body)) {
              bodyNodes = [];
              ref7 = node.body;
              for (o = 0, len5 = ref7.length; o < len5; o++) {
                item = ref7[o];
                if (item.type === 'Value' && ((ref8 = item.val) != null ? ref8.type : void 0) === 'Obj') {
                  // Extract methods from object literal
                  objNode = item.val;
                  if (objNode.properties) {
                    ref9 = objNode.properties;
                    for (q = 0, len6 = ref9.length; q < len6; q++) {
                      prop = ref9[q];
                      if (Array.isArray(prop)) {
                        for (r = 0, len7 = prop.length; r < len7; r++) {
                          p = prop[r];
                          converted = this.dataToClass(p);
                          if (converted) {
                            bodyNodes.push(converted);
                          }
                        }
                      } else if (prop) {
                        converted = this.dataToClass(prop);
                        if (converted) {
                          bodyNodes.push(converted);
                        }
                      }
                    }
                  }
                } else {
                  converted = this.dataToClass(item);
                  if (converted) {
                    bodyNodes.push(converted);
                  }
                }
              }
              return new nodes.Block(bodyNodes);
            } else if (node.body) {
              return this.dataToClass(node.body);
            } else {
              return new nodes.Block([]);
            }
          }).call(this);
          return new nodes.Class(variable, parent, body);
        // ============================================================
        // Parentheticals
        // ============================================================
        case 'Parens':
          body = Array.isArray(node.body) ? (bodyNodes = node.body.map((n) => {
            return this.dataToClass(n);
          }), new nodes.Block(bodyNodes)) : this.dataToClass(node.body);
          return new nodes.Parens(body);
        // ============================================================
        // String Interpolation
        // ============================================================
        case 'StringWithInterpolations':
          body = node.body ? (parts = node.body.map((part) => {
            return this.dataToClass(part);
          }), new nodes.Block(parts)) : new nodes.Block([]);
          quote = node.quote || '"';
          return new nodes.StringWithInterpolations(body, {quote});
        case 'Interpolation':
          expression = Array.isArray(node.expression) ? node.expression.length === 1 ? this.dataToClass(node.expression[0]) : (expressionNodes = node.expression.map((n) => {
            return this.dataToClass(n);
          }), new nodes.Block(expressionNodes)) : node.expression ? this.dataToClass(node.expression) : new nodes.Block([]);
          return new nodes.Interpolation(expression);
        // ============================================================
        // Import/Export
        // ============================================================
        case 'ImportDeclaration':
          if (node.clause) {
            clause = this.dataToClass(node.clause);
          }
          source = this.dataToClass(node.source);
          if (node.assertions) {
            assertions = this.dataToClass(node.assertions);
          }
          return new nodes.ImportDeclaration(clause, source, assertions);
        case 'ImportClause':
          if (node.defaultBinding) {
            defaultBinding = this.dataToClass(node.defaultBinding);
          }
          if (node.namedImports) {
            namedImports = this.dataToClass(node.namedImports);
          }
          return new nodes.ImportClause(defaultBinding, namedImports);
        case 'ExportDeclaration':
          return new nodes.ExportDeclaration(this.dataToClass(node.clause));
        // ============================================================
        // Meta nodes
        // ============================================================
        case 'FuncGlyph':
          // This is metadata, not a real node
          return node;
        case 'Source':
          // Source is a wrapper node - unwrap it
          return this.dataToClass(node.value);
        case 'ComputedPropertyName':
          // ComputedPropertyName is just a marker - return a flag
          // The actual computed property value should be in the parent context
          return new nodes.Literal('computed');
        case 'MetaProperty':
          if (node.meta) {
            // MetaProperty like new.target
            meta = this.dataToClass(node.meta);
          }
          if (node.property) {
            property = this.dataToClass(node.property);
          }
          // For now, pass through as literal
          return new nodes.PassthroughLiteral(`${((ref7 = node.meta) != null ? ref7.value : void 0) || 'new'}.${((ref8 = node.property) != null ? ref8.value : void 0) || 'target'}`);
        case 'RegexWithInterpolations':
          // Regex with interpolations - convert to regular regex for now
          // This would need more complex handling for full support
          return new nodes.RegexLiteral(node.value || '//', node.flags || '');
        case 'DynamicImportCall':
          // Dynamic import() call - extends Call
          variable = new nodes.IdentifierLiteral('import');
          args = node.args ? this.filterNodes(node.args) : [];
          // DynamicImportCall extends Call, so pass variable and args
          return new nodes.DynamicImportCall(variable, args);
        case 'TaggedTemplateCall':
          // Tagged template literals - expects single arg (the template)
          variable = this.dataToClass(node.variable);
          // CS3 parser provides template property instead of args
          arg = node.template ? this.dataToClass(node.template) : ((ref9 = node.args) != null ? ref9.length : void 0) > 0 ? this.dataToClass(node.args[0]) : new nodes.StringLiteral('');
          return new nodes.TaggedTemplateCall(variable, arg, node.soak);
        default:
          // ============================================================
          // Default fallback
          // ============================================================
          console.warn(`Unknown CS3 node type: ${node.type}`);
          return new nodes.PassthroughLiteral(`/* Unknown node type: ${node.type} */`);
      }
    }

  };

  module.exports = ES5Backend;

}).call(this);
