// Generated by CoffeeScript 2.7.0
(function() {
  //!/usr/bin/env coffee

  // ==============================================================================
  // CS3 ES5 Backend - Clean Room Implementation
  // ==============================================================================

  // Converts CS3 data-oriented AST nodes to CoffeeScript's class-based AST nodes
  // Then uses the existing CoffeeScript compiler to generate JavaScript

  // Key fixes in this version:
  // 1. Loop variable conflict prevention
  // 2. Proper super call handling
  // 3. Array elision support
  // ==============================================================================
  var ES5Backend, nodes;

  nodes = require('../../lib/coffeescript/nodes');

  ES5Backend = class ES5Backend {
    constructor(options1 = {}) {
      var ref, ref1, ref2, ref3;
      this.options = options1;
      this.compileOptions = {
        bare: (ref = this.options.bare) != null ? ref : true,
        header: (ref1 = this.options.header) != null ? ref1 : false,
        sourceMap: (ref2 = this.options.sourceMap) != null ? ref2 : false,
        inlineMap: (ref3 = this.options.inlineMap) != null ? ref3 : false
      };
    }

    // Main entry point - convert CS3 data node to JavaScript
    generate(dataNode) {
      var classNode;
      classNode = this.dataToClass(dataNode);
      return classNode.compile(this.compileOptions);
    }

    // Helper to create default locationData
    defaultLocationData() {
      return {
        first_line: 0,
        first_column: 0,
        last_line: 0,
        last_column: 0,
        last_line_exclusive: 0,
        last_column_exclusive: 0,
        range: [0, 0]
      };
    }

    // Helper to ensure value is a proper node
    ensureNode(value) {
      if (value == null) {
        return null;
      }
      if (value.compileToFragments || value instanceof nodes.Base) {
        return value;
      }
      // Wrap primitives in Literal
      return new nodes.Literal(String(value));
    }

    // Helper to filter and ensure all items are nodes
    filterNodes(array) {
      var i, item, len, node, result;
      if (array == null) {
        return [];
      }
      result = [];
      for (i = 0, len = array.length; i < len; i++) {
        item = array[i];
        node = this.ensureNode(this.dataToClass(item));
        if (node != null) {
          result.push(node);
        }
      }
      return result;
    }

    // Convert CS3 data nodes to CoffeeScript class nodes
    dataToClass(node) {
      var accessNode, accessor, args, assertions, attempt, attemptNode, base, body, bodyNode, bodyNodes, cases, catch_, clause, condition, conditions, context, converted, defaultBinding, elseBody, ensure, ensureNode, expr, expression, expressionNodes, expressions, first, flip, from, funcGlyph, generated, guard, i, ifNode, index, indexNode, item, len, name, namedImports, obj, objNode, objects, op, options, otherwise, otherwiseNode, p, params, parent, parts, prop, properties, quote, recovery, recoveryNode, ref, ref1, ref2, result, second, soak, source, sourceObj, splat, stringNode, subject, superCall, tag, to, value, variable;
      if (node == null) {
        return null;
      }
      if ((ref = typeof node) === 'string' || ref === 'number' || ref === 'boolean') {
        // Handle primitives
        return node;
      }
      // Handle arrays
      if (Array.isArray(node)) {
        return node.map((item) => {
          return this.dataToClass(item);
        });
      }
      if (!(node != null ? node.type : void 0)) {
        // Must be an object with a type
        return null;
      }
      switch (node.type) {
        // ============================================================
        // Root and Structural Nodes
        // ============================================================
        case 'Root':
          bodyNodes = Array.isArray(node.body) ? this.filterNodes(node.body) : node.body ? (converted = this.dataToClass(node.body), converted != null ? [converted] : []) : [];
          return new nodes.Root(new nodes.Block(bodyNodes));
        case 'Block':
          expressions = node.expressions ? (converted = this.dataToClass(node.expressions), Array.isArray(converted) ? converted.filter(function(item) {
            return item != null;
          }) : converted != null ? [converted] : []) : node.body ? (converted = this.dataToClass(node.body), Array.isArray(converted) ? converted.filter(function(item) {
            return item != null;
          }) : converted != null ? [converted] : []) : [];
          return new nodes.Block(expressions);
        // ============================================================
        // Literals
        // ============================================================
        case 'NumberLiteral':
          return new nodes.NumberLiteral(node.value, node.parsedValue);
        case 'StringLiteral':
          quote = node.quote || '"';
          value = node.value || '';
          stringNode = new nodes.StringLiteral(value, {quote});
          // Critical: Must have locationData and originalValue
          stringNode.locationData = node.locationData || this.defaultLocationData();
          stringNode.originalValue = value;
          return stringNode;
        case 'Literal':
          return new nodes.Literal(node.value);
        case 'BooleanLiteral':
          return new nodes.BooleanLiteral(node.value);
        case 'NullLiteral':
          return new nodes.NullLiteral();
        case 'UndefinedLiteral':
          return new nodes.UndefinedLiteral();
        case 'InfinityLiteral':
          return new nodes.InfinityLiteral(node.value);
        case 'NaNLiteral':
          return new nodes.NaNLiteral();
        case 'IdentifierLiteral':
          return new nodes.IdentifierLiteral(node.value);
        case 'PropertyName':
          return new nodes.PropertyName(node.value);
        case 'StatementLiteral':
          return new nodes.StatementLiteral(node.value);
        case 'ThisLiteral':
          return new nodes.ThisLiteral(node.value || 'this');
        case 'RegexLiteral':
          return new nodes.RegexLiteral(node.value, {
            delimiter: node.delimiter,
            heregexCommentTokens: node.heregexCommentTokens
          });
        case 'PassthroughLiteral':
          return new nodes.PassthroughLiteral(node.value, {
            here: node.here,
            generated: node.generated
          });
        // ============================================================
        // Values and Properties
        // ============================================================
        case 'Value':
          base = this.dataToClass(node.val || node.base || node.value);
          properties = node.properties ? node.properties.map((prop) => {
            return this.dataToClass(prop);
          }) : [];
          return new nodes.Value(base, properties);
        case 'Access':
          name = this.dataToClass(node.name);
          accessNode = new nodes.Access(name);
          if (node.soak) {
            accessNode.soak = node.soak;
          }
          if (node.shorthand) {
            accessNode.shorthand = node.shorthand;
          }
          return accessNode;
        case 'Index':
          index = this.dataToClass(node.object || node.name);
          indexNode = new nodes.Index(index);
          if (node.soak) {
            indexNode.soak = node.soak;
          }
          return indexNode;
        // ============================================================
        // Assignment
        // ============================================================
        case 'Assign':
          // Handle object property assignments
          if (node.context === 'object' && node.expression) {
            variable = this.dataToClass(node.value);
            value = this.dataToClass(node.expression);
          } else {
            variable = this.dataToClass(node.variable);
            value = this.dataToClass(node.value);
          }
          if (!((variable != null) && (value != null))) {
            return null;
          }
          context = node.context;
          options = {};
          if (node.param) {
            options.param = node.param;
          }
          if (node.subpattern) {
            options.subpattern = node.subpattern;
          }
          if (node.operatorToken) {
            if (typeof node.operatorToken === 'object' && node.operatorToken.type) {
              options.operatorToken = {
                value: node.operatorToken.value,
                locationData: node.operatorToken.locationData
              };
            } else {
              options.operatorToken = this.dataToClass(node.operatorToken);
            }
          }
          if (node.moduleDeclaration) {
            options.moduleDeclaration = node.moduleDeclaration;
          }
          return new nodes.Assign(variable, value, context, options);
        // ============================================================
        // Operations
        // ============================================================
        case 'Op':
          if (node.args) {
            [op, first, second, flip] = node.args;
            if (typeof op === 'object') {
              op = op.toString();
            }
            first = this.dataToClass(first);
            if (second) {
              second = this.dataToClass(second);
            }
            // Critical: Pass invertOperator and originalOperator
            options = {};
            if (node.invertOperator) {
              options.invertOperator = node.invertOperator;
            }
            if (node.originalOperator) {
              options.originalOperator = node.originalOperator;
            }
            return new nodes.Op(op, first, second, flip, options);
          } else {
            op = node.operator || node.op;
            first = this.dataToClass(node.first);
            if (node.second) {
              second = this.dataToClass(node.second);
            }
            return new nodes.Op(op, first, second, node.flip);
          }
          break;
        case 'Existence':
          expression = this.dataToClass(node.expression);
          return new nodes.Existence(expression);
        // ============================================================
        // Functions and Calls
        // ============================================================
        case 'Code':
          params = node.params ? this.filterNodes(node.params) : [];
          bodyNodes = Array.isArray(node.body) ? this.filterNodes(node.body) : node.body ? (converted = this.dataToClass(node.body), converted != null ? [converted] : []) : [];
          body = new nodes.Block(bodyNodes);
          funcGlyph = ((ref1 = node.funcGlyph) != null ? ref1.glyph : void 0) || '->';
          tag = funcGlyph === '=>' ? 'boundfunc' : null;
          return new nodes.Code(params, body, tag);
        case 'Param':
          name = this.dataToClass(node.name);
          if (node.value) {
            value = this.dataToClass(node.value);
          }
          splat = node.splat;
          return new nodes.Param(name, value, splat);
        case 'Call':
          variable = this.dataToClass(node.variable);
          args = node.args ? this.filterNodes(node.args) : [];
          soak = node.soak;
          return new nodes.Call(variable, args, soak);
        case 'Super':
          if (node.accessor) {
            accessor = this.dataToClass(node.accessor);
          }
          return new nodes.Super(accessor);
        case 'SuperCall':
          // FIX: Ensure proper super call handling
          args = node.args ? this.filterNodes(node.args) : [];
          // Create the super call with filtered arguments
          superCall = new nodes.SuperCall(args);
          // If there's a variable or token, handle it
          if (node.variable) {
            variable = this.dataToClass(node.variable);
            if (variable) {
              superCall.variable = variable;
            }
          }
          return superCall;
        // ============================================================
        // Arrays and Objects
        // ============================================================
        case 'Arr':
          objects = (function() {
            var i, len, ref2;
            if (node.objects) {
              result = [];
              ref2 = node.objects;
              for (i = 0, len = ref2.length; i < len; i++) {
                obj = ref2[i];
                if (Array.isArray(obj)) {
                  if (obj.length === 1) {
                    converted = this.dataToClass(obj[0]);
                    if (converted) {
                      result.push(converted);
                    }
                  }
                } else if ((obj != null ? obj.type : void 0) === 'Elision') {
                  // Handle elisions properly
                  result.push(this.dataToClass(obj));
                } else if (typeof obj === 'object' && Object.keys(obj).length > 0) {
                  converted = this.dataToClass(obj);
                  if (converted) {
                    result.push(converted);
                  }
                }
              }
              return result;
            } else if (node.value) {
              if (Array.isArray(node.value)) {
                return node.value.filter(function(v) {
                  return !(typeof v === 'object' && Object.keys(v).length === 0);
                }).map((v) => {
                  return this.dataToClass(v);
                });
              } else {
                return [this.dataToClass(node.value)];
              }
            } else {
              return [];
            }
          }).call(this);
          return new nodes.Arr(objects);
        case 'Obj':
          properties = (function() {
            var i, j, len, len1, ref2;
            if (node.properties) {
              result = [];
              ref2 = node.properties;
              for (i = 0, len = ref2.length; i < len; i++) {
                prop = ref2[i];
                if (Array.isArray(prop)) {
                  for (j = 0, len1 = prop.length; j < len1; j++) {
                    item = prop[j];
                    converted = this.dataToClass(item);
                    if ((converted != null) && converted instanceof nodes.Base) {
                      result.push(converted);
                    }
                  }
                } else if (prop != null) {
                  converted = this.dataToClass(prop);
                  if ((converted != null) && converted instanceof nodes.Base) {
                    result.push(converted);
                  }
                }
              }
              return result;
            } else {
              return [];
            }
          }).call(this);
          generated = node.generated;
          return new nodes.Obj(properties, generated);
        case 'Range':
          from = this.dataToClass(node.from);
          to = this.dataToClass(node.to);
          tag = node.exclusive ? 'exclusive' : 'inclusive';
          return new nodes.Range(from, to, tag);
        case 'Slice':
          // Unwrap the range
          return this.dataToClass(node.range);
        case 'Splat':
          name = this.dataToClass(node.name || node.body);
          return new nodes.Splat(name);
        case 'Expansion':
          return new nodes.Expansion();
        case 'Elision':
          // FIX: Support array elisions - create undefined literal
          return new nodes.UndefinedLiteral();
        // ============================================================
        // Control Flow
        // ============================================================
        case 'If':
        case 'if':
        case 'unless':
          condition = this.dataToClass(node.condition);
          body = Array.isArray(node.body) ? (bodyNodes = node.body.map((n) => {
            return this.dataToClass(n);
          }), new nodes.Block(bodyNodes)) : this.dataToClass(node.body);
          options = {};
          if (node.type) {
            options.type = node.type;
          }
          if (node.postfix) {
            options.postfix = node.postfix;
          }
          ifNode = new nodes.If(condition, body, options);
          if (node.elseBody) {
            elseBody = Array.isArray(node.elseBody) ? (bodyNodes = node.elseBody.map((n) => {
              return this.dataToClass(n);
            }), new nodes.Block(bodyNodes)) : this.dataToClass(node.elseBody);
            ifNode.elseBody = elseBody;
            ifNode.isChain = elseBody instanceof nodes.If;
          }
          return ifNode;
        case 'While':
          condition = this.dataToClass(node.condition);
          if (node.guard) {
            guard = this.dataToClass(node.guard);
          }
          body = Array.isArray(node.body) ? new nodes.Block(this.dataToClass(node.body)) : this.dataToClass(node.body);
          return new nodes.While(condition, guard).addBody(body);
        case 'For':
          // Convert body
          body = Array.isArray(node.body) ? (bodyNodes = node.body.map((n) => {
            converted = this.dataToClass(n);
            if (converted) {
              if (converted.locationData == null) {
                converted.locationData = this.defaultLocationData();
              }
            }
            return converted;
          }), new nodes.Block(bodyNodes)) : node.body ? this.dataToClass(node.body) : new nodes.Block([]);
          // Ensure locationData
          if (body.locationData == null) {
            body.locationData = this.defaultLocationData();
          }
          if (body.expressions) {
            ref2 = body.expressions;
            for (i = 0, len = ref2.length; i < len; i++) {
              expr = ref2[i];
              if (expr.locationData == null) {
                expr.locationData = this.defaultLocationData();
              }
            }
          }
          // Build source object
          sourceObj = {};
          if (node.source) {
            sourceObj.source = this.dataToClass(node.source);
          }
          if (node.guard) {
            sourceObj.guard = this.dataToClass(node.guard);
          }
          if (node.step) {
            sourceObj.step = this.dataToClass(node.step);
          }
          if (node.name) {
            sourceObj.name = this.dataToClass(node.name);
          }
          if (node.index) {
            sourceObj.index = this.dataToClass(node.index);
          }
          if (node.object) {
            sourceObj.object = node.object;
          }
          if (node.from) {
            sourceObj.from = node.from;
          }
          if (node.own) {
            sourceObj.own = node.own;
          }
          if (node.await) {
            sourceObj.await = node.await;
          }
          if (node.awaitTag) {
            sourceObj.awaitTag = this.dataToClass(node.awaitTag);
          }
          if (node.ownTag) {
            sourceObj.ownTag = this.dataToClass(node.ownTag);
          }
          // FIX: Loop variable conflicts
          // The For node constructor will handle variable allocation
          // We just need to pass the correct source configuration
          return new nodes.For(body, sourceObj);
        case 'Switch':
          subject = this.dataToClass(node.subject);
          cases = node.cases ? node.cases.map((c) => {
            return this.dataToClass(c);
          }) : [];
          otherwise = node.otherwise ? (otherwiseNode = this.dataToClass(node.otherwise), otherwiseNode instanceof nodes.Block ? otherwiseNode : Array.isArray(otherwiseNode) ? new nodes.Block(otherwiseNode) : otherwiseNode != null ? new nodes.Block([otherwiseNode]) : null) : null;
          return new nodes.Switch(subject, cases, otherwise);
        case 'SwitchWhen':
          conditions = this.dataToClass(node.conditions);
          body = node.body ? (bodyNode = this.dataToClass(node.body), bodyNode instanceof nodes.Block ? bodyNode : Array.isArray(bodyNode) ? new nodes.Block(bodyNode) : bodyNode != null ? new nodes.Block([bodyNode]) : new nodes.Block([])) : new nodes.Block([]);
          return new nodes.SwitchWhen(conditions, body);
        case 'Try':
          attempt = node.attempt ? (attemptNode = this.dataToClass(node.attempt), attemptNode instanceof nodes.Block ? attemptNode : Array.isArray(attemptNode) ? new nodes.Block(attemptNode) : attemptNode != null ? new nodes.Block([attemptNode]) : new nodes.Block([])) : new nodes.Block([]);
          if (node.catch) {
            catch_ = this.dataToClass(node.catch);
          }
          ensure = node.ensure ? (ensureNode = this.dataToClass(node.ensure), ensureNode instanceof nodes.Block ? ensureNode : Array.isArray(ensureNode) ? new nodes.Block(ensureNode) : ensureNode != null ? new nodes.Block([ensureNode]) : null) : null;
          return new nodes.Try(attempt, catch_, ensure);
        case 'Catch':
          recovery = node.recovery || node.body ? (recoveryNode = this.dataToClass(node.recovery || node.body), recoveryNode instanceof nodes.Block ? recoveryNode : Array.isArray(recoveryNode) ? new nodes.Block(recoveryNode) : recoveryNode != null ? new nodes.Block([recoveryNode]) : new nodes.Block([])) : new nodes.Block([]);
          if (node.variable) {
            variable = this.dataToClass(node.variable);
          }
          return new nodes.Catch(recovery, variable);
        case 'Throw':
          expression = this.dataToClass(node.expression);
          return new nodes.Throw(expression);
        case 'Return':
          if (node.expression) {
            expression = this.dataToClass(node.expression);
          }
          return new nodes.Return(expression);
        case 'YieldReturn':
          if (node.expression) {
            expression = this.dataToClass(node.expression);
          }
          return new nodes.YieldReturn(expression);
        case 'AwaitReturn':
          if (node.expression) {
            expression = this.dataToClass(node.expression);
          }
          return new nodes.AwaitReturn(expression);
        // ============================================================
        // Classes
        // ============================================================
        case 'Class':
          if (node.variable) {
            variable = this.dataToClass(node.variable);
          }
          if (node.parent) {
            parent = this.dataToClass(node.parent);
          }
          body = (function() {
            var j, k, l, len1, len2, len3, ref3, ref4, ref5;
            if (Array.isArray(node.body)) {
              bodyNodes = [];
              ref3 = node.body;
              for (j = 0, len1 = ref3.length; j < len1; j++) {
                item = ref3[j];
                if (item.type === 'Value' && ((ref4 = item.val) != null ? ref4.type : void 0) === 'Obj') {
                  // Extract methods from object literal
                  objNode = item.val;
                  if (objNode.properties) {
                    ref5 = objNode.properties;
                    for (k = 0, len2 = ref5.length; k < len2; k++) {
                      prop = ref5[k];
                      if (Array.isArray(prop)) {
                        for (l = 0, len3 = prop.length; l < len3; l++) {
                          p = prop[l];
                          converted = this.dataToClass(p);
                          if (converted) {
                            bodyNodes.push(converted);
                          }
                        }
                      } else if (prop) {
                        converted = this.dataToClass(prop);
                        if (converted) {
                          bodyNodes.push(converted);
                        }
                      }
                    }
                  }
                } else {
                  converted = this.dataToClass(item);
                  if (converted) {
                    bodyNodes.push(converted);
                  }
                }
              }
              return new nodes.Block(bodyNodes);
            } else if (node.body) {
              return this.dataToClass(node.body);
            } else {
              return new nodes.Block([]);
            }
          }).call(this);
          return new nodes.Class(variable, parent, body);
        // ============================================================
        // Parentheticals
        // ============================================================
        case 'Parens':
          body = Array.isArray(node.body) ? (bodyNodes = node.body.map((n) => {
            return this.dataToClass(n);
          }), new nodes.Block(bodyNodes)) : this.dataToClass(node.body);
          return new nodes.Parens(body);
        // ============================================================
        // String Interpolation
        // ============================================================
        case 'StringWithInterpolations':
          body = node.body ? (parts = node.body.map((part) => {
            return this.dataToClass(part);
          }), new nodes.Block(parts)) : new nodes.Block([]);
          quote = node.quote || '"';
          return new nodes.StringWithInterpolations(body, {quote});
        case 'Interpolation':
          expression = Array.isArray(node.expression) ? node.expression.length === 1 ? this.dataToClass(node.expression[0]) : (expressionNodes = node.expression.map((n) => {
            return this.dataToClass(n);
          }), new nodes.Block(expressionNodes)) : node.expression ? this.dataToClass(node.expression) : new nodes.Block([]);
          return new nodes.Interpolation(expression);
        // ============================================================
        // Import/Export
        // ============================================================
        case 'ImportDeclaration':
          if (node.clause) {
            clause = this.dataToClass(node.clause);
          }
          source = this.dataToClass(node.source);
          if (node.assertions) {
            assertions = this.dataToClass(node.assertions);
          }
          return new nodes.ImportDeclaration(clause, source, assertions);
        case 'ImportClause':
          if (node.defaultBinding) {
            defaultBinding = this.dataToClass(node.defaultBinding);
          }
          if (node.namedImports) {
            namedImports = this.dataToClass(node.namedImports);
          }
          return new nodes.ImportClause(defaultBinding, namedImports);
        case 'ExportDeclaration':
          return new nodes.ExportDeclaration(this.dataToClass(node.clause));
        // ============================================================
        // Meta nodes
        // ============================================================
        case 'FuncGlyph':
          // This is metadata, not a real node
          return node;
        case 'Source':
          // Source is a wrapper node - unwrap it
          return this.dataToClass(node.value);
        default:
          // ============================================================
          // Default fallback
          // ============================================================
          console.warn(`Unknown CS3 node type: ${node.type}`);
          return new nodes.PassthroughLiteral(`/* Unknown node type: ${node.type} */`);
      }
    }

  };

  module.exports = ES5Backend;

}).call(this);
