// Generated by CoffeeScript 2.7.0
(function() {
  //!/usr/bin/env coffee

  // ==============================================================================
  // CS3 ES5 Backend - Clean Room Implementation
  // ==============================================================================

  // Converts CS3 data-oriented AST nodes to CoffeeScript's class-based AST nodes
  // Then uses the existing CoffeeScript compiler to generate JavaScript

  // Key fixes in this version:
  // 1. Loop variable conflict prevention
  // 2. Proper super call handling
  // 3. Array elision support
  // ==============================================================================
  var ES5Backend, nodes;

  nodes = require('../../coffeescript/nodes');

  ES5Backend = class ES5Backend {
    constructor(options1 = {}, nodes1 = nodes) {
      var ref1, ref2, ref3, ref4;
      this.options = options1;
      this.nodes = nodes1;
      this.variableContext = {}; // Store for $var/$use variables
      // Allow nodes to be passed in or use the require
      nodes = this.nodes;
      this.compileOptions = {
        bare: (ref1 = this.options.bare) != null ? ref1 : true,
        header: (ref2 = this.options.header) != null ? ref2 : false,
        sourceMap: (ref3 = this.options.sourceMap) != null ? ref3 : false,
        inlineMap: (ref4 = this.options.inlineMap) != null ? ref4 : false,
        // Signal to nodes compiler that we're in CS3 pipeline, so it can relax
        // early "this-before-super" checks to let our lowering run.
        cs3: true
      };
      // CRITICAL FIX for #4889: Track unique variable allocation for nested for-loops
      this.loopVarCounter = 0;
      this.usedLoopVars = new Set();
    }

    // Main entry point - convert Solar directive or CoffeeScript node to JavaScript
    generate(node) {
      var classNode, result;
      // If already a CoffeeScript class node (from ReductionFrame), compile directly
      if (node != null ? node.compile : void 0) {
        result = node.compile(this.compileOptions);
        return result || '';
      }
      // Otherwise, convert via legacy dataToClass method
      classNode = this.dataToClass(node);
      if (classNode == null) {
        return '';
      }
      result = classNode.compile(this.compileOptions);
      return result || '';
    }

    // Helper to create default locationData
    defaultLocationData() {
      return {
        first_line: 0,
        first_column: 0,
        last_line: 0,
        last_column: 0,
        last_line_exclusive: 0,
        last_column_exclusive: 0,
        range: [0, 0]
      };
    }

    // CRITICAL FIX for #4889: Generate unique loop variables like CoffeeScript's scope.freeVariable
    getUniqueLoopVar() {
      var letterIndex, letters, num, varName;
      // Generate unique variable names for loop iterators
      // We'll use a pattern that won't conflict with common user variables
      // Start with less common letters: k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z
      // Skip i and j as they're commonly used by users
      letters = ['k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z'];
      letterIndex = this.loopVarCounter % letters.length;
      num = Math.floor(this.loopVarCounter / letters.length);
      varName = `${letters[letterIndex]}${num || ''}`;
      this.loopVarCounter++;
      this.usedLoopVars.add(varName);
      return varName;
    }

    // Helper to strip common indentation from heredoc strings
    stripHeredocIndentation(value, quote) {
      var i, j, k, leadingSpaces, len, line, lines, minIndent, ref1, ref2;
      if (!((quote === '"""' || quote === "'''") && typeof value === 'string')) {
        return value;
      }
      lines = value.split('\n');
      if (lines.length <= 1) {
        return value;
      }
      // Find minimum indentation (excluding empty lines)
      minIndent = 2e308;
      ref1 = lines.slice(1);
      for (j = 0, len = ref1.length; j < len; j++) {
        line = ref1[j];
        if (line.trim().length > 0) {
          leadingSpaces = line.match(/^[ \t]*/)[0].length;
          minIndent = Math.min(minIndent, leadingSpaces);
        }
      }
      // Strip common indentation from all lines except the first
      if (minIndent > 0 && minIndent < 2e308) {
        for (i = k = 1, ref2 = lines.length; (1 <= ref2 ? k < ref2 : k > ref2); i = 1 <= ref2 ? ++k : --k) {
          lines[i] = lines[i].slice(minIndent);
        }
        return lines.join('\n');
      } else {
        return value;
      }
    }

    // Helper to deep flatten arrays recursively
    deepFlatten(arr) {
      var flattened, item, j, k, len, len1, result, sub;
      result = [];
      for (j = 0, len = arr.length; j < len; j++) {
        item = arr[j];
        if (Array.isArray(item)) {
          flattened = this.deepFlatten(item);
          for (k = 0, len1 = flattened.length; k < len1; k++) {
            sub = flattened[k];
            result.push(sub);
          }
        } else {
          result.push(item);
        }
      }
      return result;
    }

    // Helper to ensure value is an array
    toArray(value) {
      if (Array.isArray(value)) {
        return value;
      } else {
        if (value != null) {
          return [value];
        } else {
          return [];
        }
      }
    }

    // Helper to check if value is a node (performance optimization)
    isNode(value) {
      return value instanceof nodes.Base;
    }

    // Helper to convert any value to a proper node
    toNode(value) {
      if (value == null) {
        return null;
      }
      if (this.isNode(value)) {
        return value;
      }
      if (value != null ? value.type : void 0) {
        return this.solarNodeToClass(value);
      }
      return this.ensureNode(value);
    }

    // Helper to convert value to a Block node
    toBlock(value) {
      if (Array.isArray(value)) {
        return new nodes.Block(this.filterNodes(value));
      } else if (value instanceof nodes.Block) {
        return value;
      } else if (value != null) {
        return new nodes.Block([this.ensureNode(value)]);
      } else {
        return new nodes.Block([]);
      }
    }

    // ==============================================================================
    // NODE CREATION METHODS - Extracted from main switch for clarity
    // ==============================================================================
    createLiteral(directive, frame, ruleName) {
      var value;
      value = this.evaluateDirective(directive.value, frame, ruleName);
      return new nodes.Literal(value);
    }

    createIdentifierLiteral(directive, frame, ruleName) {
      var node, value;
      value = this.evaluateDirective(directive.value, frame, ruleName);
      node = new nodes.IdentifierLiteral(value);
      if (node.locationData == null) {
        node.locationData = this.defaultLocationData();
      }
      return node;
    }

    createNumberLiteral(directive, frame, ruleName) {
      var cleanValue, node, parsedValue, value;
      value = this.evaluateDirective(directive.value, frame, ruleName);
      parsedValue = this.evaluateDirective(directive.parsedValue, frame, ruleName);
      // Strip underscores from numeric literals for compatibility
      cleanValue = typeof value === 'string' ? value.replace(/_/g, '') : value;
      node = new nodes.NumberLiteral(cleanValue, parsedValue);
      if (node.locationData == null) {
        node.locationData = this.defaultLocationData();
      }
      return node;
    }

    createBooleanLiteral(directive, frame, ruleName) {
      var value;
      value = this.evaluateDirective(directive.value, frame, ruleName);
      return new nodes.BooleanLiteral(value);
    }

    createNullLiteral() {
      return new nodes.NullLiteral();
    }

    createUndefinedLiteral() {
      return new nodes.UndefinedLiteral();
    }

    createThisLiteral() {
      var node;
      node = new nodes.ThisLiteral();
      if (node.locationData == null) {
        node.locationData = this.defaultLocationData();
      }
      return node;
    }

    createStringLiteral(directive, frame, ruleName) {
      var node, quote, value;
      value = this.evaluateDirective(directive.value, frame, ruleName);
      quote = this.evaluateDirective(directive.quote, frame, ruleName);
      // Strip the surrounding quotes from the value if present
      if (value && typeof value === 'string' && value.length >= 2) {
        if ((value[0] === '"' && value[value.length - 1] === '"') || (value[0] === "'" && value[value.length - 1] === "'")) {
          value = value.slice(1, -1);
        }
      }
      // Handle triple-quoted strings (heredocs)
      value = this.stripHeredocIndentation(value, quote);
      node = new nodes.StringLiteral(value, {quote});
      if (node.locationData == null) {
        node.locationData = this.defaultLocationData();
      }
      return node;
    }

    createArr(directive, frame, ruleName) {
      var arr, objects;
      objects = this.evaluateDirective(directive.objects, frame, ruleName);
      objects = this.filterNodes(this.toArray(objects));
      arr = new nodes.Arr(objects);
      if (arr.locationData == null) {
        arr.locationData = this.defaultLocationData();
      }
      return arr;
    }

    createPropertyName(directive, frame, ruleName) {
      var value;
      value = this.evaluateDirective(directive.value, frame, ruleName);
      return new nodes.PropertyName(value || '');
    }

    createIf(directive, frame, ruleName, defaultType = 'if') {
      var body, bodyNode, condition, elseBody, elseNode, ifNode, opts, postfix, type;
      condition = this.evaluateDirective(directive.condition, frame, ruleName);
      body = this.evaluateDirective(directive.body, frame, ruleName);
      elseBody = this.evaluateDirective(directive.elseBody, frame, ruleName);
      type = this.evaluateDirective(directive.type, frame, ruleName) || defaultType;
      postfix = this.evaluateDirective(directive.postfix, frame, ruleName);
      bodyNode = this.toBlock(body);
      if (bodyNode) {
        if (bodyNode.locationData == null) {
          bodyNode.locationData = this.defaultLocationData();
        }
      }
      elseNode = elseBody ? this.toBlock(elseBody) : null;
      if (elseNode) {
        if (elseNode.locationData == null) {
          elseNode.locationData = this.defaultLocationData();
        }
      }
      opts = {};
      if (type === 'unless') {
        opts.type = type;
      }
      if (postfix) {
        opts.postfix = postfix;
      }
      ifNode = new nodes.If(condition, bodyNode, opts);
      if (ifNode.locationData == null) {
        ifNode.locationData = this.defaultLocationData();
      }
      if (elseNode) {
        ifNode.addElse(elseNode);
      }
      return ifNode;
    }

    createReturn(directive, frame, ruleName) {
      var expression;
      expression = this.evaluateDirective(directive.expression, frame, ruleName);
      return new nodes.Return(expression);
    }

    createYield(directive, frame, ruleName) {
      var expression, from;
      expression = this.evaluateDirective(directive.expression, frame, ruleName);
      from = this.evaluateDirective(directive.from, frame, ruleName);
      return new nodes.Yield(expression, from);
    }

    createSlice(directive, frame, ruleName) {
      var range;
      range = this.evaluateDirective(directive.range, frame, ruleName);
      return new nodes.Slice(range);
    }

    createThrow(directive, frame, ruleName) {
      var expression;
      expression = this.evaluateDirective(directive.expression, frame, ruleName);
      return new nodes.Throw(this.ensureNode(expression) || new nodes.Literal('undefined'));
    }

    createAwait(directive, frame, ruleName) {
      var expression;
      expression = this.evaluateDirective(directive.expression, frame, ruleName);
      return new nodes.Await(expression);
    }

    createYieldFrom(directive, frame, ruleName) {
      var expression;
      expression = this.evaluateDirective(directive.expression, frame, ruleName);
      return new nodes.YieldFrom(expression);
    }

    createExistence(directive, frame, ruleName) {
      var expression;
      expression = this.evaluateDirective(directive.expression, frame, ruleName);
      return new nodes.Existence(expression);
    }

    createSwitch(directive, frame, ruleName) {
      var cases, casesNode, otherwise, subject;
      subject = this.evaluateDirective(directive.subject, frame, ruleName);
      cases = this.evaluateDirective(directive.cases, frame, ruleName);
      otherwise = this.evaluateDirective(directive.otherwise, frame, ruleName);
      casesNode = this.filterNodes((Array.isArray(cases) ? cases : []));
      // Ensure otherwise is a proper block or null
      if (otherwise) {
        if (Array.isArray(otherwise)) {
          otherwise = new nodes.Block(this.filterNodes(otherwise));
        } else if (!(otherwise instanceof nodes.Base)) {
          otherwise = new nodes.Block([this.ensureNode(otherwise)]);
        }
      }
      return new nodes.Switch(subject, casesNode, otherwise);
    }

    createCatch(directive, frame, ruleName) {
      var body, bodyNode, error, errorNode;
      // CS3 uses either 'recovery' or 'body' for the catch block
      body = this.evaluateDirective(directive.recovery, frame, ruleName) || this.evaluateDirective(directive.body, frame, ruleName);
      // CS3 uses 'variable' or 'errorVariable' for the error parameter
      error = this.evaluateDirective(directive.variable, frame, ruleName) || this.evaluateDirective(directive.errorVariable, frame, ruleName);
      // Ensure body is a proper Block
      bodyNode = Array.isArray(body) ? new nodes.Block(this.filterNodes(body)) : body instanceof nodes.Block ? body : body ? new nodes.Block([this.ensureNode(body)]) : new nodes.Block([]);
      // Ensure error parameter is properly converted if present
      errorNode = error ? this.ensureNode(error) : null;
      // Catch constructor expects (recovery, errorVariable) not (errorVariable, recovery)!
      return new nodes.Catch(bodyNode, errorNode);
    }

    createWhile(directive, frame, ruleName) {
      var body, bodyNode, condition, finalBody, guard, invert, isLoop, opts, whileNode;
      condition = this.evaluateDirective(directive.condition, frame, ruleName);
      body = this.evaluateDirective(directive.body, frame, ruleName);
      guard = this.evaluateDirective(directive.guard, frame, ruleName);
      isLoop = this.evaluateDirective(directive.isLoop, frame, ruleName);
      invert = this.evaluateDirective(directive.invert, frame, ruleName);
      // Handle body - convert from Solar node if needed
      bodyNode = (body != null ? body.type : void 0) === 'Body' || (body != null ? body.type : void 0) === 'Block' ? this.solarNodeToClass(body) : this.toBlock(body);
      // While constructor expects (condition, opts)
      opts = {};
      if (guard) {
        opts.guard = guard;
      }
      if (isLoop) {
        opts.isLoop = isLoop;
      }
      if (invert) { // Handle 'until' loops
        opts.invert = invert;
      }
      whileNode = new nodes.While(condition, opts);
      // Set the body - ensure it's never null
      finalBody = bodyNode || new nodes.Block([]);
      whileNode.body = finalBody;
      return whileNode;
    }

    createTry(directive, frame, ruleName) {
      var attempt, attemptNode, catchDirective, ensure, ensureNode, recovery;
      attempt = this.evaluateDirective(directive.attempt, frame, ruleName);
      // CS3 uses 'catch' not 'recovery' for the catch clause
      catchDirective = this.evaluateDirective(directive.catch, frame, ruleName);
      ensure = this.evaluateDirective(directive.ensure, frame, ruleName);
      // Ensure attempt is a proper block
      attemptNode = this.toBlock(attempt);
      // Process the catch clause - it should be a Catch node
      // It might be a directive that needs to be evaluated into a Catch node
      recovery = catchDirective instanceof nodes.Catch ? catchDirective : catchDirective ? catchDirective : null;
      // Ensure ensure is a proper block if present
      ensureNode = ensure ? this.toBlock(ensure) : null;
      // Try expects (attempt, recovery, ensure) where recovery and ensure are optional
      return new nodes.Try(attemptNode, recovery, ensureNode);
    }

    createLoop(directive, frame, ruleName) {
      var body, bodyNode, loopNode;
      body = this.evaluateDirective(directive.body, frame, ruleName);
      // Ensure body is a proper Block
      bodyNode = Array.isArray(body) ? new nodes.Block(this.filterNodes(body)) : body instanceof nodes.Block ? body : body ? new nodes.Block([body]) : new nodes.Block([]);
      // Loop is a While with true condition
      loopNode = new nodes.While(new nodes.BooleanLiteral('true'), {
        isLoop: true
      });
      loopNode.body = bodyNode;
      return loopNode;
    }

    createParens(directive, frame, ruleName) {
      var body, bodyNode;
      body = this.evaluateDirective(directive.body, frame, ruleName);
      // Handle array body (Parens can contain an array with a single expression)
      // Take the first element if it's an array
      bodyNode = Array.isArray(body) && body.length > 0 ? this.toNode(body[0]) || new nodes.Literal('') : this.toNode(body) || new nodes.Literal('');
      return new nodes.Parens(bodyNode);
    }

    createInterpolation(directive, frame, ruleName) {
      var actualExpression, expression, expressionNode;
      expression = this.evaluateDirective(directive.expression, frame, ruleName);
      // Expression might be an array, so extract the first element
      actualExpression = Array.isArray(expression) && expression.length > 0 ? expression[0] : expression;
      expressionNode = this.toNode(actualExpression) || new nodes.Literal('undefined');
      return new nodes.Interpolation(expressionNode);
    }

    createStringWithInterpolations(directive, frame, ruleName) {
      var body, bodyNode, bodyNodes, quote;
      body = this.evaluateDirective(directive.body, frame, ruleName);
      quote = this.evaluateDirective(directive.quote, frame, ruleName);
      // Convert body to proper nodes
      bodyNode = Array.isArray(body) ? (bodyNodes = body.map((b) => {
        return this.toNode(b);
      }), new nodes.Block(this.filterNodes(bodyNodes))) : body instanceof nodes.Block ? body : new nodes.Block([]);
      return new nodes.StringWithInterpolations(bodyNode, {quote});
    }

    createParam(directive, frame, ruleName) {
      var atValue, i, j, len, name, obj, prop, ref1, ref2, splat, value;
      name = this.evaluateDirective(directive.name, frame, ruleName);
      value = this.evaluateDirective(directive.value, frame, ruleName);
      splat = this.evaluateDirective(directive.splat, frame, ruleName);
      if (!name) {
        // Param requires at least a name
        name = new nodes.IdentifierLiteral('param');
      }
      // Check if this is an @ parameter (like @x)
      if (name instanceof nodes.Value && name.base instanceof nodes.ThisLiteral) {
        // This is an @param - mark it with this=true so Param recognizes it
        name.this = true;
        if (name.locationData == null) {
          name.locationData = this.defaultLocationData();
        }
      } else if (name && !name.locationData) {
        // Ensure name has locationData (needed for destructuring)
        name.locationData = this.defaultLocationData();
      }
      // Handle {@x, @y} destructuring - convert CS3 Assigns to CS2-style Values
      if (name instanceof nodes.Obj || (name instanceof nodes.Value && name.base instanceof nodes.Obj)) {
        obj = name instanceof nodes.Obj ? name : name.base;
        obj.generated = false;
        if (obj.properties) {
          ref1 = obj.properties;
          for (i = j = 0, len = ref1.length; j < len; i = ++j) {
            prop = ref1[i];
            if (!(prop instanceof nodes.Assign && ((ref2 = prop.value) != null ? ref2.this : void 0))) {
              continue;
            }
            // Create the CS2-style Value node for @param
            obj.properties[i] = atValue = new nodes.Value(new nodes.ThisLiteral());
            atValue.properties = [new nodes.Access(new nodes.PropertyName(prop.variable.base.value))];
            atValue.this = true;
          }
          obj.objects = obj.properties; // eachName uses 'objects' not 'properties'
        }
      }
      return new nodes.Param(name, value, splat);
    }

    createClass(directive, frame, ruleName) {
      var body, bodyNode, parent, variable;
      variable = this.evaluateDirective(directive.variable, frame, ruleName);
      parent = this.evaluateDirective(directive.parent, frame, ruleName);
      body = this.evaluateDirective(directive.body, frame, ruleName);
      bodyNode = Array.isArray(body) ? new nodes.Block(this.filterNodes(body)) : body;
      return new nodes.Class(variable, parent, bodyNode);
    }

    createBlock(directive, frame, ruleName) {
      var expressions;
      expressions = this.evaluateDirective(directive.expressions, frame, ruleName);
      return new nodes.Block(this.filterNodes((Array.isArray(expressions) ? expressions : [])));
    }

    createBody(directive, frame, ruleName) {
      var expr, expressions, flatExpressions, item, j, k, len, len1;
      expressions = this.evaluateDirective(directive.expressions, frame, ruleName);
      // Flatten nested arrays - expressions often come as [[expr1], [expr2]]
      flatExpressions = [];
      if (Array.isArray(expressions)) {
        for (j = 0, len = expressions.length; j < len; j++) {
          expr = expressions[j];
          if (Array.isArray(expr)) {
            for (k = 0, len1 = expr.length; k < len1; k++) {
              item = expr[k];
              flatExpressions.push(item);
            }
          } else {
            flatExpressions.push(expr);
          }
        }
      } else if (expressions != null) {
        flatExpressions.push(expressions);
      }
      return new nodes.Block(this.filterNodes(flatExpressions));
    }

    createRegexLiteral(directive, frame, ruleName) {
      var delimiter, flags, fullRegex, pattern, value;
      value = this.evaluateDirective(directive.value, frame, ruleName);
      delimiter = this.evaluateDirective(directive.delimiter, frame, ruleName);
      // RegexLiteral expects the full regex string including delimiters
      if (value && typeof value === 'string' && value[0] === '/') {
        return new nodes.RegexLiteral(value, {
          delimiter: delimiter || '/'
        });
      } else {
        // Otherwise try to construct from pattern and flags
        pattern = this.evaluateDirective(directive.pattern, frame, ruleName);
        flags = this.evaluateDirective(directive.flags, frame, ruleName);
        fullRegex = `/${pattern || ''}/${flags || ''}`;
        return new nodes.RegexLiteral(fullRegex, {
          delimiter: delimiter || '/'
        });
      }
    }

    createRange(directive, frame, ruleName) {
      var exclusive, exclusiveVal, from, fromNode, tag, to, toNode;
      from = this.evaluateDirective(directive.from, frame, ruleName);
      to = this.evaluateDirective(directive.to, frame, ruleName);
      // Evaluate the exclusive flag - it can be a directive or a boolean
      exclusiveVal = this.evaluateDirective(directive.exclusive, frame, ruleName);
      exclusive = typeof exclusiveVal === 'boolean' ? exclusiveVal : directive.equals != null ? this.evaluateDirective(directive.equals, frame, ruleName) === 'exclusive' : false;
      // Ensure from and to are proper nodes
      fromNode = this.toNode(from) || this.ensureNode(from);
      toNode = this.toNode(to) || this.ensureNode(to);
      // Pass 'exclusive' as the tag for exclusive ranges
      tag = exclusive ? 'exclusive' : null;
      return new nodes.Range(fromNode, toNode, tag);
    }

    createSwitchWhen(directive, frame, ruleName) {
      var blockNode, body, cond, conditions, conditionsNode, converted, processedConditions;
      conditions = this.evaluateDirective(directive.conditions, frame, ruleName);
      body = this.evaluateDirective(directive.body, frame, ruleName);
      // Process conditions - make sure they are proper nodes
      conditionsNode = (function() {
        var j, len;
        if (Array.isArray(conditions)) {
          processedConditions = [];
          for (j = 0, len = conditions.length; j < len; j++) {
            cond = conditions[j];
            if (cond instanceof nodes.Base) {
              processedConditions.push(cond);
            } else if (cond != null) {
              converted = this.ensureNode(cond);
              if (converted instanceof nodes.Base) {
                processedConditions.push(converted);
              }
            }
          }
          return processedConditions;
        } else if (conditions instanceof nodes.Base) {
          return [conditions];
        } else if (conditions != null) {
          converted = this.ensureNode(conditions);
          if (converted instanceof nodes.Base) {
            return [converted];
          } else {
            return [];
          }
        } else {
          return [];
        }
      }).call(this);
      // SwitchWhen expects 'block' not 'body'
      blockNode = Array.isArray(body) ? new nodes.Block(this.filterNodes(body)) : body ? body instanceof nodes.Block ? body : new nodes.Block([body]) : new nodes.Block([]);
      return new nodes.SwitchWhen(conditionsNode, blockNode);
    }

    createFor(directive, frame, ruleName) {
      var body, bodyNode, forNode, from, guard, incrementVar, index, isAwait, loopVar, name, nameArray, object, originalCompileNode, own, source, sourceObj, step;
      // For loops are complex - they're built incrementally via $ops
      body = this.evaluateDirective(directive.body, frame, ruleName);
      source = this.evaluateDirective(directive.source, frame, ruleName);
      guard = this.evaluateDirective(directive.guard, frame, ruleName);
      name = this.evaluateDirective(directive.name, frame, ruleName);
      index = this.evaluateDirective(directive.index, frame, ruleName);
      step = this.evaluateDirective(directive.step, frame, ruleName);
      own = this.evaluateDirective(directive.own, frame, ruleName);
      object = this.evaluateDirective(directive.object, frame, ruleName);
      from = this.evaluateDirective(directive.from, frame, ruleName);
      isAwait = this.evaluateDirective(directive.await, frame, ruleName);
      // Handle body
      // Body node with expressions - preserve full list and order
      bodyNode = (body != null ? body.expressions : void 0) ? new nodes.Block(this.filterNodes(body.expressions)) : this.toBlock(body);
      // Handle name/index - they often come as arrays
      // Special case: for own k, v of obj - name comes as [k, v]
      // But nodes.For swaps name and index when object is true, so we need to account for that
      if (own && object && Array.isArray(name) && name.length === 2 && (index == null)) {
        // nodes.For will swap these, so set them opposite to what we want
        // We want: name=v, index=k (after the swap)
        // So we set: name=k, index=v (before the swap)
        nameArray = name;
        name = nameArray[0];
        index = nameArray[1];
      } else if (Array.isArray(name)) {
        name = name[0];
      }
      if (Array.isArray(index)) {
        index = index[0];
      }
      // Convert to proper nodes if needed
      if (name != null ? name.type : void 0) {
        name = this.solarNodeToClass(name);
      }
      if (index != null ? index.type : void 0) {
        index = this.solarNodeToClass(index);
      }
      if (source != null ? source.type : void 0) {
        source = this.solarNodeToClass(source);
      }
      // Build source object for For constructor
      sourceObj = {};
      // Ensure source is a proper node
      if (source) {
        sourceObj.source = source instanceof nodes.Base ? source : this.ensureNode(source);
      }
      if (name) {
        sourceObj.name = name instanceof nodes.Base ? name : this.ensureNode(name);
      }
      // Only add index if it's actually defined (not undefined/null)
      // This is important for for-await loops which may not have an index
      // Also check if index is the string "index" which means the variable wasn't found
      // console.error "[For] index value:", index, "typeof:", typeof index, "is null?:", index is null
      if ((index != null) && index !== void 0 && index !== 'index') {
        sourceObj.index = index instanceof nodes.Base ? index : this.ensureNode(index);
      }
      if (guard) {
        sourceObj.guard = guard;
      }
      if (step) {
        sourceObj.step = step;
      }
      if (own) {
        sourceObj.own = own;
      }
      if (object) {
        sourceObj.object = object;
      }
      if (from) {
        sourceObj.from = from;
      }
      if (isAwait) {
        sourceObj.await = isAwait;
      }
      // Create For node - constructor expects (body, source)
      forNode = new nodes.For(bodyNode, sourceObj);
      if (forNode.locationData == null) {
        forNode.locationData = this.defaultLocationData();
      }
      // CRITICAL FIX for nested loop var conflicts (#4889):
      // Pre-allocate unique loop variables and override scope.freeVariable
      loopVar = this.getUniqueLoopVar();
      incrementVar = this.getUniqueLoopVar();
      originalCompileNode = forNode.compileNode;
      forNode.compileNode = (o) => {
        var e, originalFreeVariable, preAllocatedVars, ref1, result, userName, varCounter;
        originalFreeVariable = null;
        if (o != null ? (ref1 = o.scope) != null ? ref1.freeVariable : void 0 : void 0) {
          originalFreeVariable = o.scope.freeVariable;
          varCounter = 0;
          preAllocatedVars = [loopVar, incrementVar];
          // Determine user-declared value variable name to avoid collisions
          userName = null;
          try {
            if ((forNode.name != null) && forNode.name instanceof nodes.IdentifierLiteral) {
              userName = forNode.name.value;
            } else if ((forNode.name != null) && forNode.name instanceof nodes.Value && forNode.name.base instanceof nodes.IdentifierLiteral) {
              userName = forNode.name.base.value;
            }
          } catch (error1) {
            e = error1;
            userName = null;
          }
          o.scope.freeVariable = (name, options = {}) => {
            var result;
            // When nodes.For requests 'i' with single:true, it's asking for an iterator temp
            // ALWAYS return our pre-allocated var for these iterator requests
            if (options.single && name === 'i') {
              if (varCounter < preAllocatedVars.length) {
                result = preAllocatedVars[varCounter++];
                return result;
              } else {
                return this.getUniqueLoopVar();
              }
            } else {
              return originalFreeVariable.call(o.scope, name, options);
            }
          };
        }
        result = originalCompileNode.call(forNode, o);
        if (originalFreeVariable != null) {
          o.scope.freeVariable = originalFreeVariable;
        }
        return result;
      };
      return forNode;
    }

    createCode(directive, frame, ruleName) {
      var body, bodyNode, bodyNodes, bound, codeNode, frameValue, funcGlyph, hasSuper, isCtor, origEachSuper, origFlag, params, paramsNode;
      params = this.evaluateDirective(directive.params, frame, ruleName);
      // For body, check if it's a position reference to an already-processed array or Block
      // This preserves modifications made by operations like addElse
      if (typeof directive.body === 'number' && (frame != null ? frame[directive.body - 1] : void 0)) {
        frameValue = frame[directive.body - 1].value;
        // If it's already a Block or an array of nodes, use it directly
        // This preserves any modifications made by operations
        if (frameValue instanceof nodes.Block || (Array.isArray(frameValue) && frameValue.some(function(v) {
          return v instanceof nodes.Base;
        }))) {
          body = frameValue;
        } else {
          body = this.evaluateDirective(directive.body, frame, ruleName);
        }
      } else {
        body = this.evaluateDirective(directive.body, frame, ruleName);
      }
      // Check if this is a bound function (fat arrow =>)
      funcGlyph = this.evaluateDirective(directive.funcGlyph, frame, ruleName);
      bound = (funcGlyph != null ? funcGlyph.glyph : void 0) === '=>' || this.evaluateDirective(directive.bound, frame, ruleName);
      // Ensure params are proper nodes
      if (Array.isArray(params)) {
        paramsNode = params.map((p) => {
          if (p != null ? p.type : void 0) {
            return this.solarNodeToClass(p);
          } else if (p instanceof nodes.Base) {
            return p;
          } else {
            return this.ensureNode(p);
          }
        });
        paramsNode = this.filterNodes(paramsNode);
      } else {
        paramsNode = [];
      }
      // Ensure body is a proper Block with converted nodes
      bodyNode = Array.isArray(body) ? (bodyNodes = body.map((b) => {
        // Check for nodes.Base FIRST to avoid re-processing existing nodes
        if (b instanceof nodes.Base) {
          return b;
        } else if (b != null ? b.type : void 0) {
          return this.solarNodeToClass(b);
        } else {
          return this.ensureNode(b);
        }
      }), new nodes.Block(this.filterNodes(bodyNodes))) : this.toBlock(body);
      // Create proper FuncGlyph for bound/unbound functions
      funcGlyph = bound ? new nodes.FuncGlyph('=>') : new nodes.FuncGlyph('->');
      codeNode = new nodes.Code(paramsNode, bodyNode, funcGlyph);
      // For CS3, pre-scan for super calls to avoid false positives
      // in derived constructor validation
      hasSuper = false;
      if (bodyNode != null ? bodyNode.expressions : void 0) {
        bodyNode.traverseChildren(false, function(node) {
          if (node instanceof nodes.SuperCall || (node instanceof nodes.Call && node.variable instanceof nodes.Super)) {
            hasSuper = true;
            return false; // Stop traversing
          }
          return true; // Continue traversing
        });
      }
      
      // Monkey-patch only for constructors; avoid affecting arrow methods and regular methods
      isCtor = !!(this.evaluateDirective(directive.isConstructor, frame, ruleName));
      if (hasSuper && isCtor) {
        // Skip validation for @params in derived constructors
        origFlag = codeNode.flagThisParamInDerivedClassConstructorWithoutCallingSuper;
        codeNode.flagThisParamInDerivedClassConstructorWithoutCallingSuper = function(param) {};
        // Also patch eachSuperCall to make it always find the super call
        // Skip the validation for CS3-generated code with super
        origEachSuper = codeNode.eachSuperCall;
        codeNode.eachSuperCall = function(context, iterator, opts) {
          var expr, j, len, ref1;
          // If checking params (not the body), use original so validations still run
          if (context !== this.body && (origEachSuper != null)) {
            return origEachSuper.call(this, context, iterator, opts);
          }
          // Otherwise, search body for the real SuperCall and report it
          if (iterator) {
            ref1 = bodyNode.expressions;
            for (j = 0, len = ref1.length; j < len; j++) {
              expr = ref1[j];
              if (expr instanceof nodes.SuperCall || (expr instanceof nodes.Call && expr.variable instanceof nodes.Super)) {
                iterator(expr);
                break;
              }
            }
          }
          return true;
        };
      }
      return codeNode;
    }

    createObj(directive, frame, ruleName) {
      var fixedProps, generated, j, key, len, obj, prop, propName, propNameStr, properties, ref1, ref2, value;
      properties = this.evaluateDirective(directive.properties, frame, ruleName);
      properties = this.filterNodes((Array.isArray(properties) ? properties : []));
      generated = this.evaluateDirective(directive.generated, frame, ruleName);
      // If object is generated (from braces) and has shorthand properties,
      // convert them to proper key-value pairs
      if (generated) {
        fixedProps = [];
        for (j = 0, len = properties.length; j < len; j++) {
          prop = properties[j];
          if (prop instanceof nodes.Value && prop.base instanceof nodes.IdentifierLiteral && !((ref1 = prop.properties) != null ? ref1.length : void 0)) {
            // This is a shorthand property like 'x' in {x}
            // Convert to x: x
            key = new nodes.Value(prop.base);
            value = new nodes.Value(prop.base);
            fixedProps.push(new nodes.Assign(key, value, 'object'));
          } else if (prop instanceof nodes.Value && prop.base instanceof nodes.ThisLiteral) {
            // This is an @ property like {@x} - extract the property name
            // and mark the Value node with this=true for Param.eachName to handle correctly
            if (((ref2 = prop.properties) != null ? ref2[0] : void 0) instanceof nodes.Access) {
              // Get the property name from the Access node
              propName = prop.properties[0].name;
              if (propName instanceof nodes.PropertyName) {
                // PropertyName has a 'value' property with the actual name
                propNameStr = propName.value;
                propName = new nodes.IdentifierLiteral(propNameStr);
              } else if (typeof propName === 'string') {
                propName = new nodes.IdentifierLiteral(propName);
              } else if (!(propName instanceof nodes.Base)) {
                propName = this.ensureNode(propName);
              }
              // Create the property assignment for object pattern
              // The value should be a Value node marked with this=true
              key = new nodes.Value(propName);
              value = new nodes.Value(propName);
              value.this = true; // Mark as @ parameter
              fixedProps.push(new nodes.Assign(key, value, 'object'));
            } else {
              fixedProps.push(prop);
            }
          } else {
            fixedProps.push(prop);
          }
        }
        properties = fixedProps;
      }
      obj = new nodes.Obj(properties, generated);
      if (obj.locationData == null) {
        obj.locationData = this.defaultLocationData();
      }
      return obj;
    }

    createAssign(directive, frame, ruleName) {
      var context, operator, options, value, variable;
      // Handle object property assignments differently
      if (directive.context === 'object' && (directive.expression != null)) {
        // In object context, 'value' is the property name, 'expression' is the value
        variable = this.evaluateDirective(directive.value, frame, ruleName);
        value = this.evaluateDirective(directive.expression, frame, ruleName);
        context = directive.context;
        // Mark Value nodes with ThisLiteral base as this=true for static properties
        if (variable instanceof nodes.Value && variable.base instanceof nodes.ThisLiteral) {
          variable.this = true;
        }
        return new nodes.Assign(variable, value, context);
      } else if ((directive.expression != null) && (directive.variable == null)) {
        // Default value assignment (e.g., in destructuring {x = 10})
        // Here 'value' is the variable name and 'expression' is the default value
        variable = this.evaluateDirective(directive.value, frame, ruleName);
        value = this.evaluateDirective(directive.expression, frame, ruleName);
        // Use null context for destructuring defaults so Param.eachName handles it correctly
        return new nodes.Assign(variable, value, null);
      } else {
        // Regular assignment
        variable = this.evaluateDirective(directive.variable, frame, ruleName);
        value = this.evaluateDirective(directive.value, frame, ruleName);
        // For compound assignments, use the operator as the context
        context = directive.operator != null ? (operator = this.evaluateDirective(directive.operator, frame, ruleName), operator) : this.evaluateDirective(directive.context, frame, ruleName);
        options = {};
        if (directive.originalContext != null) {
          options.originalContext = this.evaluateDirective(directive.originalContext, frame, ruleName);
        }
        // Create the Assign node with the correct context for compound assignments
        return new nodes.Assign(variable, value, context, options);
      }
    }

    // Helper to ensure value is a proper node
    ensureNode(value) {
      var node, ref1;
      if (value == null) {
        return null;
      }
      if (value.compileToFragments || value instanceof nodes.Base) {
        return value;
      }
      // Only wrap primitives; drop unknown objects to avoid emitting debug strings.
      if ((ref1 = typeof value) === 'string' || ref1 === 'number' || ref1 === 'boolean') {
        node = new nodes.Literal(String(value));
        if (node.locationData == null) {
          node.locationData = this.defaultLocationData();
        }
        return node;
      }
      // Try to convert objects that might be PropertyName-like
      if ((value != null ? value.value : void 0) != null) {
        node = new nodes.PropertyName(value.value);
        if (node.locationData == null) {
          node.locationData = this.defaultLocationData();
        }
        return node;
      }
      return null;
    }

    // Helper to filter and ensure all items are nodes
    filterNodes(array) {
      var item, j, len, node, result;
      if (array == null) {
        return [];
      }
      result = [];
      for (j = 0, len = array.length; j < len; j++) {
        item = array[j];
        node = this.toNode(item);
        if (node != null) {
          result.push(node);
        }
      }
      return result;
    }

    // Add mergeLocationData helper
    mergeLocationData(first, last) {
      var ref1, ref2;
      if (!last) {
        return first;
      }
      return {
        first_line: first.first_line,
        first_column: first.first_column,
        last_line: last.last_line,
        last_column: last.last_column,
        last_line_exclusive: (ref1 = last.last_line_exclusive) != null ? ref1 : first.last_line_exclusive,
        last_column_exclusive: (ref2 = last.last_column_exclusive) != null ? ref2 : first.last_column_exclusive,
        range: [first.range[0], last.range[1]]
      };
    }

    // ReductionFrame-based Solar directive evaluation
    reduce(values, positions, stackTop, symbolCount, directive) {
      var frame, i, j, offset, ref1;
      // Build frame directly from parser stacks using indices as a flat array
      frame = [];
      for (i = j = 0, ref1 = symbolCount; (0 <= ref1 ? j < ref1 : j > ref1); i = 0 <= ref1 ? ++j : --j) {
        offset = stackTop - symbolCount + i + 1;
        frame.push({
          value: values[offset],
          pos: positions[offset]
        });
      }
      // Evaluate Solar directive against ReductionFrame
      return this.evaluateDirective(directive, frame, null);
    }

    // Core directive evaluator - evaluates Solar directives against RHS frame
    evaluateDirective(directive, frame, ruleName = null) {
      var accessor, arg, args, argsNode, array, body, bodyNode, clause, directiveCopy, evaluated, exprDirective, expression, filteredBody, flattened, flip, glyph, idx, implicitValue, inner, innerDirective, invertOperator, item, itemCopy, j, k, key, l, left, len, len1, len2, len3, len4, literal, m, n, name, nameDirective, nameNode, negated, node, nodeType, object, op, opNode, originalOperator, prop, properties, ref, ref1, ref10, ref11, ref12, ref13, ref2, ref3, ref4, ref5, ref6, ref7, ref8, ref9, result, right, source, step, subProp, superNode, tail, templateArg, vNode, validProps, value, valueNode, varName, varValue, variable, variableNode;
      // Handle position references (1, 2, 3, ...) FIRST
      if (typeof directive === 'number') {
        return (ref1 = frame[directive - 1]) != null ? ref1.value : void 0; // 1-based → 0-based
      }
      if ((ref2 = typeof directive) === 'string' || ref2 === 'boolean') {
        
        // Handle primitives (except numbers, handled above)
        return directive;
      }
      // Handle arrays
      if (Array.isArray(directive)) {
        return directive.map((item) => {
          return this.evaluateDirective(item, frame, ruleName);
        });
      }
      // Handle Solar directives
      if ((directive != null) && typeof directive === 'object') {
        // $use directive (with optional method/prop/index)
        if (directive.$use != null) {
          ref = directive.$use;
          value = typeof ref === 'number' ? (ref3 = frame[ref - 1]) != null ? ref3.value : void 0 : typeof ref === 'string' && (this.variableContext[ref] != null) ? this.variableContext[ref] : ref; // Position reference // Direct value
          
          // Apply method calls
          if (directive.method != null) {
            args = ((ref4 = directive.args) != null ? ref4.map((arg) => {
              return this.evaluateDirective(arg, frame);
            }) : void 0) || [];
            return (value != null ? (ref5 = value[directive.method]) != null ? ref5.apply(value, args) : void 0 : void 0) || String(value);
          // Apply property access
          } else if (directive.prop != null) {
            // Special handling for boolean properties to avoid the falsy trap
            result = value != null ? value[directive.prop] : void 0;
            if ((result != null) || ((value != null) && typeof value === 'object' && directive.prop in value)) {
              return result;
            } else {
              return String(value);
            }
          // Apply array index access
          } else if (directive.index != null) {
            if (Array.isArray(value) || ((value != null ? value.length : void 0) != null)) {
              return (value != null ? value[directive.index] : void 0) || void 0;
            } else {
              return void 0;
            }
          } else {
            return value;
          }
        // $ast directive (AST node creation)
        } else if (directive.$ast != null) {
          // @ is now replaced with actual rule name at parser generation time
          nodeType = directive.$ast;
          // Directly create CoffeeScript node with evaluated properties
          switch (nodeType) {
            case 'Root':
              body = this.evaluateDirective(directive.body, frame, ruleName);
              body = this.toArray(body);
              filteredBody = this.filterNodes(body);
              return new nodes.Root(new nodes.Block(filteredBody));
            case 'IdentifierLiteral':
              return this.createIdentifierLiteral(directive, frame, ruleName);
            case 'Literal':
              return this.createLiteral(directive, frame, ruleName);
            case 'NumberLiteral':
              return this.createNumberLiteral(directive, frame, ruleName);
            case 'Value':
              // directive.val or directive.value can be a position reference (number) or actual value
              innerDirective = directive.val != null ? directive.val : directive.value;
              inner = this.evaluateDirective(innerDirective, frame, ruleName);
              // Handle properties (accessors)
              properties = this.evaluateDirective(directive.properties, frame, ruleName);
              // Special case: SuperCall should not be wrapped in Value unless it has properties
              if (inner instanceof nodes.SuperCall && (!properties || properties.length === 0)) {
                return inner;
              }
              if ((inner != null ? inner.compileToFragments : void 0) || inner instanceof nodes.Base) {
                valueNode = inner instanceof nodes.Value ? inner : new nodes.Value(inner);
                if (properties && Array.isArray(properties) && properties.length > 0) {
                  validProps = [];
                  for (j = 0, len = properties.length; j < len; j++) {
                    prop = properties[j];
                    // Handle nested arrays of properties (e.g., from :: operator)
                    if (Array.isArray(prop)) {
                      for (k = 0, len1 = prop.length; k < len1; k++) {
                        subProp = prop[k];
                        node = this.toNode(subProp);
                        if (node instanceof nodes.Base) {
                          validProps.push(node);
                        }
                      }
                    } else {
                      node = this.toNode(prop);
                      if (node instanceof nodes.Base) {
                        validProps.push(node);
                      }
                    }
                  }
                  // Only add non-null properties
                  if (validProps.length > 0) {
                    valueNode.add(validProps);
                  }
                }
                return valueNode;
              }
              return this.ensureNode(inner) || new nodes.Literal("/* TODO: Solar Value */");
            case 'Access':
              nameNode = this.evaluateDirective(directive.name, frame, ruleName);
              // Handle various forms of nameNode
              if (nameNode == null) {
                // For shorthand (::), use "prototype" as the name
                nameNode = directive.shorthand ? new nodes.PropertyName('prototype') : new nodes.PropertyName('');
              } else if (typeof nameNode === 'string') {
                nameNode = new nodes.PropertyName(nameNode);
              } else if (((nameNode != null ? nameNode.value : void 0) != null) && !(nameNode instanceof nodes.Base)) {
                nameNode = new nodes.PropertyName(String(nameNode.value));
              } else {
                nameNode = this.toNode(nameNode) || new nodes.PropertyName('');
              }
              return new nodes.Access(nameNode, {
                soak: directive.soak,
                shorthand: directive.shorthand
              });
            case 'Index':
              idx = this.evaluateDirective((directive.index != null ? directive.index : directive.name != null ? directive.name : directive.object), frame, ruleName);
              return new nodes.Index(this.ensureNode(idx));
            case 'PropertyName':
              return this.createPropertyName(directive, frame, ruleName);
            case 'Op':
              op = this.evaluateDirective((directive.operator != null ? directive.operator : (ref6 = directive.args) != null ? ref6[0] : void 0), frame, ruleName);
              left = this.ensureNode(this.evaluateDirective((directive.left != null ? directive.left : (ref7 = directive.args) != null ? ref7[1] : void 0), frame, ruleName));
              right = this.ensureNode(this.evaluateDirective((directive.right != null ? directive.right : (ref8 = directive.args) != null ? ref8[2] : void 0), frame, ruleName));
              flip = this.evaluateDirective((directive.flip != null ? directive.flip : (ref9 = directive.args) != null ? ref9[3] : void 0), frame, ruleName);
              originalOperator = this.evaluateDirective(directive.originalOperator, frame, ruleName);
              invertOperator = this.evaluateDirective(directive.invertOperator, frame, ruleName);
              // Handle CoffeeScript's in/of/instanceof operators
              // IMPORTANT: These work opposite to JavaScript!
              // CoffeeScript 'of' checks properties/keys (like JS 'in')
              // CoffeeScript 'in' checks values/elements (uses indexOf)

              // Check if this is a negated operator (not in, not of)
              negated = invertOperator === 'not' || invertOperator === true;
              if (op === 'of') {
                // 'x of obj' checks if x is a property/key/index
                // Compiles to JavaScript's native 'in' operator
                // MUST set originalOperator to null to prevent it defaulting to 'in'
                // which would trigger the isInOperator() check and create an In node
                opNode = new nodes.Op('in', left, right, false, {
                  originalOperator: null
                });
                // If negated (not of), wrap in a Parens to ensure proper precedence
                if (negated) {
                  return new nodes.Op('!', new nodes.Parens(opNode));
                } else {
                  return opNode;
                }
              } else if (op === 'in') {
                // 'x in array' checks if x is in the values
                // Op with originalOperator='in' will create an In node internally
                // If negated, set invertOperator to trigger inversion
                return new nodes.Op('in', left, right, false, {
                  originalOperator: 'in',
                  invertOperator: negated ? '!' : null
                });
              } else if (op === 'instanceof') {
                // instanceof checks type
                opNode = new nodes.Op('instanceof', left, right);
                if (negated) {
                  return new nodes.Op('!', opNode);
                } else {
                  return opNode;
                }
              } else {
                // All other operators
                return new nodes.Op(op, left, right, flip, {originalOperator, invertOperator});
              }
              break;
            case 'Arguments':
              args = this.evaluateDirective((directive.args != null ? directive.args : directive.$ary != null ? directive.$ary : directive), frame, ruleName);
              args = this.filterNodes(this.toArray(args));
              args = this.deepFlatten(args);
              // Handle implicit property if provided
              if (directive.implicit != null) {
                implicitValue = this.evaluateDirective(directive.implicit, frame, ruleName);
                args.implicit = !!implicitValue;
              } else {
                args.implicit = !!directive.implicit;
              }
              return args;
            case 'Call':
              variableNode = this.evaluateDirective(directive.variable, frame, ruleName);
              argsNode = this.evaluateDirective(directive.args, frame, ruleName);
              // Ensure args are proper nodes
              if (Array.isArray(argsNode)) {
                // Flatten and convert to nodes
                flattened = this.deepFlatten(argsNode);
                argsNode = [];
                for (l = 0, len2 = flattened.length; l < len2; l++) {
                  item = flattened[l];
                  node = this.toNode(item);
                  if (node != null) {
                    argsNode.push(node);
                  }
                }
              } else {
                argsNode = [];
              }
              // Check if this is a bare super() call (not a delegated super.method(...))
              if (variableNode instanceof nodes.Super) {
                return new nodes.SuperCall(variableNode, argsNode);
              } else if (variableNode instanceof nodes.Value && variableNode.base instanceof nodes.Super) {
                // Has a property access: this is super.method(...), NOT a constructor super()
                return new nodes.Call(variableNode, argsNode, this.evaluateDirective(directive.soak, frame, ruleName), this.evaluateDirective(directive.token, frame, ruleName));
              } else {
                return new nodes.Call((variableNode instanceof nodes.Value ? variableNode : new nodes.Value(variableNode)), argsNode, this.evaluateDirective(directive.soak, frame, ruleName), this.evaluateDirective(directive.token, frame, ruleName));
              }
              break;
            case 'TaggedTemplateCall':
              vNode = this.evaluateDirective(directive.variable, frame, ruleName);
              templateArg = this.ensureNode(this.evaluateDirective(directive.template, frame, ruleName));
              // Convert StringLiteral to StringWithInterpolations for tagged templates
              if (templateArg instanceof nodes.StringLiteral) {
                templateArg = nodes.StringWithInterpolations.fromStringLiteral(templateArg);
              }
              // Tagged templates should never have soak (no typeof check)
              return new nodes.TaggedTemplateCall((vNode instanceof nodes.Value ? vNode : new nodes.Value(vNode)), templateArg, false);
            case 'Assign':
              return this.createAssign(directive, frame, ruleName);
            case 'StringLiteral':
              return this.createStringLiteral(directive, frame, ruleName);
            case 'BooleanLiteral':
              return this.createBooleanLiteral(directive, frame, ruleName);
            case 'StatementLiteral':
              // Handle break, continue, debugger statements
              value = this.evaluateDirective(directive.value, frame, ruleName);
              switch (value) {
                case 'break':
                  return new nodes.StatementLiteral(value);
                case 'continue':
                  return new nodes.StatementLiteral(value);
                case 'debugger':
                  return new nodes.StatementLiteral(value);
                default:
                  // For other statements, create a basic literal
                  return new nodes.Literal(value);
              }
              break;
            case 'NullLiteral':
              return this.createNullLiteral();
            case 'UndefinedLiteral':
              return this.createUndefinedLiteral();
            case 'Arr':
              return this.createArr(directive, frame, ruleName);
            case 'Obj':
              return this.createObj(directive, frame, ruleName);
            case 'Range':
              return this.createRange(directive, frame, ruleName);
            case 'If':
            case 'if':
              return this.createIf(directive, frame, ruleName, 'if');
            case 'Unless':
            case 'unless':
              return this.createIf(directive, frame, ruleName, 'unless');
            case 'While':
              return this.createWhile(directive, frame, ruleName);
            case 'For':
              return this.createFor(directive, frame, ruleName);
            case 'Try':
              return this.createTry(directive, frame, ruleName);
            case 'Code':
              return this.createCode(directive, frame, ruleName);
            case 'Param':
              return this.createParam(directive, frame, ruleName);
            case 'Return':
              return this.createReturn(directive, frame, ruleName);
            case 'Yield':
              return this.createYield(directive, frame, ruleName);
            case 'Class':
              return this.createClass(directive, frame, ruleName);
            case 'Slice':
              return this.createSlice(directive, frame, ruleName);
            case 'Super':
              // Handle Super nodes which may have accessor for super.method() calls
              accessor = this.evaluateDirective(directive.accessor, frame, ruleName);
              literal = this.evaluateDirective(directive.literal, frame, ruleName);
              // If accessor is present, this is super.method() or super[expr]
              // The CS2 nodes.Super expects accessor to be set on the node
              superNode = new nodes.Super();
              if (accessor) {
                superNode.accessor = accessor;
              }
              if (literal) {
                superNode.literal = literal;
              }
              return superNode;
            case 'SuperCall':
              // Handle super() calls in constructors and methods
              args = this.evaluateDirective(directive.args, frame, ruleName);
              // Filter out nulls that ensureNode might return
              argsNode = Array.isArray(args) ? args.map((arg) => {
                return this.ensureNode(arg);
              }).filter((arg) => {
                return arg != null;
              }) : args ? (arg = this.ensureNode(args), arg != null ? [arg] : []) : [];
              // Create a SuperCall node with the Super variable and arguments
              variableNode = new nodes.Super();
              return new nodes.SuperCall(variableNode, argsNode);
            case 'StringWithInterpolations':
              return this.createStringWithInterpolations(directive, frame, ruleName);
            case 'Interpolation':
              return this.createInterpolation(directive, frame, ruleName);
            case 'TemplateElement':
              value = this.evaluateDirective(directive.value, frame, ruleName);
              tail = this.evaluateDirective(directive.tail, frame, ruleName);
              return new nodes.TemplateElement(value, tail);
            case 'Block':
              return this.createBlock(directive, frame, ruleName);
            case 'Body':
              return this.createBody(directive, frame, ruleName);
            case 'RegexLiteral':
            case 'Regex':
              return this.createRegexLiteral(directive, frame, ruleName);
            case 'Parens':
              return this.createParens(directive, frame, ruleName);
            case 'PassthroughLiteral':
              value = this.evaluateDirective(directive.value, frame, ruleName);
              return new nodes.PassthroughLiteral(value, {
                here: directive.here,
                generated: directive.generated
              });
            case 'Throw':
              return this.createThrow(directive, frame, ruleName);
            case 'Splat':
              // Check for 'name' or 'body' field (@ directive uses 'body')
              nameDirective = (ref10 = directive.name) != null ? ref10 : directive.body;
              name = this.evaluateDirective(nameDirective, frame, ruleName);
              // Splat requires a valid expression, not undefined
              if (name) {
                return new nodes.Splat(name);
              } else {
                // Create a placeholder if name is missing
                return new nodes.Splat(new nodes.Literal('undefined'));
              }
              break;
            case 'Expansion':
              // Check for 'expression' or 'body' field (@ directive uses 'body')
              exprDirective = (ref11 = directive.expression) != null ? ref11 : directive.body;
              expression = this.evaluateDirective(exprDirective, frame, ruleName);
              // Expansion needs a valid expression
              if (expression) {
                return new nodes.Expansion(expression);
              } else {
                return new nodes.Expansion(new nodes.Literal('undefined'));
              }
              break;
            case 'In':
              object = this.evaluateDirective(directive.object, frame, ruleName);
              array = this.evaluateDirective(directive.array, frame, ruleName);
              return new nodes.In(object, array);
            case 'ImportDeclaration':
              clause = this.evaluateDirective(directive.clause, frame, ruleName);
              source = this.evaluateDirective(directive.source, frame, ruleName);
              return new nodes.ImportDeclaration(clause, source);
            case 'ExportNamedDeclaration':
            case 'ExportDeclaration':
              clause = this.evaluateDirective(directive.clause, frame, ruleName);
              source = this.evaluateDirective(directive.source, frame, ruleName);
              return new nodes.ExportNamedDeclaration(clause, source);
            case 'Existence':
              return this.createExistence(directive, frame, ruleName);
            case 'Loop':
              return this.createLoop(directive, frame, ruleName);
            case 'Switch':
              return this.createSwitch(directive, frame, ruleName);
            case 'When':
            case 'SwitchWhen':
              return this.createSwitchWhen(directive, frame, ruleName);
            case 'Case':
            case 'SwitchCase':
              return this.createSwitchWhen(directive, frame, ruleName);
            case 'Catch':
              return this.createCatch(directive, frame, ruleName);
            case 'Finally':
              body = this.evaluateDirective(directive.body, frame, ruleName);
              bodyNode = Array.isArray(body) ? new nodes.Block(this.filterNodes(body)) : body;
              return new nodes.Finally(bodyNode);
            case 'Await':
              return this.createAwait(directive, frame, ruleName);
            case 'YieldFrom':
              return this.createYieldFrom(directive, frame, ruleName);
            case 'ThisLiteral':
            case 'This':
              return this.createThisLiteral();
            case 'Elision':
              // Elisions in array destructuring are placeholders for skipped elements
              // CS2 has a special Elision class for this
              return new nodes.Elision();
            case 'InfinityLiteral':
              // Infinity is a special numeric value
              return new nodes.Literal('Infinity');
            case 'NaNLiteral':
              // NaN is a special numeric value
              return new nodes.Literal('NaN');
            case 'ComputedPropertyName':
              // Computed property names like ["dynamic" + key]: value
              expression = this.evaluateDirective(directive.expression, frame, ruleName);
              // Return a bracket notation access node
              if (expression instanceof nodes.Base) {
                return expression;
              } else {
                return this.ensureNode(expression);
              }
              break;
            case 'DynamicImport':
              // Dynamic import is just the 'import' keyword itself
              return new nodes.IdentifierLiteral('import');
            case 'DynamicImportCall':
              // Dynamic import: import('./module')
              variable = this.evaluateDirective(directive.variable, frame, ruleName);
              args = this.evaluateDirective(directive.args, frame, ruleName);
              // Ensure variable is the import identifier
              variableNode = variable instanceof nodes.Base ? variable : new nodes.IdentifierLiteral('import');
              // Process arguments
              // Filter out nulls that ensureNode might return
              argsNode = Array.isArray(args) ? args.map((arg) => {
                return this.ensureNode(arg);
              }).filter((arg) => {
                return arg != null;
              }) : args ? (arg = this.ensureNode(args), arg != null ? [arg] : []) : [];
              return new nodes.Call(variableNode, argsNode, false);
            case 'FuncGlyph':
              // FuncGlyph for -> or => functions
              glyph = this.evaluateDirective(directive.glyph, frame, ruleName);
              return new nodes.FuncGlyph(glyph);
            default:
              // For unimplemented types, create placeholder
              return new nodes.Literal(`/* TODO: Solar ${nodeType} */`);
          }
        // $ary directive (array creation)
        } else if (directive.$ary != null) {
          // If $ary is a number, it's a position reference to an existing array
          if (typeof directive.$ary === 'number') {
            result = this.evaluateDirective(directive.$ary, frame, ruleName);
            result = this.toArray(result);
          } else {
            // Create new array from elements
            result = [];
            ref12 = directive.$ary;
            for (m = 0, len3 = ref12.length; m < len3; m++) {
              item = ref12[m];
              // If item is a number, it's a position reference
              if (typeof item === 'number') {
                evaluated = this.evaluateDirective(item, frame, ruleName);
              } else {
                // Item is an object, might have a $pos directive - evaluate without it
                itemCopy = Object.assign({}, item);
                if (itemCopy.$pos != null) {
                  delete itemCopy.$pos;
                }
                evaluated = this.evaluateDirective(itemCopy, frame, ruleName);
              }
              if (evaluated != null) {
                // Skip null/undefined items
                result.push(evaluated);
              }
            }
          }
// Handle additional properties (like implicit)
          for (key in directive) {
            value = directive[key];
            if (key !== '$ary' && !key.startsWith('$')) {
              result[key] = this.evaluateDirective(value, frame, ruleName);
            }
          }
          return result;
        // $ops directive (operations)
        } else if (directive.$ops != null) {
          result = this.applyOperation(directive, frame, ruleName);
          // If the operation returned a value, use it; otherwise evaluate the rest of the directive
          if (result != null) {
            return result;
          } else {
            // Try evaluating the directive without $ops (for combined directives)
            directiveCopy = Object.assign({}, directive);
            delete directiveCopy.$ops;
            return this.evaluateDirective(directiveCopy, frame, ruleName);
          }
        // $seq directive (sequences)
        } else if (directive.$seq != null) {
          result = null;
          ref13 = directive.$seq;
          for (n = 0, len4 = ref13.length; n < len4; n++) {
            step = ref13[n];
            // Handle $var directives to store variables
            if ((step != null ? step.$var : void 0) != null) {
              varName = step.$var;
              varValue = this.evaluateDirective(step.value, frame, ruleName);
              this.variableContext[varName] = varValue;
            } else {
              result = this.evaluateDirective(step, frame, ruleName);
            }
          }
          return result;
        } else {
          // Plain object (evaluate properties)
          result = {};
          for (key in directive) {
            value = directive[key];
            if (!key.startsWith('$')) {
              result[key] = this.evaluateDirective(value, frame, ruleName);
            }
          }
          return result;
        }
      } else {
        return directive;
      }
    }

    // Convert evaluated Solar node to CoffeeScript class (Phase A: Legacy adapter)
    // This is a compatibility shim that converts already-evaluated Solar nodes to CoffeeScript nodes
    // It creates a mock directive and frame, then uses our existing creation methods
    solarNodeToClass(solarNode) {
      var directive, mockFrame, result;
      if (!(solarNode != null ? solarNode.type : void 0)) {
        return null;
      }
      if (solarNode instanceof nodes.Base) {
        // For nodes that are already CoffeeScript nodes, return as-is
        return solarNode;
      }
      // Create a mock directive that looks like what evaluateDirective expects
      // Most Solar nodes have their properties directly on the object
      directive = Object.assign({
        $ast: solarNode.type
      }, solarNode);
      // Create a mock frame with empty context
      mockFrame = {
        rhs: [],
        ruleName: solarNode.type
      };
      // Use our existing evaluateDirective logic, which will dispatch to the appropriate create method
      result = this.evaluateDirective(directive, mockFrame, solarNode.type);
      // If evaluateDirective couldn't handle it, fall back to a simple literal
      return result || new nodes.Literal(`/* TODO: Solar node ${solarNode.type} */`);
    }

    // Resolve $pos directive to locationData
    resolvePosition(posDirective, frame) {
      var end, endCol, endLine, ref1, ref2, ref3, start, startCol, startLine;
      if (typeof posDirective === 'number') {
        // $pos: 1 → copy slot 1's position
        return ((ref1 = frame[posDirective - 1]) != null ? ref1.pos : void 0) || this.defaultLocationData();
      } else if (Array.isArray(posDirective)) {
        if (posDirective.length === 2) {
          // $pos: [1, 3] → span from slot 1 to slot 3
          start = (ref2 = frame[posDirective[0] - 1]) != null ? ref2.pos : void 0;
          end = (ref3 = frame[posDirective[1] - 1]) != null ? ref3.pos : void 0;
          if (start && end) {
            return this.mergeLocationData(start, end);
          }
        } else if (posDirective.length === 4) {
          // $pos: [sl, sc, el, ec] → explicit position
          [startLine, startCol, endLine, endCol] = posDirective;
          return {
            first_line: startLine,
            first_column: startCol,
            last_line: endLine,
            last_column: endCol,
            range: [0, 0]
          };
        }
      } else {
        return this.defaultLocationData();
      }
    }

    // Operation handlers
    applyArrayOperation(directive, frame, ruleName) {
      var evaluated, item, j, k, len, len1, ref1, ref2, result, target, value;
      if (directive.append != null) {
        // First element is the target array, rest are items to append
        target = this.evaluateDirective(directive.append[0], frame, ruleName);
        // Ensure target is an array
        target = Array.isArray(target) ? target : [];
        ref1 = directive.append.slice(1);
        for (j = 0, len = ref1.length; j < len; j++) {
          item = ref1[j];
          value = this.evaluateDirective(item, frame, ruleName);
          // If value is already an array (from $ary), unwrap it
          if (Array.isArray(value) && value.length === 1) {
            if (value[0] != null) {
              target.push(value[0]);
            }
          } else {
            if (value != null) {
              target.push(value);
            }
          }
        }
        return target;
      } else if (directive.gather != null) {
        result = [];
        ref2 = directive.gather;
        for (k = 0, len1 = ref2.length; k < len1; k++) {
          item = ref2[k];
          evaluated = this.evaluateDirective(item, frame, ruleName);
          if (Array.isArray(evaluated)) {
            result = result.concat(evaluated);
          } else {
            if (evaluated != null) {
              result.push(evaluated);
            }
          }
        }
        return result;
      }
    }

    applyValueOperation(directive, frame, ruleName) {
      var clonedValue, propNode, propNodes, propRaw, ref1, targetNode, targetRaw;
      // Add an accessor (Access/Index) to a Value
      if (directive.add != null) {
        targetRaw = this.evaluateDirective(directive.add[0], frame, ruleName);
        propRaw = this.evaluateDirective(directive.add[1], frame, ruleName);
        targetNode = this.toNode(targetRaw) || this.ensureNode(targetRaw);
        // Handle array of properties
        propNodes = Array.isArray(propRaw) ? propRaw.map((p) => {
          return this.toNode(p) || this.ensureNode(p);
        }) : (propNode = this.toNode(propRaw) || this.ensureNode(propRaw), propNode != null ? [propNode] : void 0);
        if (!((targetNode != null) && (propNodes != null ? propNodes.length : void 0) > 0)) {
          // Ensure we have valid nodes before proceeding
          return null;
        }
        if (targetNode instanceof nodes.Value) {
          // Clone the Value node to avoid mutation issues
          clonedValue = Object.assign(Object.create(Object.getPrototypeOf(targetNode)), targetNode);
          clonedValue.properties = (targetNode.properties || []).slice();
          clonedValue.add(propNodes);
          return clonedValue;
        } else {
          return new nodes.Value(targetNode, propNodes);
        }
      }
      return this.evaluateDirective((ref1 = directive.add) != null ? ref1[0] : void 0, frame, ruleName);
    }

    applyIfOperation(directive, frame, ruleName) {
      var block, elseBody, elseBodyNode, ifNode;
      // If operations for adding else clauses
      if (directive.addElse != null) {
        // addElse: [ifNode, elseBody] - add else clause to if statement
        ifNode = this.evaluateDirective(directive.addElse[0], frame, ruleName);
        elseBody = this.evaluateDirective(directive.addElse[1], frame, ruleName);
        if (ifNode instanceof nodes.If) {
          if (elseBody != null ? elseBody.type : void 0) {
            // Convert elseBody to proper node if needed
            elseBody = this.toNode(elseBody);
          }
          // Set the else body (alternate property)
          elseBodyNode = Array.isArray(elseBody) ? (block = new nodes.Block(this.filterNodes(elseBody)), block.locationData != null ? block.locationData : block.locationData = this.defaultLocationData(), block) : elseBody instanceof nodes.Block ? (elseBody.locationData != null ? elseBody.locationData : elseBody.locationData = this.defaultLocationData(), elseBody) : elseBody ? elseBody instanceof nodes.Base ? (elseBody.locationData != null ? elseBody.locationData : elseBody.locationData = this.defaultLocationData(), elseBody) : (block = new nodes.Block([this.ensureNode(elseBody)]), block.locationData != null ? block.locationData : block.locationData = this.defaultLocationData(), block) : null;
          if (elseBodyNode != null) {
            // Use addElse to properly handle else-if chains
            ifNode.addElse(elseBodyNode);
          }
        }
        return ifNode;
      } else {
        return null;
      }
    }

    applyLoopOperation(directive, frame, ruleName) {
      var bodyArg, bodyNode, loopNode, position, ref1, sourceInfo;
      if (directive.addSource != null) {
        // addSource: [loop, source] - add source to loop
        loopNode = this.evaluateDirective(directive.addSource[0], frame, ruleName);
        sourceInfo = this.evaluateDirective(directive.addSource[1], frame, ruleName);
        if (sourceInfo != null ? sourceInfo.type : void 0) {
          // Convert sourceInfo to proper node if needed
          sourceInfo = this.toNode(sourceInfo);
        }
        // Ensure source has proper structure
        if (sourceInfo) {
          // For addSource, we might get an object with source, name, index, etc.
          if (sourceInfo instanceof nodes.Base) {
            // Already a node, ensure it has locationData
            if (sourceInfo.locationData == null) {
              sourceInfo.locationData = this.defaultLocationData();
            }
          } else if (typeof sourceInfo === 'object' && !Array.isArray(sourceInfo)) {
            if (sourceInfo.source && !(sourceInfo.source instanceof nodes.Base)) {
              // It's a source object with properties
              sourceInfo.source = this.ensureNode(sourceInfo.source);
            }
            if (sourceInfo.name && !(sourceInfo.name instanceof nodes.Base)) {
              sourceInfo.name = this.ensureNode(sourceInfo.name);
            }
            if (sourceInfo.index && !(sourceInfo.index instanceof nodes.Base)) {
              sourceInfo.index = this.ensureNode(sourceInfo.index);
            }
          } else {
            // Convert to node
            sourceInfo = this.ensureNode(sourceInfo);
          }
        }
        if (loopNode && sourceInfo) {
          loopNode.addSource(sourceInfo);
        }
        loopNode;
      } else if (directive.addBody != null) {
        // addBody: [loop, body] - add body to loop
        loopNode = this.evaluateDirective(directive.addBody[0], frame, ruleName);
        bodyArg = directive.addBody[1];
        // Handle "Body $N" placeholder
        if (typeof bodyArg === 'string' && bodyArg.startsWith('Body $')) {
          position = parseInt(bodyArg.slice(6));
          bodyNode = this.evaluateDirective(position, frame, ruleName);
        } else {
          bodyNode = this.evaluateDirective(bodyArg, frame, ruleName);
        }
        if (bodyNode != null ? bodyNode.type : void 0) {
          // Convert body to proper node if needed
          bodyNode = this.toNode(bodyNode);
        }
        // Ensure body is a proper Block node with locationData
        if (bodyNode) {
          // Handle different body types
          if (Array.isArray(bodyNode)) {
            bodyNode = new nodes.Block(this.filterNodes(bodyNode));
          } else if (!(bodyNode instanceof nodes.Block)) {
            bodyNode = new nodes.Block([bodyNode instanceof nodes.Base ? bodyNode : this.ensureNode(bodyNode)]);
          }
          if (bodyNode.locationData == null) {
            bodyNode.locationData = this.defaultLocationData();
          }
        } else {
          bodyNode = new nodes.Block([]);
          bodyNode.locationData = this.defaultLocationData();
        }
        if (loopNode) {
          loopNode.addBody(bodyNode);
        }
        loopNode;
      } else {
        loopNode = this.evaluateDirective((ref1 = directive.addBody) != null ? ref1[0] : void 0, frame, ruleName);
      }
      // Handle postfix property if specified
      if ((directive.postfix != null) && (loopNode != null)) {
        loopNode.postfix = this.evaluateDirective(directive.postfix, frame, ruleName);
      }
      return loopNode;
    }

    // Apply $ops operations
    applyOperation(directive, frame, ruleName) {
      var ref1;
      switch (directive.$ops) {
        case 'array':
          return this.applyArrayOperation(directive, frame, ruleName);
        case 'value':
          return this.applyValueOperation(directive, frame, ruleName);
        case 'if':
          return this.applyIfOperation(directive, frame, ruleName);
        case 'loop':
          return this.applyLoopOperation(directive, frame, ruleName);
        case 'prop':
          // TODO: Implement property operations (set)
          return this.evaluateDirective((ref1 = directive.set) != null ? ref1.target : void 0, frame, ruleName);
        default:
          return new nodes.Literal(`/* TODO: $ops ${directive.$ops} */`);
      }
    }

    // Legacy dataToClass method (backward compatibility for non-frame calls)
    dataToClass(node) {
      var mockFrame, ref1;
      if (node == null) {
        return null;
      }
      if ((ref1 = typeof node) === 'string' || ref1 === 'number' || ref1 === 'boolean') {
        return node;
      }
      if (Array.isArray(node)) {
        return node.map((item) => {
          return this.dataToClass(item);
        });
      }
      // For legacy calls without frame, create minimal frame
      if ((node != null) && typeof node === 'object') {
        if (node.type != null) {
          // Already a normalized node - convert directly
          return this.solarNodeToClass(node);
        } else {
          // Solar directive without frame - limited support
          mockFrame = {
            rhs: [
              {
                value: node
              }
            ]
          };
          return this.evaluateDirective(node, mockFrame);
        }
      }
    }

  };

  module.exports = ES5Backend;

}).call(this);
