// Generated by CoffeeScript 2.7.0
(function() {
  //!/usr/bin/env coffee

  // ==============================================================================
  // CS3 ES5 Backend - Clean Room Implementation
  // ==============================================================================

  // Converts CS3 data-oriented AST nodes to CoffeeScript's class-based AST nodes
  // Then uses the existing CoffeeScript compiler to generate JavaScript

  // Key fixes in this version:
  // 1. Loop variable conflict prevention
  // 2. Proper super call handling
  // 3. Array elision support
  // ==============================================================================
  var ES5Backend, nodes;

  nodes = require('../../coffeescript/nodes');

  ES5Backend = class ES5Backend {
    constructor(options1 = {}) {
      var ref, ref1, ref2, ref3;
      this.options = options1;
      this.compileOptions = {
        bare: (ref = this.options.bare) != null ? ref : true,
        header: (ref1 = this.options.header) != null ? ref1 : false,
        sourceMap: (ref2 = this.options.sourceMap) != null ? ref2 : false,
        inlineMap: (ref3 = this.options.inlineMap) != null ? ref3 : false,
        // Signal to nodes compiler that we're in CS3 pipeline, so it can relax
        // early "this-before-super" checks to let our lowering run.
        cs3: true
      };
      // CRITICAL FIX for #4889: Track unique variable allocation for nested for-loops
      this.loopVarCounter = 0;
      this.usedLoopVars = new Set();
    }

    // Main entry point - convert CS3 data node to JavaScript
    generate(dataNode) {
      var classNode, result;
      classNode = this.dataToClass(dataNode);
      if (classNode == null) {
        return ''; // CRITICAL: Never return undefined
      }
      result = classNode.compile(this.compileOptions);
      return result || ''; // CRITICAL: Ensure we always return a string
    }

    
      // Helper to create default locationData
    defaultLocationData() {
      return {
        first_line: 0,
        first_column: 0,
        last_line: 0,
        last_column: 0,
        last_line_exclusive: 0,
        last_column_exclusive: 0,
        range: [0, 0]
      };
    }

    // CRITICAL FIX for #4889: Generate unique loop variables like CoffeeScript's scope.freeVariable
    getUniqueLoopVar() {
      var diff, endCode, letter, newCode, num, startCode, varName;
      // Use the same algorithm as CoffeeScript's scope.temporary with single=true
      // Generate: i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, then i1, j1, etc.
      startCode = 'i'.charCodeAt(0); // 105
      endCode = 'z'.charCodeAt(0); // 122
      diff = endCode - startCode; // 17
      newCode = startCode + this.loopVarCounter % (diff + 1);
      letter = String.fromCharCode(newCode);
      num = Math.floor(this.loopVarCounter / (diff + 1));
      varName = `${letter}${num || ''}`;
      this.loopVarCounter++;
      this.usedLoopVars.add(varName);
      return varName;
    }

    // Helper to ensure value is a proper node
    ensureNode(value) {
      var ref;
      if (value == null) {
        return null;
      }
      if (value.compileToFragments || value instanceof nodes.Base) {
        return value;
      }
      // Only wrap primitives; drop unknown objects to avoid emitting debug strings.
      if ((ref = typeof value) === 'string' || ref === 'number' || ref === 'boolean') {
        return new nodes.Literal(String(value));
      }
      return null;
    }

    // CRITICAL: Enhanced null-safe node conversion
    safeDataToClass(node) {
      var error, result;
      if (node == null) {
        return null;
      }
      try {
        result = this.dataToClass(node);
        return result || null;
      } catch (error1) {
        error = error1;
        console.error("CS3 Backend node conversion error:", error.message);
        return new nodes.Literal("/* conversion error */");
      }
    }

    // Helper to filter and ensure all items are nodes
    filterNodes(array) {
      var i, item, len, node, result;
      if (array == null) {
        return [];
      }
      result = [];
      for (i = 0, len = array.length; i < len; i++) {
        item = array[i];
        node = this.ensureNode(this.dataToClass(item));
        if (node != null) {
          result.push(node);
        }
      }
      return result;
    }

    // Add mergeLocationData helper
    mergeLocationData(first, last) {
      var ref, ref1;
      if (!last) {
        return first;
      }
      return {
        first_line: first.first_line,
        first_column: first.first_column,
        last_line: last.last_line,
        last_column: last.last_column,
        last_line_exclusive: (ref = last.last_line_exclusive) != null ? ref : first.last_line_exclusive,
        last_column_exclusive: (ref1 = last.last_column_exclusive) != null ? ref1 : first.last_column_exclusive,
        range: [first.range[0], last.range[1]]
      };
    }

    // Convert CS3 data nodes to CoffeeScript class nodes
    dataToClass(node) {
      var access, accessNode, accessor, arg, args, assertObj, assertions, assignments, atParam, atParams, attempt, attemptNode, base, body, bodyNode, bodyNodes, callNode, cases, catch_, className, clause, codeNode, condition, conditions, context, converted, declaration, defaultBinding, elision, elseBody, ensure, ensureNode, err, exportNode, exported, expr, expression, expressionNodes, expressions, first, firstAccess, flatParams, flip, forNode, from, funcGlyph, generated, guard, i, ifNode, importNode, index, indexNode, inferredMeta, isAtParam, item, j, k, key, l, lastProp, left, len, len1, len2, len3, len4, len5, len6, local, m, metaName, metaNode, name, nameData, nameNode, namedImports, o, obj, objNode, objects, op, options, original, otherwise, otherwiseNode, p, param, paramNode, params, parent, prevClassName, prevInClassBody, processedParams, prop, propAccess, propName, properties, propertyAccess, prototypeAccess, q, range, rangeNode, recovery, recoveryNode, ref, ref1, ref10, ref11, ref12, ref13, ref14, ref15, ref16, ref17, ref18, ref19, ref2, ref20, ref21, ref22, ref23, ref24, ref25, ref26, ref3, ref4, ref5, ref6, ref7, ref8, ref9, result, returnKeyword, right, second, simpleParam, soak, source, sourceObj, spec, specifiers, splat, stringNode, subject, tag, thisLit, to, val, value, valueNode, variable, variableNode, wrappedVar;
      if (node == null) {
        return null;
      }
      if ((ref = typeof node) === 'string' || ref === 'number' || ref === 'boolean') {
        // Handle primitives
        return node;
      }
      // Handle arrays
      if (Array.isArray(node)) {
        return node.map((item) => {
          return this.dataToClass(item);
        });
      }
      if (!(node != null ? node.type : void 0)) {
        // Must be an object with a type
        return null;
      }
      switch (node.type) {
        // ============================================================
        // Root and Structural Nodes
        // ============================================================
        case 'Root':
          bodyNodes = Array.isArray(node.body) ? this.filterNodes(node.body) : node.body ? (converted = this.dataToClass(node.body), converted != null ? [converted] : []) : [];
          return new nodes.Root(new nodes.Block(bodyNodes));
        case 'Block':
          expressions = node.expressions ? (converted = this.dataToClass(node.expressions), Array.isArray(converted) ? converted.filter(function(item) {
            return item != null;
          }) : converted != null ? [converted] : []) : node.body ? (converted = this.dataToClass(node.body), Array.isArray(converted) ? converted.filter(function(item) {
            return item != null;
          }) : converted != null ? [converted] : []) : [];
          return new nodes.Block(expressions);
        // ============================================================
        // Literals
        // ============================================================
        case 'NumberLiteral':
          return new nodes.NumberLiteral(node.value, node.parsedValue);
        case 'StringLiteral':
          options = {
            quote: node.quote,
            initialChunk: node.initialChunk,
            finalChunk: node.finalChunk,
            indent: node.indent,
            double: node.double,
            heregex: node.heregex
          };
          stringNode = new nodes.StringLiteral(node.value, options);
          stringNode.originalValue = node.value; // Critical: needed for withoutQuotesInLocationData
          // Ensure locationData is properly set with defaults if missing
          stringNode.locationData = node.locationData || this.defaultLocationData();
          return stringNode;
        case 'Literal':
          return new nodes.Literal(node.value);
        case 'BooleanLiteral':
          return new nodes.BooleanLiteral(node.value);
        case 'NullLiteral':
          return new nodes.NullLiteral();
        case 'UndefinedLiteral':
          return new nodes.UndefinedLiteral();
        case 'InfinityLiteral':
          return new nodes.InfinityLiteral(node.value);
        case 'NaNLiteral':
          return new nodes.NaNLiteral();
        case 'IdentifierLiteral':
          return new nodes.IdentifierLiteral(node.value);
        case 'PropertyName':
          return new nodes.PropertyName(node.value);
        case 'StatementLiteral':
          return new nodes.StatementLiteral(node.value);
        case 'ThisLiteral':
          return new nodes.ThisLiteral(node.value || 'this');
        case 'RegexLiteral':
          return new nodes.RegexLiteral(node.value, {
            delimiter: node.delimiter,
            heregexCommentTokens: node.heregexCommentTokens
          });
        case 'PassthroughLiteral':
          return new nodes.PassthroughLiteral(node.value, {
            here: node.here,
            generated: node.generated
          });
        // ============================================================
        // Values and Properties
        // ============================================================
        case 'Value':
          base = this.dataToClass(node.val || node.base || node.value);
          if (!base) {
            // Handle empty Value nodes (like in "yield" without operand)
            base = new nodes.UndefinedLiteral();
          }
          properties = (function() {
            var i, j, len, len1, ref1;
            if (node.properties) {
              result = [];
              ref1 = node.properties;
              for (i = 0, len = ref1.length; i < len; i++) {
                prop = ref1[i];
                if (Array.isArray(prop)) {
// Handle nested arrays (like [[Access, Access]] for ::)
                  for (j = 0, len1 = prop.length; j < len1; j++) {
                    item = prop[j];
                    converted = this.dataToClass(item);
                    if (converted) {
                      result.push(converted);
                    }
                  }
                } else {
                  converted = this.dataToClass(prop);
                  if (converted) {
                    result.push(converted);
                  }
                }
              }
              return result;
            } else {
              return [];
            }
          }).call(this);
          try {
            // Special-case import.meta: convert Value(import, Access(meta)) to MetaProperty
            if (base instanceof nodes.IdentifierLiteral && base.value === 'import') {
              if (properties.length > 0 && properties[0] instanceof nodes.Access) {
                firstAccess = properties[0];
                if ((firstAccess.name != null) && firstAccess.name.value === 'meta') {
                  metaNode = new nodes.IdentifierLiteral('import');
                  propertyAccess = new nodes.Access(new nodes.PropertyName('meta'));
                  base = new nodes.MetaProperty(metaNode, propertyAccess);
                  properties = properties.slice(1);
                }
              }
            }
          } catch (error1) {
            err = error1;
          }
          // fall through; keep generic Value
          valueNode = new nodes.Value(base, properties, tag);
          if (node.locationData) {
            valueNode.locationData = node.locationData;
          }
          // If properties, merge from base to last property
          if (properties.length > 0) {
            lastProp = properties[properties.length - 1];
            valueNode.locationData = this.mergeLocationData(base.locationData || valueNode.locationData, lastProp.locationData);
          }
          return valueNode;
        case 'Access':
          name = this.dataToClass(node.name);
          accessNode = new nodes.Access(name);
          if (node.soak) {
            accessNode.soak = node.soak;
          }
          if (node.shorthand) {
            accessNode.shorthand = node.shorthand;
          }
          return accessNode;
        case 'Index':
          index = this.dataToClass(node.object || node.name);
          indexNode = new nodes.Index(index);
          if (node.soak) {
            indexNode.soak = node.soak;
          }
          return indexNode;
        // ============================================================
        // Assignment
        // ============================================================
        case 'Assign':
          // Handle object property assignments
          if (node.context === 'object' && node.expression) {
            // CRITICAL FIX: Detect class properties vs object literal properties

            // CRITICAL FIX: Detect class properties vs object literal properties

            // Check if this is a class static property (@prop)
            if (((ref1 = node.value) != null ? ref1.type : void 0) === 'Value' && ((ref2 = node.value.val) != null ? ref2.type : void 0) === 'Value' && ((ref3 = node.value.val.val) != null ? ref3.type : void 0) === 'ThisLiteral') {
              // Static property: @prop -> ClassName.prop = value
              // The property name is in node.value.val.properties[0].name.value
              propName = (ref4 = node.value.val.properties) != null ? (ref5 = ref4[0]) != null ? (ref6 = ref5.name) != null ? ref6.value : void 0 : void 0 : void 0;
              if (propName && this.currentClassName) {
                // Create ClassName.propName
                className = new nodes.IdentifierLiteral(this.currentClassName);
                propAccess = new nodes.Value(className, [new nodes.Access(new nodes.PropertyName(propName))]);
                value = this.dataToClass(node.expression);
                return new nodes.Assign(propAccess, value);
              }
            // Check if this is a class instance property (prop:) - but not constructor
            } else if (this.inClassBody && ((ref7 = node.value) != null ? ref7.type : void 0) === 'Value' && ((ref8 = node.value.val) != null ? ref8.type : void 0) === 'PropertyName') {
              propName = node.value.val.value;
              // Skip constructor - it's handled separately by the Class node
              if (propName !== 'constructor' && propName && this.currentClassName) {
                // Instance property: prop -> ClassName.prototype.prop = value
                className = new nodes.IdentifierLiteral(this.currentClassName);
                prototypeAccess = new nodes.Value(className, [new nodes.Access(new nodes.PropertyName('prototype'))]);
                propAccess = new nodes.Value(prototypeAccess, [new nodes.Access(new nodes.PropertyName(propName))]);
                value = this.dataToClass(node.expression);
                return new nodes.Assign(propAccess, value);
              }
            }
            // Regular object literal property
            if (((ref9 = node.value) != null ? ref9.type : void 0) === 'Value') {
              base = node.value.val;
            } else {
              base = node.value;
            }
            if ((base != null ? base.type : void 0) === 'PropertyName') {
              variable = this.dataToClass(base);
            } else if ((ref10 = base != null ? base.type : void 0) === 'IdentifierLiteral' || ref10 === 'StringLiteral' || ref10 === 'NumberLiteral') {
              variable = new nodes.PropertyName(base.value);
            } else {
              // Fallback to class conversion; Obj compile will validate
              variable = this.dataToClass(node.value);
            }
            if (!(variable instanceof nodes.Value)) {
              // Ensure Value for downstream class initializer analysis
              variable = new nodes.Value(variable);
            }
            value = this.dataToClass(node.expression);
            return new nodes.Assign(variable, value, 'object');
          } else {
            variable = this.dataToClass(node.variable);
            value = this.dataToClass(node.value);
          }
          if (!((variable != null) && (value != null))) {
            return null;
          }
          context = node.context;
          options = {};
          if (node.param) {
            options.param = node.param;
          }
          if (node.subpattern) {
            options.subpattern = node.subpattern;
          }
          if (node.operatorToken) {
            if (typeof node.operatorToken === 'object' && node.operatorToken.type) {
              options.operatorToken = {
                value: node.operatorToken.value,
                locationData: node.operatorToken.locationData
              };
            } else {
              options.operatorToken = this.dataToClass(node.operatorToken);
            }
          }
          if (node.moduleDeclaration) {
            options.moduleDeclaration = node.moduleDeclaration;
          }
          return new nodes.Assign(variable, value, context, options);
        // ============================================================
        // Operations
        // ============================================================
        case 'Op':
          if (node.args) {
            [op, first, second, flip] = node.args;
            if (typeof op === 'object') {
              op = op.toString();
            }
            first = this.dataToClass(first);
            if (second) {
              second = this.dataToClass(second);
            }
            // Critical: Pass invertOperator and originalOperator
            options = {};
            if (node.invertOperator) {
              options.invertOperator = node.invertOperator;
            }
            if (node.originalOperator) {
              options.originalOperator = node.originalOperator;
            }
            return new nodes.Op(op, first, second, flip, options);
          } else {
            op = node.operator || node.op;
            first = this.dataToClass(node.first);
            if (node.second) {
              second = this.dataToClass(node.second);
            }
            return new nodes.Op(op, first, second, node.flip);
          }
          break;
        case 'Existence':
          expression = this.dataToClass(node.expression);
          return new nodes.Existence(expression);
        // ============================================================
        // Functions and Calls
        // ============================================================
        case 'Code':
          // First, flatten params and collect @params to generate thisAssignments
          flatParams = [];
          atParams = []; // Track @params to lower and assign in body
          if (node.params) {
            ref11 = node.params;
            for (i = 0, len = ref11.length; i < len; i++) {
              param = ref11[i];
              if (Array.isArray(param)) {
                for (j = 0, len1 = param.length; j < len1; j++) {
                  p = param[j];
                  flatParams.push(p);
                }
              } else {
                flatParams.push(param);
              }
            }
          }
          // Process params, handling @params by lowering them to plain params
          processedParams = [];
          for (k = 0, len2 = flatParams.length; k < len2; k++) {
            param = flatParams[k];
            // Check if this is an @param that needs special handling
            isAtParam = (param != null ? param.type : void 0) === 'Param' && ((ref12 = param.name) != null ? ref12.type : void 0) === 'Value' && ((ref13 = param.name.val) != null ? ref13.type : void 0) === 'ThisLiteral' && ((ref14 = param.name.properties) != null ? ref14.length : void 0) > 0;
            if (isAtParam) {
              // Convert @name to regular name parameter for all functions
              propName = param.name.properties[0].name.value;
              // Create a simple param directly with nodes classes
              nameNode = new nodes.IdentifierLiteral(propName);
              // Handle default values if present
              if (param.value) {
                valueNode = this.dataToClass(param.value);
                simpleParam = new nodes.Param(nameNode, valueNode);
              } else {
                simpleParam = new nodes.Param(nameNode);
              }
              // Handle splat if present
              if (param.splat) {
                simpleParam.splat = param.splat;
              }
              processedParams.push(simpleParam);
              // Save assignment to be applied in body (ideally after super)
              atParams.push({
                name: propName
              });
            } else {
              // Regular param
              converted = this.dataToClass(param);
              if (converted) {
                processedParams.push(converted);
              }
            }
          }
          params = processedParams;
          bodyNodes = Array.isArray(node.body) ? this.filterNodes(node.body) : node.body ? (converted = this.dataToClass(node.body), converted != null ? [converted] : []) : [];
          // Build a nodes.Code and attach thisAssignments; compiler will inject
          // them after super() when possible via expandCtorSuper.
          body = new nodes.Block(bodyNodes);
          funcGlyph = ((ref15 = node.funcGlyph) != null ? ref15.glyph : void 0) || '->';
          tag = funcGlyph === '=>' ? 'boundfunc' : null;
          codeNode = new nodes.Code(params, body, tag);
          if (atParams.length > 0) {
            assignments = [];
            for (l = 0, len3 = atParams.length; l < len3; l++) {
              atParam = atParams[l];
              thisLit = new nodes.ThisLiteral();
              access = new nodes.Access(new nodes.PropertyName(atParam.name));
              left = new nodes.Value(thisLit, [access]);
              right = new nodes.IdentifierLiteral(atParam.name);
              assignments.push(new nodes.Assign(left, right));
            }
            codeNode.thisAssignments = assignments;
          }
          return codeNode;
        case 'Param':
          name = this.dataToClass(node.name);
          if (node.value) {
            value = this.dataToClass(node.value);
          }
          splat = !!node.splat;
          paramNode = new nodes.Param(name, value, splat);
          if (node.locationData) {
            paramNode.locationData = node.locationData;
          }
          return paramNode;
        case 'Call':
          variable = this.dataToClass(node.variable);
          args = node.args ? this.filterNodes(node.args) : [];
          soak = node.soak;
          callNode = new nodes.Call(variable, args, soak);
          if (node.new) {
            callNode.isNew = true;
          }
          if (node.new) {
            callNode.locationData = this.mergeLocationData(node.new.locationData, callNode.locationData || this.defaultLocationData());
          }
          return callNode;
        case 'Super':
          if (node.accessor) {
            accessor = this.dataToClass(node.accessor);
          }
          return new nodes.Super(accessor);
        case 'SuperCall':
          // SuperCall extends Call(variable, args, soak)
          // The variable should be a Super node
          variable = node.variable ? this.dataToClass(node.variable) : new nodes.Super();
          // Process arguments, filtering out empty objects
          args = (function() {
            var len4, m, ref16;
            if (node.args) {
              result = [];
              ref16 = node.args;
              for (m = 0, len4 = ref16.length; m < len4; m++) {
                arg = ref16[m];
                // Skip empty objects
                if ((arg != null) && (arg.type || Object.keys(arg).length > 0)) {
                  converted = this.dataToClass(arg);
                  if (converted) {
                    result.push(converted);
                  }
                }
              }
              return result;
            } else {
              return [];
            }
          }).call(this);
          // Create SuperCall with Super as variable and filtered args
          return new nodes.SuperCall(variable, args, node.soak);
        // ============================================================
        // Arrays and Objects
        // ============================================================
        case 'Arr':
          objects = (function() {
            var len4, len5, len6, m, o, q, ref16, ref17;
            if (node.objects) {
              result = [];
              ref16 = node.objects;
              for (m = 0, len4 = ref16.length; m < len4; m++) {
                obj = ref16[m];
                if (Array.isArray(obj)) {
// Process all elements in nested arrays (happens with elisions)
                  for (o = 0, len5 = obj.length; o < len5; o++) {
                    item = obj[o];
                    if ((item != null ? item.type : void 0) === 'Elision') {
                      // Handle elisions - create actual hole/empty slot
                      result.push(new nodes.Elision());
                    } else {
                      converted = this.dataToClass(item);
                      if (converted) {
                        result.push(converted);
                      }
                    }
                  }
                } else if ((obj != null ? obj.type : void 0) === 'Elision') {
                  // Handle elisions - create actual hole/empty slot
                  result.push(new nodes.Elision());
                } else if (typeof obj === 'object' && Object.keys(obj).length > 0) {
                  converted = this.dataToClass(obj);
                  if (converted) {
                    result.push(converted);
                  }
                }
              }
              // Handle trailing elisions stored in separate elisions property
              // Only process elisions that have type: 'Elision', not empty objects
              if (node.elisions) {
                ref17 = node.elisions;
                for (q = 0, len6 = ref17.length; q < len6; q++) {
                  elision = ref17[q];
                  if ((elision != null ? elision.type : void 0) === 'Elision') {
                    result.push(new nodes.Elision());
                  }
                }
              }
              return result;
            } else if (node.value) {
              if (Array.isArray(node.value)) {
                return node.value.filter(function(v) {
                  return !(typeof v === 'object' && Object.keys(v).length === 0);
                }).map((v) => {
                  return this.dataToClass(v);
                });
              } else {
                return [this.dataToClass(node.value)];
              }
            } else {
              return [];
            }
          }).call(this);
          return new nodes.Arr(objects);
        case 'Obj':
          properties = (function() {
            var len4, len5, m, o, ref16;
            if (node.properties) {
              result = [];
              ref16 = node.properties;
              for (m = 0, len4 = ref16.length; m < len4; m++) {
                prop = ref16[m];
                if (Array.isArray(prop)) {
                  for (o = 0, len5 = prop.length; o < len5; o++) {
                    item = prop[o];
                    converted = this.dataToClass(item);
                    if ((converted != null) && converted instanceof nodes.Base) {
                      result.push(converted);
                    }
                  }
                } else if (prop != null) {
                  // CS3 Obj property can be an Assign-like structure with key and value
                  if (prop.type === 'Assign' && prop.context === 'object') {
                    variableNode = this.dataToClass(prop.value);
                    // Ensure variable is a Value so downstream methods like hasProperties/lookStatic exist
                    variable = variableNode instanceof nodes.Value ? variableNode : new nodes.Value(variableNode);
                    value = this.dataToClass(prop.expression);
                    if ((variable != null) && (value != null)) {
                      result.push(new nodes.Assign(variable, value, 'object'));
                    }
                  } else {
                    converted = this.dataToClass(prop);
                    if ((converted != null) && converted instanceof nodes.Base) {
                      result.push(converted);
                    }
                  }
                }
              }
              return result;
            } else {
              return [];
            }
          }).call(this);
          generated = node.generated;
          return new nodes.Obj(properties, generated);
        case 'Range':
          from = node.from ? this.dataToClass(node.from) : null;
          to = node.to ? this.dataToClass(node.to) : null;
          tag = node.exclusive ? 'exclusive' : 'inclusive';
          // Ensure proper range evaluation for nested loops
          rangeNode = new nodes.Range(from, to, tag);
          if (node.locationData) {
            rangeNode.locationData = node.locationData;
          }
          return rangeNode;
        case 'Slice':
          // Create a Slice with its range
          if (node.range) {
            range = this.dataToClass(node.range);
            return new nodes.Slice(range);
          } else {
            // console.warn "Slice without range:", node
            return null;
          }
          break;
        case 'Splat':
          // CRITICAL FIX: Ensure splat name is valid for assignment
          nameData = node.name || node.body || node.value;
          if (nameData != null) {
            name = this.dataToClass(nameData);
            // Validate that name can be assigned to
            if (name && (name instanceof nodes.IdentifierLiteral || name instanceof nodes.Value || name instanceof nodes.Arr || name instanceof nodes.Obj)) {
              return new nodes.Splat(name);
            } else {
              // Invalid splat name, create a safe placeholder
              return new nodes.Splat(new nodes.IdentifierLiteral('rest'));
            }
          } else {
            // No name provided, create default
            return new nodes.Splat(new nodes.IdentifierLiteral('rest'));
          }
          break;
        case 'Expansion':
          return new nodes.Expansion();
        case 'Elision':
          // Support array elisions - create actual hole/empty slot
          return new nodes.Elision();
        // ============================================================
        // Control Flow
        // ============================================================
        case 'If':
        case 'if':
        case 'unless':
          condition = this.dataToClass(node.condition);
          body = Array.isArray(node.body) ? (bodyNodes = node.body.map((n) => {
            return this.dataToClass(n);
          }), new nodes.Block(bodyNodes)) : this.dataToClass(node.body);
          options = {};
          if (node.type) {
            options.type = node.type;
          }
          if (node.postfix) {
            options.postfix = node.postfix;
          }
          ifNode = new nodes.If(condition, body, options);
          if (node.elseBody) {
            elseBody = Array.isArray(node.elseBody) ? (bodyNodes = node.elseBody.map((n) => {
              return this.dataToClass(n);
            }), new nodes.Block(bodyNodes)) : this.dataToClass(node.elseBody);
            ifNode.elseBody = elseBody;
            ifNode.isChain = elseBody instanceof nodes.If;
          }
          return ifNode;
        case 'While':
          condition = this.dataToClass(node.condition);
          if (node.guard) {
            guard = this.dataToClass(node.guard);
          }
          body = Array.isArray(node.body) ? new nodes.Block(this.dataToClass(node.body)) : this.dataToClass(node.body);
          return new nodes.While(condition, guard).addBody(body);
        case 'For':
          // Convert body
          body = Array.isArray(node.body) ? (bodyNodes = node.body.map((n) => {
            converted = this.dataToClass(n);
            if (converted) {
              if (converted.locationData == null) {
                converted.locationData = this.defaultLocationData();
              }
            }
            return converted;
          }), new nodes.Block(bodyNodes)) : node.body ? this.dataToClass(node.body) : new nodes.Block([]);
          // Ensure locationData
          if (body.locationData == null) {
            body.locationData = this.defaultLocationData();
          }
          if (body.expressions) {
            ref16 = body.expressions;
            for (m = 0, len4 = ref16.length; m < len4; m++) {
              expr = ref16[m];
              if (expr.locationData == null) {
                expr.locationData = this.defaultLocationData();
              }
            }
          }
          // Build source object (only pass class nodes; avoid raw flags that confuse semantics)
          sourceObj = {};
          if (node.source != null) {
            sourceObj.source = this.dataToClass(node.source);
          }
          if (node.guard != null) {
            sourceObj.guard = this.dataToClass(node.guard);
          }
          if (node.step != null) {
            sourceObj.step = this.dataToClass(node.step);
          }
          if (node.name != null) {
            sourceObj.name = this.dataToClass(node.name);
          }
          if (node.index != null) {
            sourceObj.index = this.dataToClass(node.index);
          }
          if (node.own != null) {
            sourceObj.own = !!node.own;
          }
          if (node.object != null) {
            sourceObj.object = !!node.object;
          }
          if (node.await != null) {
            sourceObj.await = !!node.await;
          }
          if (node.awaitTag != null) {
            sourceObj.awaitTag = this.dataToClass(node.awaitTag);
          }
          if (node.ownTag != null) {
            sourceObj.ownTag = this.dataToClass(node.ownTag);
          }
          // SIMPLER FIX for #4889: Let CoffeeScript handle variable allocation naturally
          // The complex scope override was causing test framework issues
          // Just create the For node normally - the core issue was elsewhere
          forNode = new nodes.For(body, sourceObj);
          if (node.locationData) {
            forNode.locationData = node.locationData;
          }
          return forNode;
        case 'Switch':
          subject = this.dataToClass(node.subject);
          cases = node.cases ? node.cases.map((c) => {
            return this.dataToClass(c);
          }) : [];
          otherwise = node.otherwise ? (otherwiseNode = this.dataToClass(node.otherwise), otherwiseNode instanceof nodes.Block ? otherwiseNode : Array.isArray(otherwiseNode) ? new nodes.Block(otherwiseNode) : otherwiseNode != null ? new nodes.Block([otherwiseNode]) : null) : null;
          return new nodes.Switch(subject, cases, otherwise);
        case 'SwitchWhen':
          conditions = this.dataToClass(node.conditions);
          body = node.body ? (bodyNode = this.dataToClass(node.body), bodyNode instanceof nodes.Block ? bodyNode : Array.isArray(bodyNode) ? new nodes.Block(bodyNode) : bodyNode != null ? new nodes.Block([bodyNode]) : new nodes.Block([])) : new nodes.Block([]);
          return new nodes.SwitchWhen(conditions, body);
        case 'Try':
          attempt = node.attempt ? (attemptNode = this.dataToClass(node.attempt), attemptNode instanceof nodes.Block ? attemptNode : Array.isArray(attemptNode) ? new nodes.Block(attemptNode) : attemptNode != null ? new nodes.Block([attemptNode]) : new nodes.Block([])) : new nodes.Block([]);
          if (node.catch) {
            catch_ = this.dataToClass(node.catch);
          }
          ensure = node.ensure ? (ensureNode = this.dataToClass(node.ensure), ensureNode instanceof nodes.Block ? ensureNode : Array.isArray(ensureNode) ? new nodes.Block(ensureNode) : ensureNode != null ? new nodes.Block([ensureNode]) : null) : null;
          return new nodes.Try(attempt, catch_, ensure);
        case 'Catch':
          recovery = node.recovery || node.body ? (recoveryNode = this.dataToClass(node.recovery || node.body), recoveryNode instanceof nodes.Block ? recoveryNode : Array.isArray(recoveryNode) ? new nodes.Block(recoveryNode) : recoveryNode != null ? new nodes.Block([recoveryNode]) : new nodes.Block([])) : new nodes.Block([]);
          if (node.variable) {
            variable = this.dataToClass(node.variable);
          }
          return new nodes.Catch(recovery, variable);
        case 'Throw':
          expression = this.dataToClass(node.expression);
          return new nodes.Throw(expression);
        case 'Return':
          if (node.expression) {
            expression = this.dataToClass(node.expression);
          }
          return new nodes.Return(expression);
        case 'YieldReturn':
          if (node.expression) {
            expression = this.dataToClass(node.expression);
          }
          if (node.returnKeyword) {
            returnKeyword = this.dataToClass(node.returnKeyword);
          }
          return new nodes.YieldReturn(expression, {returnKeyword});
        case 'AwaitReturn':
          if (node.expression) {
            expression = this.dataToClass(node.expression);
          }
          if (node.returnKeyword) {
            returnKeyword = this.dataToClass(node.returnKeyword);
          }
          return new nodes.AwaitReturn(expression, {returnKeyword});
        // ============================================================
        // Classes
        // ============================================================
        case 'Class':
          if (node.variable) {
            variable = this.dataToClass(node.variable);
          }
          if (node.parent) {
            parent = this.dataToClass(node.parent);
          }
          // CRITICAL FIX: Track class context for property conversion
          prevInClassBody = this.inClassBody;
          prevClassName = this.currentClassName;
          this.inClassBody = true;
          this.currentClassName = ((ref17 = node.variable) != null ? ref17.type : void 0) === 'IdentifierLiteral' ? node.variable.value : ((ref18 = node.variable) != null ? ref18.type : void 0) === 'Value' && ((ref19 = node.variable.val) != null ? ref19.type : void 0) === 'IdentifierLiteral' ? node.variable.val.value : 'UnknownClass';
          body = (function() {
            var len5, len6, len7, o, q, r, ref20, ref21, ref22;
            if (Array.isArray(node.body)) {
              bodyNodes = [];
              ref20 = node.body;
              for (o = 0, len5 = ref20.length; o < len5; o++) {
                item = ref20[o];
                if (item.type === 'Value' && ((ref21 = item.val) != null ? ref21.type : void 0) === 'Obj') {
                  // Extract methods from object literal
                  objNode = item.val;
                  if (objNode.properties) {
                    ref22 = objNode.properties;
                    for (q = 0, len6 = ref22.length; q < len6; q++) {
                      prop = ref22[q];
                      if (Array.isArray(prop)) {
                        for (r = 0, len7 = prop.length; r < len7; r++) {
                          p = prop[r];
                          converted = this.dataToClass(p);
                          if (converted) {
                            bodyNodes.push(converted);
                          }
                        }
                      } else if (prop) {
                        converted = this.dataToClass(prop);
                        if (converted) {
                          bodyNodes.push(converted);
                        }
                      }
                    }
                  }
                } else {
                  converted = this.dataToClass(item);
                  if (converted) {
                    // Ensure any class body assignment has a Value variable for core checks
                    if (converted instanceof nodes.Assign) {
                      if (!(converted.variable instanceof nodes.Value)) {
                        wrappedVar = new nodes.Value(converted.variable);
                        converted = new nodes.Assign(wrappedVar, converted.value, converted.context);
                      }
                    }
                    bodyNodes.push(converted);
                  }
                }
              }
              return new nodes.Block(bodyNodes);
            } else if (node.body) {
              return this.dataToClass(node.body);
            } else {
              return new nodes.Block([]);
            }
          }).call(this);
          // Restore previous class context
          this.inClassBody = prevInClassBody;
          this.currentClassName = prevClassName;
          return new nodes.Class(variable, parent, body);
        // ============================================================
        // Parentheticals
        // ============================================================
        case 'Parens':
          body = Array.isArray(node.body) ? (bodyNodes = node.body.map((n) => {
            return this.dataToClass(n);
          }), new nodes.Block(bodyNodes)) : this.dataToClass(node.body);
          return new nodes.Parens(body);
        // ============================================================
        // String Interpolation
        // ============================================================
        case 'StringWithInterpolations':
          bodyNodes = (function() {
            var len5, o, ref20, results;
            ref20 = node.body || [];
            results = [];
            for (o = 0, len5 = ref20.length; o < len5; o++) {
              expr = ref20[o];
              results.push(this.dataToClass(expr));
            }
            return results;
          }).call(this);
          body = new nodes.Block(bodyNodes);
          stringNode = new nodes.StringWithInterpolations(body, node.quote);
          if (node.startQuote) {
            stringNode.startQuote = this.dataToClass(node.startQuote);
          }
          // Ensure locationData is properly set with defaults if missing
          stringNode.locationData = node.locationData || this.defaultLocationData();
          return stringNode;
        case 'Interpolation':
          expression = Array.isArray(node.expression) ? node.expression.length === 1 ? this.dataToClass(node.expression[0]) : (expressionNodes = node.expression.map((n) => {
            return this.dataToClass(n);
          }), new nodes.Block(expressionNodes)) : node.expression ? this.dataToClass(node.expression) : new nodes.Block([]);
          return new nodes.Interpolation(expression);
        // ============================================================
        // Import/Export
        // ============================================================
        case 'ImportDeclaration':
          if (node.clause) {
            clause = this.dataToClass(node.clause);
          }
          if (node.source) {
            source = this.dataToClass(node.source);
          }
          assertions = [];
          if (node.assertions) {
            assertObj = this.dataToClass(node.assertions);
            ref20 = assertObj.properties || [];
            for (o = 0, len5 = ref20.length; o < len5; o++) {
              prop = ref20[o];
              if (prop.type === 'Assign') {
                key = prop.variable;
                val = prop.value;
                assertions.push(new nodes.Assign(key, val, 'assert'));
              }
            }
          }
          importNode = new nodes.ImportDeclaration(clause, source);
          if (assertions.length > 0) {
            importNode.assertions = assertions;
          }
          if (node.locationData) {
            importNode.locationData = node.locationData;
          }
          return importNode;
        case 'ExportNamedDeclaration':
          if (node.clause) {
            clause = this.dataToClass(node.clause);
          }
          if (node.source) {
            source = this.dataToClass(node.source);
          }
          exportNode = new nodes.ExportNamedDeclaration(clause, source);
          if (node.locationData) {
            exportNode.locationData = node.locationData;
          }
          return exportNode;
        case 'ExportDefaultDeclaration':
          if (node.declaration) {
            declaration = this.dataToClass(node.declaration);
          }
          exportNode = new nodes.ExportDefaultDeclaration(declaration);
          if (node.locationData) {
            exportNode.locationData = node.locationData;
          }
          return exportNode;
        case 'ExportAllDeclaration':
          if (node.exported) {
            exported = this.dataToClass(node.exported);
          }
          if (node.source) {
            source = this.dataToClass(node.source);
          }
          assertions = []; // similar to import
          if (node.assertions) {
            assertObj = this.dataToClass(node.assertions);
            ref21 = assertObj.properties || [];
            for (q = 0, len6 = ref21.length; q < len6; q++) {
              prop = ref21[q];
              if (prop.type === 'Assign') {
                key = prop.variable;
                val = prop.value;
                assertions.push(new nodes.Assign(key, val, 'assert'));
              }
            }
          }
          exportNode = new nodes.ExportAllDeclaration(exported, source);
          if (assertions.length > 0) {
            exportNode.assertions = assertions;
          }
          if (node.locationData) {
            exportNode.locationData = node.locationData;
          }
          return exportNode;
        case 'ImportClause':
          if (node.defaultBinding) {
            defaultBinding = this.dataToClass(node.defaultBinding);
          }
          if (node.namedImports) {
            namedImports = this.dataToClass(node.namedImports);
          }
          return new nodes.ImportClause(defaultBinding, namedImports);
        case 'ImportDefaultSpecifier':
          local = this.dataToClass(node.local || node.original || node.name || node.value);
          return new nodes.ImportDefaultSpecifier(local);
        case 'ImportSpecifier':
          original = this.dataToClass(node.imported || node.original || node.name);
          local = this.dataToClass(node.local || node.alias || node.name);
          return new nodes.ImportSpecifier(original, local);
        case 'ImportNamespaceSpecifier':
          local = this.dataToClass(node.local || node.name);
          return new nodes.ImportNamespaceSpecifier(local);
        case 'ImportSpecifierList':
          specifiers = (function() {
            var len7, r, ref22, results;
            ref22 = node.specifiers || [];
            results = [];
            for (r = 0, len7 = ref22.length; r < len7; r++) {
              spec = ref22[r];
              results.push(this.dataToClass(spec));
            }
            return results;
          }).call(this);
          return new nodes.ImportSpecifierList(specifiers);
        case 'ExportDeclaration':
          return new nodes.ExportDeclaration(this.dataToClass(node.clause));
        case 'ExportSpecifierList':
          specifiers = (function() {
            var len7, r, ref22, results;
            ref22 = node.specifiers || [];
            results = [];
            for (r = 0, len7 = ref22.length; r < len7; r++) {
              spec = ref22[r];
              results.push(this.dataToClass(spec));
            }
            return results;
          }).call(this);
          return new nodes.ExportSpecifierList(specifiers);
        case 'ExportSpecifier':
          if (node.local) {
            local = this.dataToClass(node.local);
          }
          if (node.exported) {
            exported = this.dataToClass(node.exported);
          }
          return new nodes.ExportSpecifier(local, exported);
        case 'DefaultLiteral':
          return new nodes.IdentifierLiteral(node.value);
        // ============================================================
        // Meta nodes
        // ============================================================
        case 'FuncGlyph':
          // This is metadata, not a real node
          return node;
        case 'Source':
          // Source is a wrapper node - unwrap it
          return this.dataToClass(node.value);
        case 'ComputedPropertyName':
          // ComputedPropertyName is just a marker - return a flag
          // The actual computed property value should be in the parent context
          return new nodes.Literal('computed');
        case 'MetaProperty':
          // MetaProperty like new.target or import.meta
          propName = ((ref22 = node.property) != null ? (ref23 = ref22.name) != null ? ref23.value : void 0 : void 0) || ((ref24 = node.property) != null ? ref24.value : void 0) || 'target';
          // If meta is missing but property is 'meta', infer 'import'
          inferredMeta = (node.meta == null) && propName === 'meta' ? 'import' : null;
          metaName = ((ref25 = node.meta) != null ? ref25.value : void 0) || node.meta || inferredMeta || 'new';
          metaNode = new nodes.IdentifierLiteral(metaName);
          propertyAccess = new nodes.Access(new nodes.PropertyName(propName));
          return new nodes.MetaProperty(metaNode, propertyAccess);
        case 'RegexWithInterpolations':
          // Regex with interpolations - convert to regular regex for now
          // This would need more complex handling for full support
          return new nodes.RegexLiteral(node.value || '//', node.flags || '');
        case 'DynamicImportCall':
          // Dynamic import() call - extends Call
          variable = new nodes.IdentifierLiteral('import');
          args = node.args ? this.filterNodes(node.args) : [];
          // DynamicImportCall extends Call, so pass variable and args
          return new nodes.DynamicImportCall(variable, args);
        case 'TaggedTemplateCall':
          // Tagged template literals - expects single arg (the template)
          variable = this.dataToClass(node.variable);
          // CS3 parser provides template property instead of args
          arg = node.template ? this.dataToClass(node.template) : ((ref26 = node.args) != null ? ref26.length : void 0) > 0 ? this.dataToClass(node.args[0]) : new nodes.StringLiteral('');
          return new nodes.TaggedTemplateCall(variable, arg, node.soak);
        default:
          // Silence debug output for cleaner test runs
          // console.warn "Unknown CS3 node type: #{node.type}"
          // ============================================================
          // Default fallback
          // ============================================================
          return new nodes.PassthroughLiteral(`/* Unknown node type: ${node.type} */`);
      }
    }

  };

  module.exports = ES5Backend;

}).call(this);
