// Generated by CoffeeScript 2.7.0
(function() {
  //!/usr/bin/env coffee

  // ==============================================================================
  // CS3 ES5 Backend - Clean Room Implementation
  // ==============================================================================

  // Converts CS3 data-oriented AST nodes to CoffeeScript's class-based AST nodes
  // Then uses the existing CoffeeScript compiler to generate JavaScript

  // Key fixes in this version:
  // 1. Loop variable conflict prevention
  // 2. Proper super call handling
  // 3. Array elision support
  // ==============================================================================
  var ES5Backend, nodes;

  nodes = require('../../coffeescript/nodes');

  ES5Backend = class ES5Backend {
    constructor(options = {}) {
      var ref1, ref2, ref3, ref4;
      this.options = options;
      this.compileOptions = {
        bare: (ref1 = this.options.bare) != null ? ref1 : true,
        header: (ref2 = this.options.header) != null ? ref2 : false,
        sourceMap: (ref3 = this.options.sourceMap) != null ? ref3 : false,
        inlineMap: (ref4 = this.options.inlineMap) != null ? ref4 : false,
        // Signal to nodes compiler that we're in CS3 pipeline, so it can relax
        // early "this-before-super" checks to let our lowering run.
        cs3: true
      };
      // CRITICAL FIX for #4889: Track unique variable allocation for nested for-loops
      this.loopVarCounter = 0;
      this.usedLoopVars = new Set();
    }

    // Main entry point - convert Solar directive or CoffeeScript node to JavaScript
    generate(node) {
      var classNode, result;
      // If already a CoffeeScript class node (from ReductionFrame), compile directly
      if (node != null ? node.compile : void 0) {
        result = node.compile(this.compileOptions);
        return result || '';
      }
      // Otherwise, convert via legacy dataToClass method
      classNode = this.dataToClass(node);
      if (classNode == null) {
        return '';
      }
      result = classNode.compile(this.compileOptions);
      return result || '';
    }

    // Helper to create default locationData
    defaultLocationData() {
      return {
        first_line: 0,
        first_column: 0,
        last_line: 0,
        last_column: 0,
        last_line_exclusive: 0,
        last_column_exclusive: 0,
        range: [0, 0]
      };
    }

    // CRITICAL FIX for #4889: Generate unique loop variables like CoffeeScript's scope.freeVariable
    getUniqueLoopVar() {
      var diff, endCode, letter, newCode, num, startCode, varName;
      // Use the same algorithm as CoffeeScript's scope.temporary with single=true
      // Generate: i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, then i1, j1, etc.
      startCode = 'i'.charCodeAt(0); // 105
      endCode = 'z'.charCodeAt(0); // 122
      diff = endCode - startCode; // 17
      newCode = startCode + this.loopVarCounter % (diff + 1);
      letter = String.fromCharCode(newCode);
      num = Math.floor(this.loopVarCounter / (diff + 1));
      varName = `${letter}${num || ''}`;
      this.loopVarCounter++;
      this.usedLoopVars.add(varName);
      return varName;
    }

    // Helper to ensure value is a proper node
    ensureNode(value) {
      var ref1;
      if (value == null) {
        return null;
      }
      if (value.compileToFragments || value instanceof nodes.Base) {
        return value;
      }
      // Only wrap primitives; drop unknown objects to avoid emitting debug strings.
      if ((ref1 = typeof value) === 'string' || ref1 === 'number' || ref1 === 'boolean') {
        return new nodes.Literal(String(value));
      }
      return null;
    }

    // CRITICAL: Enhanced null-safe node conversion
    safeDataToClass(node) {
      var error, result;
      if (node == null) {
        return null;
      }
      try {
        result = this.dataToClass(node);
        return result || null;
      } catch (error1) {
        error = error1;
        console.error("CS3 Backend node conversion error:", error.message);
        return new nodes.Literal("/* conversion error */");
      }
    }

    // Helper to filter and ensure all items are nodes
    filterNodes(array) {
      var i, item, len, node, result;
      if (array == null) {
        return [];
      }
      result = [];
      for (i = 0, len = array.length; i < len; i++) {
        item = array[i];
        if ((item != null ? item.compileToFragments : void 0) || item instanceof nodes.Base) {
          result.push(item);
          continue;
        }
        node = this.ensureNode(this.dataToClass(item));
        if (node != null) {
          result.push(node);
        }
      }
      return result;
    }

    // Add mergeLocationData helper
    mergeLocationData(first, last) {
      var ref1, ref2;
      if (!last) {
        return first;
      }
      return {
        first_line: first.first_line,
        first_column: first.first_column,
        last_line: last.last_line,
        last_column: last.last_column,
        last_line_exclusive: (ref1 = last.last_line_exclusive) != null ? ref1 : first.last_line_exclusive,
        last_column_exclusive: (ref2 = last.last_column_exclusive) != null ? ref2 : first.last_column_exclusive,
        range: [first.range[0], last.range[1]]
      };
    }

    // ReductionFrame-based Solar directive evaluation
    reduce(ruleName, directive, frame) {
      // Evaluate Solar directive against ReductionFrame
      return this.evaluateDirective(directive, frame, ruleName);
    }

    // Core directive evaluator - evaluates Solar directives against RHS frame
    evaluateDirective(directive, frame, ruleName = null) {
      var args, argsNode, body, context, flip, i, idx, inner, invertOperator, key, left, len, nameNode, nodeType, op, originalOperator, parsedValue, ref, ref1, ref10, ref2, ref3, ref4, ref5, ref6, ref7, ref8, ref9, result, right, step, templateArg, test, vNode, value, variable, variableNode;
      // Handle position references (1, 2, 3, ...) FIRST
      if (typeof directive === 'number') {
        return (ref1 = frame.rhs[directive - 1]) != null ? ref1.value : void 0; // 1-based → 0-based
      }
      if ((ref2 = typeof directive) === 'string' || ref2 === 'boolean') {
        
        // Handle primitives (except numbers, handled above)
        return directive;
      }
      // Handle arrays
      if (Array.isArray(directive)) {
        return directive.map((item) => {
          return this.evaluateDirective(item, frame, ruleName);
        });
      }
      // Handle Solar directives
      if ((directive != null) && typeof directive === 'object') {
        // $use directive (with optional method/prop)
        if (directive.$use != null) {
          ref = directive.$use;
          value = typeof ref === 'number' ? (ref3 = frame.rhs[ref - 1]) != null ? ref3.value : void 0 : ref; // Position reference // Direct value or temp variable
          
          // Apply method calls
          if (directive.method != null) {
            args = ((ref4 = directive.args) != null ? ref4.map((arg) => {
              return this.evaluateDirective(arg, frame);
            }) : void 0) || [];
            return (value != null ? (ref5 = value[directive.method]) != null ? ref5.apply(value, args) : void 0 : void 0) || String(value);
          // Apply property access
          } else if (directive.prop != null) {
            return (value != null ? value[directive.prop] : void 0) || String(value);
          } else {
            return value;
          }
        // $ast directive (AST node creation)
        } else if (directive.$ast != null) {
          nodeType = directive.$ast === '@' ? ruleName : directive.$ast;
          // Directly create CoffeeScript node with evaluated properties
          switch (nodeType) {
            case 'Root':
              body = this.evaluateDirective(directive.body, frame, ruleName);
              body = Array.isArray(body) ? body : (body != null ? [body] : []);
              return new nodes.Root(new nodes.Block(this.filterNodes(body)));
            case 'IdentifierLiteral':
              value = this.evaluateDirective(directive.value, frame, ruleName);
              return new nodes.IdentifierLiteral(value);
            case 'Literal':
              value = this.evaluateDirective(directive.value, frame, ruleName);
              return new nodes.Literal(value);
            case 'NumberLiteral':
              value = this.evaluateDirective(directive.value, frame, ruleName);
              parsedValue = this.evaluateDirective(directive.parsedValue, frame, ruleName);
              return new nodes.NumberLiteral(value, parsedValue);
            case 'Value':
              inner = this.evaluateDirective((directive.val != null ? directive.val : directive.value), frame, ruleName);
              if ((inner != null ? inner.compileToFragments : void 0) || inner instanceof nodes.Base) {
                if (inner instanceof nodes.Value) {
                  return inner;
                } else {
                  return new nodes.Value(inner);
                }
              }
              return this.ensureNode(inner) || new nodes.Literal("/* TODO: Solar Value */");
            case 'Access':
              nameNode = this.evaluateDirective(directive.name, frame, ruleName);
              return new nodes.Access(nameNode, {
                soak: directive.soak,
                shorthand: directive.shorthand
              });
            case 'Index':
              idx = this.evaluateDirective((directive.index != null ? directive.index : directive.name != null ? directive.name : directive.object), frame, ruleName);
              return new nodes.Index(this.ensureNode(idx));
            case 'PropertyName':
              value = this.evaluateDirective(directive.value, frame, ruleName);
              return new nodes.PropertyName(value);
            case 'Op':
              op = this.evaluateDirective((directive.operator != null ? directive.operator : (ref6 = directive.args) != null ? ref6[0] : void 0), frame, ruleName);
              left = this.ensureNode(this.evaluateDirective((directive.left != null ? directive.left : (ref7 = directive.args) != null ? ref7[1] : void 0), frame, ruleName));
              right = this.ensureNode(this.evaluateDirective((directive.right != null ? directive.right : (ref8 = directive.args) != null ? ref8[2] : void 0), frame, ruleName));
              flip = this.evaluateDirective((directive.flip != null ? directive.flip : (ref9 = directive.args) != null ? ref9[3] : void 0), frame, ruleName);
              originalOperator = this.evaluateDirective(directive.originalOperator, frame, ruleName);
              invertOperator = this.evaluateDirective(directive.invertOperator, frame, ruleName);
              return new nodes.Op(op, left, right, flip, {originalOperator, invertOperator});
            case 'Arguments':
              args = this.evaluateDirective((directive.args != null ? directive.args : directive.$ary != null ? directive.$ary : directive), frame, ruleName);
              args = this.filterNodes((Array.isArray(args) ? args : []));
              args.implicit = !!directive.implicit;
              return args;
            case 'Call':
              variableNode = this.evaluateDirective(directive.variable, frame, ruleName);
              argsNode = this.evaluateDirective(directive.args, frame, ruleName);
              if (!Array.isArray(argsNode)) {
                argsNode = [];
              }
              return new nodes.Call((variableNode instanceof nodes.Value ? variableNode : new nodes.Value(variableNode)), argsNode, this.evaluateDirective(directive.soak, frame, ruleName), this.evaluateDirective(directive.token, frame, ruleName));
            case 'TaggedTemplateCall':
              vNode = this.evaluateDirective(directive.variable, frame, ruleName);
              templateArg = this.ensureNode(this.evaluateDirective(directive.template, frame, ruleName));
              return new nodes.Call((vNode instanceof nodes.Value ? vNode : new nodes.Value(vNode)), [templateArg]);
            case 'Assign':
              variable = this.evaluateDirective(directive.variable, frame, ruleName);
              value = this.evaluateDirective(directive.value, frame, ruleName);
              context = this.evaluateDirective(directive.context, frame, ruleName);
              return new nodes.Assign(variable, value, context);
            default:
              // For unimplemented types, create placeholder
              return new nodes.Literal(`/* TODO: Solar ${nodeType} */`);
          }
        // $ary directive (array creation)
        } else if (directive.$ary != null) {
          return directive.$ary.map((item) => {
            return this.evaluateDirective(item, frame, ruleName);
          });
        // $ops directive (operations)
        } else if (directive.$ops != null) {
          return this.applyOperation(directive, frame, ruleName);
        // $seq directive (sequences)
        } else if (directive.$seq != null) {
          result = null;
          ref10 = directive.$seq;
          for (i = 0, len = ref10.length; i < len; i++) {
            step = ref10[i];
            result = this.evaluateDirective(step, frame, ruleName);
          }
          return result;
        // $ite directive (conditionals)
        } else if (directive.$ite != null) {
          test = this.evaluateDirective(directive.$ite.test, frame, ruleName);
          if (test) {
            return this.evaluateDirective(directive.$ite.then, frame, ruleName);
          } else {
            return this.evaluateDirective(directive.$ite.else, frame, ruleName);
          }
        } else {
          // Plain object (evaluate properties)
          result = {};
          for (key in directive) {
            value = directive[key];
            if (!key.startsWith('$')) {
              result[key] = this.evaluateDirective(value, frame, ruleName);
            }
          }
          return result;
        }
      } else {
        return directive;
      }
    }

    // Convert evaluated Solar node to CoffeeScript class (Phase A: Legacy adapter)
    solarNodeToClass(solarNode) {
      var first, second, value, variable;
      if (!(solarNode != null ? solarNode.type : void 0)) {
        return null;
      }
      switch (solarNode.type) {
        case 'IdentifierLiteral':
          return new nodes.IdentifierLiteral(solarNode.value);
        case 'Literal':
          return new nodes.Literal(solarNode.value);
        case 'NumberLiteral':
          return new nodes.NumberLiteral(solarNode.value, solarNode.parsedValue);
        case 'Op':
          if (solarNode.left) {
            first = this.solarNodeToClass(solarNode.left);
          }
          if (solarNode.right) {
            second = this.solarNodeToClass(solarNode.right);
          }
          return new nodes.Op(solarNode.operator, first, second, solarNode.flip);
        case 'Assign':
          if (solarNode.variable) {
            variable = this.solarNodeToClass(solarNode.variable);
          }
          if (solarNode.value) {
            value = this.solarNodeToClass(solarNode.value);
          }
          return new nodes.Assign(variable, value, solarNode.context);
        default:
          // Placeholder for unimplemented node types
          return new nodes.Literal(`/* TODO: Solar node ${solarNode.type} */`);
      }
    }

    // Resolve $pos directive to locationData
    resolvePosition(posDirective, frame) {
      var end, endCol, endLine, ref1, ref2, ref3, start, startCol, startLine;
      if (typeof posDirective === 'number') {
        // $pos: 1 → copy slot 1's position
        return ((ref1 = frame.rhs[posDirective - 1]) != null ? ref1.pos : void 0) || this.defaultLocationData();
      } else if (Array.isArray(posDirective)) {
        if (posDirective.length === 2) {
          // $pos: [1, 3] → span from slot 1 to slot 3
          start = (ref2 = frame.rhs[posDirective[0] - 1]) != null ? ref2.pos : void 0;
          end = (ref3 = frame.rhs[posDirective[1] - 1]) != null ? ref3.pos : void 0;
          if (start && end) {
            return this.mergeLocationData(start, end);
          }
        } else if (posDirective.length === 4) {
          // $pos: [sl, sc, el, ec] → explicit position
          [startLine, startCol, endLine, endCol] = posDirective;
          return {
            first_line: startLine,
            first_column: startCol,
            last_line: endLine,
            last_column: endCol,
            range: [0, 0]
          };
        }
      } else {
        return this.defaultLocationData();
      }
    }

    // Apply $ops operations
    applyOperation(directive, frame, ruleName) {
      var evaluated, i, item, j, len, len1, propNode, propRaw, ref1, ref2, ref3, ref4, ref5, ref6, result, target, targetNode, targetRaw, value;
      switch (directive.$ops) {
        case 'array':
          if (directive.append != null) {
            target = this.evaluateDirective(directive.append[0], frame, ruleName);
            ref1 = directive.append.slice(1);
            for (i = 0, len = ref1.length; i < len; i++) {
              item = ref1[i];
              value = this.evaluateDirective(item, frame, ruleName);
              if (value != null) {
                target.push(value);
              }
            }
            return target;
          } else if (directive.gather != null) {
            result = [];
            ref2 = directive.gather;
            for (j = 0, len1 = ref2.length; j < len1; j++) {
              item = ref2[j];
              evaluated = this.evaluateDirective(item, frame, ruleName);
              if (Array.isArray(evaluated)) {
                result = result.concat(evaluated);
              } else {
                if (evaluated != null) {
                  result.push(evaluated);
                }
              }
            }
            return result;
          }
          break;
        case 'value':
          // Add an accessor (Access/Index) to a Value
          if (directive.add != null) {
            targetRaw = this.evaluateDirective(directive.add[0], frame, ruleName);
            propRaw = this.evaluateDirective(directive.add[1], frame, ruleName);
            targetNode = (targetRaw != null ? targetRaw.compileToFragments : void 0) || targetRaw instanceof nodes.Base ? targetRaw : this.ensureNode(targetRaw);
            propNode = (propRaw != null ? propRaw.compileToFragments : void 0) || propRaw instanceof nodes.Base ? propRaw : this.ensureNode(propRaw);
            if (targetNode instanceof nodes.Value) {
              targetNode.add([propNode]);
              return targetNode;
            } else {
              return new nodes.Value(targetNode, [propNode]);
            }
          }
          return this.evaluateDirective((ref3 = directive.add) != null ? ref3[0] : void 0, frame, ruleName);
        case 'if':
          // TODO: Implement if operations (addElse)
          return this.evaluateDirective((ref4 = directive.addElse) != null ? ref4[0] : void 0, frame, ruleName);
        case 'loop':
          // TODO: Implement loop operations (addBody, addSource)
          return this.evaluateDirective((ref5 = directive.addBody) != null ? ref5[0] : void 0, frame, ruleName);
        case 'prop':
          // TODO: Implement property operations (set)
          return this.evaluateDirective((ref6 = directive.set) != null ? ref6.target : void 0, frame, ruleName);
        default:
          return new nodes.Literal(`/* TODO: $ops ${directive.$ops} */`);
      }
    }

    // Legacy dataToClass method (backward compatibility for non-frame calls)
    dataToClass(node) {
      var mockFrame, ref1;
      if (node == null) {
        return null;
      }
      if ((ref1 = typeof node) === 'string' || ref1 === 'number' || ref1 === 'boolean') {
        return node;
      }
      if (Array.isArray(node)) {
        return node.map((item) => {
          return this.dataToClass(item);
        });
      }
      // For legacy calls without frame, create minimal frame
      if ((node != null) && typeof node === 'object') {
        if (node.type != null) {
          // Already a normalized node - convert directly
          return this.solarNodeToClass(node);
        } else {
          // Solar directive without frame - limited support
          mockFrame = {
            rhs: [
              {
                value: node
              }
            ]
          };
          return this.evaluateDirective(node, mockFrame);
        }
      }
    }

  };

  module.exports = ES5Backend;

}).call(this);
