// Generated by CoffeeScript 2.7.0
(function() {
  // See [http://wiki.ecmascript.org/doku.php?id=harmony:egal](http://wiki.ecmascript.org/doku.php?id=harmony:egal).

  // Import Node.js assert functions for test framework
  var arrayEgal, diffOutput, doesNotThrow, egal, getAstExpressions, getAstRoot, ok, throws;

  ({throws, doesNotThrow, ok} = require('assert'));

  egal = function(a, b) {
    if (a === b) {
      return a !== 0 || 1 / a === 1 / b;
    } else {
      return a !== a && b !== b;
    }
  };

  // A recursive functional equivalence helper; uses egal for testing equivalence.
  arrayEgal = function(a, b) {
    var el, idx, j, len;
    if (egal(a, b)) {
      return true;
    } else if (a instanceof Array && b instanceof Array) {
      if (a.length !== b.length) {
        return false;
      }
      for (idx = j = 0, len = a.length; j < len; idx = ++j) {
        el = a[idx];
        if (!arrayEgal(el, b[idx])) {
          return false;
        }
      }
      return true;
    }
  };

  diffOutput = function(expectedOutput, actualOutput) {
    var actualOutputLines, expectedOutputLines, i, j, len, line;
    expectedOutputLines = expectedOutput.split('\n');
    actualOutputLines = actualOutput.split('\n');
    for (i = j = 0, len = actualOutputLines.length; j < len; i = ++j) {
      line = actualOutputLines[i];
      if (line !== expectedOutputLines[i]) {
        actualOutputLines[i] = `${yellow}${line}${reset}`;
      }
    }
    return `Expected generated JavaScript to be:
${reset}${expectedOutput}${red}
  but instead it was:
${reset}${actualOutputLines.join('\n')}${red}`;
  };

  exports.eq = function(a, b, msg) {
    return ok(egal(a, b), msg || `Expected ${reset}${a}${red} to equal ${reset}${b}${red}`);
  };

  exports.arrayEq = function(a, b, msg) {
    return ok(arrayEgal(a, b), msg || `Expected ${reset}${a}${red} to deep equal ${reset}${b}${red}`);
  };

  exports.eqJS = function(input, expectedOutput, msg) {
    var actualOutput;
    actualOutput = CoffeeScript.compile(input, {
      bare: true
    }).replace(/^\s+|\s+$/g, ''); // Trim leading/trailing whitespace.
    return ok(egal(expectedOutput, actualOutput), msg || diffOutput(expectedOutput, actualOutput));
  };

  exports.isWindows = function() {
    return process.platform === 'win32';
  };

  exports.inspect = function(obj) {
    if (global.testingBrowser) {
      return JSON.stringify(obj, null, 2);
    } else {
      return require('util').inspect(obj, {
        depth: 10,
        colors: process.env.NODE_DISABLE_COLORS ? false : true
      });
    }
  };

  // Helpers to get AST nodes for a string of code.
  exports.getAstRoot = getAstRoot = function(code) {
    return CoffeeScript.compile(code, {
      ast: true
    });
  };

  // The root node is always a `File` node, so for brevity in the tests return its
  // children from `program.body`.
  getAstExpressions = function(code) {
    var ast;
    ast = getAstRoot(code);
    return ast.program.body;
  };

  // Many tests want just the root node.
  exports.getAstExpression = function(code) {
    var expressionStatementAst;
    expressionStatementAst = getAstExpressions(code)[0];
    ok(expressionStatementAst.type === 'ExpressionStatement', 'Expected ExpressionStatement AST wrapper');
    return expressionStatementAst.expression;
  };

  exports.getAstStatement = function(code) {
    var statement;
    statement = getAstExpressions(code)[0];
    ok(statement.type !== 'ExpressionStatement', "Didn't expect ExpressionStatement AST wrapper");
    return statement;
  };

  exports.getAstExpressionOrStatement = function(code) {
    var expressionAst;
    expressionAst = getAstExpressions(code)[0];
    if (expressionAst.type !== 'ExpressionStatement') {
      return expressionAst;
    }
    return expressionAst.expression;
  };

  exports.throwsCompileError = function(code, compileOpts, ...args) {
    throws(function() {
      return CoffeeScript.compile(code, compileOpts, ...args);
    });
    return throws(function() {
      return CoffeeScript.compile(code, Object.assign({}, compileOpts != null ? compileOpts : {}, {
        ast: true
      }), ...args);
    });
  };

  exports.doesNotThrowCompileError = function(code, compileOpts, ...args) {
    doesNotThrow(function() {
      return CoffeeScript.compile(code, compileOpts, ...args);
    });
    return doesNotThrow(function() {
      return CoffeeScript.compile(code, Object.assign({}, compileOpts != null ? compileOpts : {}, {
        ast: true
      }), ...args);
    });
  };

  // Export Node.js assert functions for global test framework access
  exports.throws = throws;

  exports.doesNotThrow = doesNotThrow;

  exports.ok = ok;

}).call(this);
