// Generated by CoffeeScript 2.7.0
(function() {
  // Test advanced and complex patterns
  var splice = [].splice;

  test("destructuring in for loops", function() {
    var a, b, j, len, pairs, sums;
    pairs = [
      {
        a: 1,
        b: 2
      },
      {
        a: 3,
        b: 4
      }
    ];
    sums = [];
    for (j = 0, len = pairs.length; j < len; j++) {
      ({a, b} = pairs[j]);
      sums.push(a + b);
    }
    eq(sums[0], 3);
    return eq(sums[1], 7);
  });

  test("destructuring with splats", function() {
    var first, last, middle, ref;
    ref = [1, 2, 3, 4, 5], [first, ...middle] = ref, [last] = splice.call(middle, -1);
    eq(first, 1);
    eq(last, 5);
    return eq(middle.length, 3);
  });

  test("complex destructuring", function() {
    var data, firstName, score1, score2;
    data = {
      users: [
        {
          name: "Alice",
          scores: [90,
        85]
        },
        {
          name: "Bob",
          scores: [88,
        92]
        }
      ]
    };
    ({
      users: [
        {
          name: firstName,
          scores: [score1]
        },
        {
          scores: [,
        score2]
        }
      ]
    } = data);
    eq(firstName, "Alice");
    eq(score1, 90);
    return eq(score2, 92);
  });

  test("method chaining", function() {
    var Chain, result;
    Chain = class Chain {
      constructor(value1 = 0) {
        this.value = value1;
      }

      add(n) {
        this.value += n;
        return this;
      }

      multiply(n) {
        this.value *= n;
        return this;
      }

      get() {
        return this.value;
      }

    };
    result = new Chain().add(5).multiply(2).add(3).get();
    return eq(result, 13);
  });

  test("nested ternary operators", function() {
    var grade;
    grade = function(score) {
      if (score >= 90) {
        return "A";
      } else if (score >= 80) {
        return "B";
      } else if (score >= 70) {
        return "C";
      } else {
        return "F";
      }
    };
    eq(grade(95), "A");
    eq(grade(85), "B");
    eq(grade(75), "C");
    return eq(grade(65), "F");
  });

  test("complex array slicing", function() {
    var arr, everyOther, i;
    arr = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9];
    // Every other element
    everyOther = (function() {
      var j, ref, results;
      results = [];
      for (i = j = 0, ref = arr.length; j < ref; i = j += 2) {
        results.push(arr[i]);
      }
      return results;
    })();
    eq(everyOther.length, 5);
    eq(everyOther[0], 0);
    return eq(everyOther[4], 8);
  });

  test("guard clauses in comprehensions", function() {
    var n, numbers, result;
    numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10];
    result = (function() {
      var j, len, results;
      results = [];
      for (j = 0, len = numbers.length; j < len; j++) {
        n = numbers[j];
        if (n % 2 === 0 && n > 4) {
          results.push(n * 2);
        }
      }
      return results;
    })();
    eq(result.length, 3);
    eq(result[0], 12); // 6 * 2
    return eq(result[2], 20); // 10 * 2
  });

  test("object comprehension with computed keys", function() {
    var i, j, keys, obj, ref, values;
    keys = ['a', 'b', 'c'];
    values = [1, 2, 3];
    obj = {};
    for (i = j = 0, ref = keys.length; (0 <= ref ? j < ref : j > ref); i = 0 <= ref ? ++j : --j) {
      obj[keys[i]] = values[i];
    }
    eq(obj.a, 1);
    eq(obj.b, 2);
    return eq(obj.c, 3);
  });

  test("switch with multiple values", function() {
    var classify;
    classify = function(value) {
      switch (value) {
        case 1:
        case 2:
        case 3:
          return "small";
        case 4:
        case 5:
        case 6:
          return "medium";
        case 7:
        case 8:
        case 9:
          return "large";
        default:
          return "unknown";
      }
    };
    eq(classify(2), "small");
    eq(classify(5), "medium");
    return eq(classify(8), "large");
  });

  test("switch without value (when-then)", function() {
    var categorize;
    categorize = function(age) {
      switch (false) {
        case !(age < 13):
          return "child";
        case !(age < 20):
          return "teen";
        case !(age < 60):
          return "adult";
        default:
          return "senior";
      }
    };
    eq(categorize(10), "child");
    eq(categorize(16), "teen");
    eq(categorize(35), "adult");
    return eq(categorize(70), "senior");
  });

  test("postfix loops", function() {
    var count, i, j, k, len, n, ref, sum;
    count = 0;
    for (i = j = 1; j <= 5; i = ++j) {
      count++;
    }
    eq(count, 5);
    sum = 0;
    ref = [1, 2, 3];
    for (k = 0, len = ref.length; k < len; k++) {
      n = ref[k];
      sum += n;
    }
    return eq(sum, 6);
  });

  test("loop with guard and index", function() {
    var arr, idx, j, len, result, val;
    arr = ['a', 'b', 'c', 'd', 'e'];
    result = [];
    for (idx = j = 0, len = arr.length; j < len; idx = ++j) {
      val = arr[idx];
      if (idx % 2 === 0) {
        result.push(`${idx}:${val}`);
      }
    }
    eq(result.length, 3);
    eq(result[0], "0:a");
    return eq(result[2], "4:e");
  });

  test("range with variables", function() {
    var end, range, start;
    start = 5;
    end = 10;
    range = (function() {
      var results = [];
      for (var j = start; start <= end ? j <= end : j >= end; start <= end ? j++ : j--){ results.push(j); }
      return results;
    }).apply(this);
    eq(range.length, 6);
    eq(range[0], 5);
    return eq(range[5], 10);
  });

  test("negative indices", function() {
    var arr;
    // CoffeeScript compiles negative indices to arr[arr.length - n]
    arr = [1, 2, 3, 4, 5];
    // These would work in CoffeeScript source but not in runtime JS
    // eq arr[-1], 5
    // eq arr[-2], 4
    // Instead use slice for negative indexing
    eq(arr.slice(-1)[0], 5);
    eq(arr.slice(-2)[0], 4);
    return eq(arr.slice(-5)[0], 1);
  });

  test("string multiplication pattern", function() {
    var repeat;
    // Repeat string pattern
    repeat = function(str, n) {
      var i, j, ref, result;
      result = "";
      for (i = j = 1, ref = n; (1 <= ref ? j <= ref : j >= ref); i = 1 <= ref ? ++j : --j) {
        result += str;
      }
      return result;
    };
    return eq(repeat("ab", 3), "ababab");
  });

  test("default parameters with destructuring", function() {
    var fn;
    fn = function({a = 1, b = 2} = {}) {
      return a + b;
    };
    eq(fn(), 3);
    eq(fn({
      a: 5
    }), 7);
    eq(fn({
      b: 10
    }), 11);
    return eq(fn({
      a: 5,
      b: 5
    }), 10);
  });

  test("rest parameters in destructuring", function() {
    var fn, result;
    fn = function([first, second, ...rest]) {
      return {first, second, rest};
    };
    result = fn([1, 2, 3, 4, 5]);
    eq(result.first, 1);
    eq(result.second, 2);
    return eq(result.rest.length, 3);
  });

  test("complex boolean expressions", function() {
    var a, b, c, result;
    a = true;
    b = false;
    c = true;
    result = a && !b && c;
    ok(result);
    result = a || b && c;
    ok(result);
    result = !(a && b) || c;
    return ok(result);
  });

  test("property existence checks", function() {
    var obj;
    obj = {
      a: null,
      b: void 0,
      c: 0,
      d: false,
      e: ""
    };
    ok('a' in obj);
    ok('b' in obj);
    ok('c' in obj);
    ok('d' in obj);
    ok('e' in obj);
    return ok(!('f' in obj));
  });

}).call(this);
