// Generated by CoffeeScript 2.7.0
(function() {
  test("switch with multiple values", function() {
    var classify;
    classify = function(value) {
      switch (value) {
        case 1:
        case 2:
        case 3:
          return "small";
        case 4:
        case 5:
        case 6:
          return "medium";
        case 7:
        case 8:
        case 9:
          return "large";
        default:
          return "unknown";
      }
    };
    eq(classify(2), "small");
    eq(classify(5), "medium");
    return eq(classify(8), "large");
  });

  test("switch without value (when-then)", function() {
    var categorize;
    categorize = function(age) {
      switch (false) {
        case !(age < 13):
          return "child";
        case !(age < 20):
          return "teen";
        case !(age < 60):
          return "adult";
        default:
          return "senior";
      }
    };
    eq(categorize(10), "child");
    eq(categorize(16), "teen");
    eq(categorize(35), "adult");
    return eq(categorize(70), "senior");
  });

  test("postfix loops", function() {
    var count, i, j, k, len, n, ref, sum;
    count = 0;
    for (i = j = 1; j <= 5; i = ++j) {
      count++;
    }
    eq(count, 5);
    sum = 0;
    ref = [1, 2, 3];
    for (k = 0, len = ref.length; k < len; k++) {
      n = ref[k];
      sum += n;
    }
    return eq(sum, 6);
  });

  test("loop with guard and index", function() {
    var arr, idx, j, len, result, val;
    arr = ['a', 'b', 'c', 'd', 'e'];
    result = [];
    for (idx = j = 0, len = arr.length; j < len; idx = ++j) {
      val = arr[idx];
      if (idx % 2 === 0) {
        result.push(`${idx}:${val}`);
      }
    }
    eq(result.length, 3);
    eq(result[0], "0:a");
    return eq(result[2], "4:e");
  });

  test("range with variables", function() {
    var end, range, start;
    start = 5;
    end = 10;
    range = (function() {
      var results = [];
      for (var j = start; start <= end ? j <= end : j >= end; start <= end ? j++ : j--){ results.push(j); }
      return results;
    }).apply(this);
    eq(range.length, 6);
    eq(range[0], 5);
    return eq(range[5], 10);
  });

  test("negative indices", function() {
    var arr;
    // CoffeeScript compiles negative indices to arr[arr.length - n]
    arr = [1, 2, 3, 4, 5];
    // These would work in CoffeeScript source but not in runtime JS
    // eq arr[-1], 5
    // eq arr[-2], 4
    // Instead use slice for negative indexing
    eq(arr.slice(-1)[0], 5);
    eq(arr.slice(-2)[0], 4);
    return eq(arr.slice(-5)[0], 1);
  });

  test("string multiplication pattern", function() {});

  // Repeat string pattern

}).call(this);
