// Generated by CoffeeScript 2.7.0
(function() {
  // Test advanced and complex patterns
  var splice = [].splice;

  test("destructuring in for loops", function() {
    var a, b, j, len, pairs, sums;
    pairs = [
      {
        a: 1,
        b: 2
      },
      {
        a: 3,
        b: 4
      }
    ];
    sums = [];
    for (j = 0, len = pairs.length; j < len; j++) {
      ({a, b} = pairs[j]);
      sums.push(a + b);
    }
    eq(sums[0], 3);
    return eq(sums[1], 7);
  });

  test("destructuring with splats", function() {
    var first, last, middle, ref;
    ref = [1, 2, 3, 4, 5], [first, ...middle] = ref, [last] = splice.call(middle, -1);
    eq(first, 1);
    eq(last, 5);
    return eq(middle.length, 3);
  });

  test("complex destructuring", function() {
    var data, firstName, score1, score2;
    data = {
      users: [
        {
          name: "Alice",
          scores: [90,
        85]
        },
        {
          name: "Bob",
          scores: [88,
        92]
        }
      ]
    };
    ({
      users: [
        {
          name: firstName,
          scores: [score1]
        },
        {
          scores: [,
        score2]
        }
      ]
    } = data);
    eq(firstName, "Alice");
    eq(score1, 90);
    return eq(score2, 92);
  });

  test("method chaining", function() {
    var Chain, result;
    Chain = class Chain {
      constructor(value = 0) {
        this.value = value;
      }

      add(n) {
        this.value += n;
        return this;
      }

      multiply(n) {
        this.value *= n;
        return this;
      }

      get() {
        return this.value;
      }

    };
    result = new Chain().add(5).multiply(2).add(3).get();
    return eq(result, 13);
  });

  test("nested ternary operators", function() {
    var grade;
    grade = function(score) {
      if (score >= 90) {
        return "A";
      } else if (score >= 80) {
        return "B";
      } else if (score >= 70) {
        return "C";
      } else {
        return "F";
      }
    };
    eq(grade(95), "A");
    eq(grade(85), "B");
    eq(grade(75), "C");
    return eq(grade(65), "F");
  });

  test("complex array slicing", function() {
    var arr, everyOther, i;
    arr = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9];
    // Every other element
    everyOther = (function() {
      var j, ref, results;
      results = [];
      for (i = j = 0, ref = arr.length; j < ref; i = j += 2) {
        results.push(arr[i]);
      }
      return results;
    })();
    eq(everyOther.length, 5);
    eq(everyOther[0], 0);
    return eq(everyOther[4], 8);
  });

  test("guard clauses in comprehensions", function() {
    var n, numbers, result;
    numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10];
    result = (function() {
      var j, len, results;
      results = [];
      for (j = 0, len = numbers.length; j < len; j++) {
        n = numbers[j];
        if (n % 2 === 0 && n > 4) {
          results.push(n * 2);
        }
      }
      return results;
    })();
    eq(result.length, 3);
    eq(result[0], 12); // 6 * 2
    return eq(result[2], 20); // 10 * 2
  });

  test("object comprehension with computed keys", function() {
    var i, j, keys, obj, ref, values;
    keys = ['a', 'b', 'c'];
    values = [1, 2, 3];
    obj = {};
    for (i = j = 0, ref = keys.length; (0 <= ref ? j < ref : j > ref); i = 0 <= ref ? ++j : --j) {
      obj[keys[i]] = values[i];
    }
    eq(obj.a, 1);
    eq(obj.b, 2);
    return eq(obj.c, 3);
  });

}).call(this);
