// Generated by CoffeeScript 2.7.0
(function() {
  // The `coffee` utility. Handles command-line compilation of CoffeeScript
  // into various forms: saved into `.js` files or printed to stdout
  // or recompiled every time the source is saved,
  // printed as a token stream or as the syntax tree, or launch an
  // interactive REPL.

  // External dependencies.
  var BANNER, CS3DebugBackend, CoffeeScript, ES5Backend, EventEmitter, Lexer, SWITCHES, buildCSOptionParser, compileCS3, compileJoin, compileOptions, compilePath, compileScript, compileStdio, directivesCS3, err, exec, findDirectoryIndex, forkNode, fs, helpers, hidden, joinTimeout, makePrelude, mkdirp, notSources, optionParser, optparse, opts, outputPath, parseOptions, parserCS3, path, printLine, printTokens, printWarn, removeSource, removeSourceDir, silentUnlink, sourceCode, sources, spawn, timeLog, toYAML, tokensCS3, usage, useWinPathSep, version, wait, watch, watchDir, watchedDirs, writeJs,
    indexOf = [].indexOf;

  fs = require('fs');

  path = require('path');

  helpers = require('./helpers');

  optparse = require('./optparse');

  CoffeeScript = require('./');

  ({spawn, exec} = require('child_process'));

  ({EventEmitter} = require('events'));

  // CS3 plumbing (lexer/parser/backends) for new CLI switches
  ({Lexer} = require('./lexer'));

  try {
    parserCS3 = require('./parser-cs3');
  } catch (error) {
    err = error;
    parserCS3 = null;
  }

  try {
    ES5Backend = require('../backends/es5/index');
  } catch (error) {
    err = error;
    ES5Backend = null;
  }

  CS3DebugBackend = class CS3DebugBackend {
    constructor(options1 = {}) {
      this.options = options1;
      this.trace = this.options['cs3-trace'];
      this.reductions = [];
      this.root = null;
    }

    reduce(ruleName, directive, frame) {
      var node, ref, ref1;
      // Log all reductions if tracing is enabled
      if (this.trace) {
        console.error(`[CS3 Reduce] ${ruleName}`);
        if (ruleName === 'Root') {
          console.error(`[CS3 Root directive] ${JSON.stringify(directive)}`);
          console.error(`[CS3 Root frame.rhs] length=${(ref = frame.rhs) != null ? ref.length : void 0}, slot0=${JSON.stringify((ref1 = frame.rhs) != null ? ref1[0] : void 0)}`);
        }
      }
      // Evaluate the directive to get the node
      node = this.evaluate(directive, frame, ruleName);
      // Track all reductions
      this.reductions.push({
        rule: ruleName,
        node
      });
      // Capture the Root node when we see it
      if (ruleName === 'Root' || (node != null ? node.type : void 0) === 'Root') {
        this.root = node;
        if (this.trace) {
          console.error(`[CS3 Found Root] type=${node != null ? node.type : void 0}, node=${JSON.stringify(node)}`);
        }
      }
      // Return the node to the parser
      return node;
    }

    evaluate(d, fr, rn = null) {
      var accessor, arr, arrays, bodyNode, elseBlock, ifBlock, item, items, j, k, len, len1, len2, loopNode, m, mapped, n, o, op, out, propName, propValue, ref, ref1, ref2, ref3, ref4, ref5, sourceNode, t, target, v, val;
      if (typeof d === 'number') {
        return (ref = fr.rhs[d - 1]) != null ? ref.value : void 0;
      }
      if (((ref1 = typeof d) === 'string' || ref1 === 'boolean' || ref1 === 'undefined') || d === null) {
        return d;
      }
      if (Array.isArray(d)) {
        return d.map((x) => {
          return this.evaluate(x, fr, rn);
        });
      }
      if ((d != null) && typeof d === 'object') {
        if (d.$use != null) {
          v = typeof d.$use === 'number' ? (ref2 = fr.rhs[d.$use - 1]) != null ? ref2.value : void 0 : d.$use;
          if (d.method != null) {
            return v != null ? (ref3 = v[d.method]) != null ? ref3.apply(v, (d.args || []).map((a) => {
              return this.evaluate(a, fr);
            })) : void 0 : void 0;
          } else if (d.prop != null) {
            return v != null ? v[d.prop] : void 0;
          } else {
            return v;
          }
        }
        if (d.$ast != null) {
          t = d.$ast === '@' ? rn : d.$ast;
          out = {
            type: t
          };
          for (k in d) {
            v = d[k];
            if (k !== '$ast' && k !== '$pos') {
              out[k] = this.evaluate(v, fr, rn);
            }
          }
          if (this.trace && rn === 'Root') {
            console.error(`[CS3 Root eval] type=${t}, out=${JSON.stringify(out)}`);
          }
          return out;
        }
        if (d.$ary != null) {
          arr = Array.isArray(d.$ary) ? d.$ary : [d.$ary];
          return arr.map((x) => {
            return this.evaluate(x, fr, rn);
          });
        }
        if (d.$ops != null) {
          // Handle $ops directives - these are operations on arrays/values/properties
          op = d.$ops;
          // Array operations
          if (op === 'array') {
            if (d.append != null) {
              // append: [target, ...items] - append items to target array
              items = d.append.map((x) => {
                return this.evaluate(x, fr, rn);
              });
              target = items[0] || [];
              ref4 = items.slice(1);
              for (j = 0, len = ref4.length; j < len; j++) {
                item = ref4[j];
                if (item != null) {
                  target.push(item);
                }
              }
              return target;
            }
            if (d.gather != null) {
              // gather: [target, ...arrays] - gather arrays into target
              arrays = d.gather.map((x) => {
                return this.evaluate(x, fr, rn);
              });
              target = arrays[0] || [];
              ref5 = arrays.slice(1);
              for (m = 0, len1 = ref5.length; m < len1; m++) {
                arr = ref5[m];
                if (Array.isArray(arr)) {
                  for (n = 0, len2 = arr.length; n < len2; n++) {
                    item = arr[n];
                    target.push(item);
                  }
                } else if (arr != null) {
                  target.push(arr);
                }
              }
              return target;
            }
            return [];
          }
          // Value operations - add accessors to a value
          if (op === 'value') {
            if (d.add != null) {
              // add: [value, accessor] - add accessor to value
              mapped = d.add.map((x) => {
                return this.evaluate(x, fr, rn);
              });
              val = mapped[0];
              accessor = mapped[1];
              if ((val != null) && typeof val === 'object') {
                if (val.properties == null) {
                  val.properties = [];
                }
                if (accessor != null) {
                  val.properties.push(accessor);
                }
                if (val.type === 'Value' && (val.val != null)) {
                  // Also set bareLiteral for proper AST structure
                  if (val.bareLiteral == null) {
                    val.bareLiteral = val.val;
                  }
                }
              }
              return val;
            }
            return null;
          }
          // Property operations - set properties on objects
          if (op === 'prop') {
            if (d.set != null) {
              // set: {target, property, value} - set property on target
              target = this.evaluate(d.set.target, fr, rn);
              propName = d.set.property;
              propValue = this.evaluate(d.set.value, fr, rn);
              if ((target != null) && typeof target === 'object') {
                target[propName] = propValue;
              }
              return target;
            }
            return null;
          }
          // Loop operations - add body/source to loops
          if (op === 'loop') {
            if (d.addBody != null) {
              // addBody: [loop, body] - add body to loop
              mapped = d.addBody.map((x) => {
                var num;
                if (typeof x === 'string' && x.startsWith('Body $')) {
                  // Handle special Body $N syntax
                  num = parseInt(x.replace('Body $', ''));
                  return {
                    type: 'Body',
                    expressions: [this.evaluate(num, fr, rn)]
                  };
                } else {
                  return this.evaluate(x, fr, rn);
                }
              });
              loopNode = mapped[0];
              bodyNode = mapped[1];
              if ((loopNode != null) && typeof loopNode === 'object') {
                // Handle array body (for postfix loops)
                if (Array.isArray(bodyNode)) {
                  loopNode.body = {
                    type: 'Body',
                    expressions: bodyNode
                  };
                } else {
                  loopNode.body = bodyNode;
                }
              }
              return loopNode;
            }
            if (d.addSource != null) {
              // addSource: [loop, source] - add source to for loop
              mapped = d.addSource.map((x) => {
                return this.evaluate(x, fr, rn);
              });
              loopNode = mapped[0];
              sourceNode = mapped[1];
              if ((loopNode != null) && (sourceNode != null) && typeof loopNode === 'object') {
// Merge source properties into loop
                for (k in sourceNode) {
                  v = sourceNode[k];
                  if (k !== 'type') {
                    loopNode[k] = v;
                  }
                }
              }
              return loopNode;
            }
            return null;
          }
          // If operations - add else branches
          if (op === 'if') {
            if (d.addElse != null) {
              // addElse: [ifBlock, elseBlock] - add else to if
              mapped = d.addElse.map((x) => {
                return this.evaluate(x, fr, rn);
              });
              ifBlock = mapped[0];
              elseBlock = mapped[1];
              if ((ifBlock != null) && typeof ifBlock === 'object') {
                ifBlock.elseBody = elseBlock;
              }
              return ifBlock;
            }
            return null;
          }
          return {
            // Unknown operation - return as-is for debugging
            $ops: op,
            data: d
          };
        }
        // Plain object - evaluate all non-directive properties
        o = {};
        for (k in d) {
          v = d[k];
          if (!k.startsWith('$')) {
            o[k] = this.evaluate(v, fr, rn);
          }
        }
        return o;
      }
      return d;
    }

  };

  // Format converters for AST output
  toYAML = function(obj, indent = 0) {
    var escaped, item, itemStr, j, key, keys, len, len1, lines, m, ref, spaces, value;
    if (obj === null || obj === void 0) {
      return 'null';
    }
    if ((ref = typeof obj) === 'string' || ref === 'number' || ref === 'boolean') {
      return String(obj);
    }
    spaces = '  '.repeat(indent);
    if (Array.isArray(obj)) {
      if (obj.length === 0) {
        return '[]';
      }
      lines = [];
      for (j = 0, len = obj.length; j < len; j++) {
        item = obj[j];
        itemStr = toYAML(item, indent + 1);
        if (itemStr.includes('\n') || typeof item === 'object') {
          lines.push(`${spaces}-`);
          lines.push(toYAML(item, indent + 1).split('\n').map(function(l) {
            return `  ${l}`;
          }).join('\n'));
        } else {
          lines.push(`${spaces}- ${itemStr}`);
        }
      }
      return lines.join('\n');
    }
    if (typeof obj === 'object') {
      keys = Object.keys(obj);
      if (keys.length === 0) {
        return '{}';
      }
      lines = [];
      for (m = 0, len1 = keys.length; m < len1; m++) {
        key = keys[m];
        value = obj[key];
        if (value === null || value === void 0) {
          lines.push(`${spaces}${key}: null`);
        } else if (typeof value === 'object') {
          lines.push(`${spaces}${key}:`);
          lines.push(toYAML(value, indent + 1).split('\n').map(function(l) {
            return `  ${l}`;
          }).join('\n'));
        } else if (typeof value === 'string') {
          // Quote strings that might be ambiguous in YAML
          escaped = value.replace(/"/g, '\\"');
          lines.push(`${spaces}${key}: \"${escaped}\"`);
        } else {
          lines.push(`${spaces}${key}: ${value}`);
        }
      }
      return lines.join('\n');
    }
    return String(obj);
  };

  tokensCS3 = function(code, options = {}) {
    var lexer;
    lexer = new Lexer();
    return lexer.tokenize(code, options);
  };

  directivesCS3 = function(code, options = {}) {
    var backend, body, i, j, lastReduction, len, lexIface, node, parserResult, red, ref, ref1, root, rule, tokens;
    if (parserCS3 == null) {
      throw new Error('CS3 parser not available');
    }
    tokens = tokensCS3(code, options);
    i = 0;
    lexIface = {
      lex: function() {
        var t;
        if (i >= tokens.length) {
          return 1;
        }
        t = tokens[i++];
        this.yytext = t[1];
        this.yylloc = t[2];
        this.yylineno = t[2] ? t[2].first_line : 0;
        this.yyleng = String(this.yytext).length;
        return parserCS3.parser.symbolIds[t[0]] || parserCS3.parser.symbolIds[t[1]];
      },
      setInput: function() {
        return i = 0;
      },
      upcomingInput: function() {
        return '';
      }
    };
    parserCS3.parser.lexer = lexIface;
    backend = new CS3DebugBackend(options);
    parserCS3.parser.yy = {backend};
    // Parse the input
    parserResult = parserCS3.parse();
    // The parser should return the final AST value
    // If it's an object with a type, that's our Root
    if ((parserResult != null) && typeof parserResult === 'object') {
      if (options['cs3-trace']) {
        console.error(`[CS3 Parser returned] type=${parserResult.type}`);
      }
      return parserResult;
    }
    // If the backend captured a Root node, return it
    if (backend.root != null) {
      if (options['cs3-trace']) {
        console.error(`[CS3 Backend Root] type=${backend.root.type}`);
      }
      return backend.root;
    }
    // Otherwise, try to synthesize a Root from the reductions
    body = [];
    ref = backend.reductions;
    for (j = 0, len = ref.length; j < len; j++) {
      red = ref[j];
      ({rule, node} = red);
      if (node == null) {
        // Skip null/undefined nodes
        continue;
      }
      // For top-level rules, collect the nodes
      if ((rule === 'Body' || rule === 'Line' || rule === 'Statement' || rule === 'Expression') && ((node != null ? node.type : void 0) != null)) {
        body.push(node);
      }
    }
    // If we have collected some nodes, wrap them in a Root
    if (body.length > 0) {
      root = {
        type: 'Root',
        body
      };
      if (options['cs3-trace']) {
        console.error(`[CS3 Synthesized Root] with ${body.length} nodes`);
      }
      return root;
    }
    // As a last resort, see if the last reduction is meaningful
    lastReduction = backend.reductions[backend.reductions.length - 1];
    if ((lastReduction != null ? (ref1 = lastReduction.node) != null ? ref1.type : void 0 : void 0) != null) {
      if (options['cs3-trace']) {
        console.error(`[CS3 Last Reduction] rule=${lastReduction.rule}, type=${lastReduction.node.type}`);
      }
      return lastReduction.node;
    }
    // Return null if we couldn't find anything
    if (options['cs3-trace']) {
      console.error("[CS3 No Root found]");
    }
    return null;
  };

  compileCS3 = function(code, options = {}) {
    var ast, backend, i, lexIface, result, tokens;
    if (!((ES5Backend != null) && (parserCS3 != null))) {
      throw new Error('CS3 backend not available');
    }
    tokens = tokensCS3(code, options);
    i = 0;
    lexIface = {
      lex: function() {
        var t;
        if (i >= tokens.length) {
          return 1;
        }
        t = tokens[i++];
        this.yytext = t[1];
        this.yylloc = t[2];
        this.yylineno = t[2] ? t[2].first_line : 0;
        this.yyleng = String(this.yytext).length;
        return parserCS3.parser.symbolIds[t[0]] || parserCS3.parser.symbolIds[t[1]];
      },
      setInput: function() {
        return i = 0;
      },
      upcomingInput: function() {
        return '';
      }
    };
    backend = new ES5Backend(options);
    parserCS3.parser.lexer = lexIface;
    parserCS3.parser.yy = {backend};
    ast = parserCS3.parse();
    // Generate JavaScript code from the AST
    result = (ast != null ? ast.compile : void 0) ? ast.compile(backend.compileOptions) : (backend != null ? backend.generate : void 0) ? backend.generate(ast) : '';
    return result || '';
  };

  useWinPathSep = path.sep === '\\';

  // Allow CoffeeScript to emit Node.js events.
  helpers.extend(CoffeeScript, new EventEmitter());

  printLine = function(line) {
    return process.stdout.write(line + '\n');
  };

  printWarn = function(line) {
    return process.stderr.write(line + '\n');
  };

  hidden = function(file) {
    return /^\.|~$/.test(file);
  };

  // The help banner that is printed in conjunction with `-h`/`--help`.
  BANNER = `Usage: coffee [options] path/to/script.coffee [args]

If called without options, \`coffee\` will run your script.`;

  // The list of all the valid option flags that `coffee` knows how to handle.
  SWITCHES = [['--ast', 'generate an abstract syntax tree of nodes'], ['-b', '--bare', 'compile without a top-level function wrapper'], ['-c', '--compile', 'compile to JavaScript and save as .js files'], ['--es6', 'compile to ES6 JavaScript instead of ES5'], ['-e', '--eval', 'pass a string from the command line as input'], ['-h', '--help', 'display this help message'], ['-i', '--interactive', 'run an interactive CoffeeScript REPL'], ['-j', '--join [FILE]', 'concatenate the source CoffeeScript before compiling'], ['-l', '--literate', 'treat stdio as literate style coffeescript'], ['-m', '--map', 'generate source map and save as .js.map files'], ['-M', '--inline-map', 'generate source map and include it directly in output'], ['-n', '--nodes', 'print out the parse tree that the parser produces'], ['--nodejs [ARGS]', 'pass options directly to the "node" binary'], ['--no-header', 'suppress the "Generated by" header'], ['-o', '--output [PATH]', 'set the output path or path/filename for compiled JavaScript'], ['-p', '--print', 'print out the compiled JavaScript'], ['-r', '--require [MODULE*]', 'require the given module before eval or REPL'], ['-s', '--stdio', 'listen for and compile scripts over stdio'], ['-t', '--transpile', 'pipe generated JavaScript through Babel'], ['--tokens', 'print out the tokens that the lexer/rewriter produce'], ['--cs3-tokens', 'print CS3 lexer tokens (via cs3 lexer)'], ['--cs3-ast', 'print CS3 AST data nodes (Solar directives)'], ['--cs3-trace', 'enable debug tracing for CS3 parser reductions'], ['--format [FORMAT]', 'output format for --cs3-ast (json, yaml)'], ['--cs3', 'compile with CS3 pipeline'], ['-v', '--version', 'display the version number'], ['-w', '--watch', 'watch scripts for changes and rerun commands']];

  // Top-level objects shared by all the functions.
  opts = {};

  sources = [];

  sourceCode = [];

  notSources = {};

  watchedDirs = {};

  optionParser = null;

  exports.buildCSOptionParser = buildCSOptionParser = function() {
    return new optparse.OptionParser(SWITCHES, BANNER);
  };

  // Run `coffee` by parsing passed options and determining what action to take.
  // Many flags cause us to divert before compiling anything. Flags passed after
  // `--` will be passed verbatim to your script as arguments in `process.argv`
  exports.run = function() {
    var j, len, literals, outputBasename, ref, replCliOpts, results, source;
    optionParser = buildCSOptionParser();
    try {
      parseOptions();
    } catch (error) {
      err = error;
      console.error(`option parsing error: ${err.message}`);
      process.exit(1);
    }
    if ((!opts.doubleDashed) && (opts.arguments[1] === '--')) {
      printWarn(`coffee was invoked with '--' as the second positional argument, which is
now deprecated. To pass '--' as an argument to a script to run, put an
additional '--' before the path to your script.

'--' will be removed from the argument list.`);
      printWarn(`The positional arguments were: ${JSON.stringify(opts.arguments)}`);
      opts.arguments = [opts.arguments[0]].concat(opts.arguments.slice(2));
    }
    // Make the REPL *CLI* use the global context so as to (a) be consistent with the
    // `node` REPL CLI and, therefore, (b) make packages that modify native prototypes
    // (such as 'colors' and 'sugar') work as expected.
    replCliOpts = {
      useGlobal: true
    };
    if (opts.require) {
      opts.prelude = makePrelude(opts.require);
    }
    replCliOpts.prelude = opts.prelude;
    replCliOpts.transpile = opts.transpile;
    if (opts.nodejs) {
      return forkNode();
    }
    if (opts.help) {
      return usage();
    }
    if (opts.version) {
      return version();
    }
    if (opts.interactive) {
      return require('./repl').start(replCliOpts);
    }
    if (opts.stdio) {
      return compileStdio();
    }
    if (opts.eval) {
      return compileScript(null, opts.arguments[0]);
    }
    if (!opts.arguments.length) {
      return require('./repl').start(replCliOpts);
    }
    literals = opts.run ? opts.arguments.splice(1) : [];
    process.argv = process.argv.slice(0, 2).concat(literals);
    process.argv[0] = 'coffee';
    if (opts.output) {
      outputBasename = path.basename(opts.output);
      if (indexOf.call(outputBasename, '.') >= 0 && (outputBasename !== '.' && outputBasename !== '..') && !helpers.ends(opts.output, path.sep)) {
        // An output filename was specified, e.g. `/dist/scripts.js`.
        opts.outputFilename = outputBasename;
        opts.outputPath = path.resolve(path.dirname(opts.output));
      } else {
        // An output path was specified, e.g. `/dist`.
        opts.outputFilename = null;
        opts.outputPath = path.resolve(opts.output);
      }
    }
    if (opts.join) {
      opts.join = path.resolve(opts.join);
      console.error(`
The --join option is deprecated and will be removed in a future version.

If for some reason it's necessary to share local variables between files,
replace...

    $ coffee --compile --join bundle.js -- a.coffee b.coffee c.coffee

with...

    $ cat a.coffee b.coffee c.coffee | coffee --compile --stdio > bundle.js
`);
    }
    ref = opts.arguments;
    results = [];
    for (j = 0, len = ref.length; j < len; j++) {
      source = ref[j];
      source = path.resolve(source);
      results.push(compilePath(source, true, source));
    }
    return results;
  };

  makePrelude = function(requires) {
    return requires.map(function(module) {
      var full, match, name;
      if (match = module.match(/^(.*)=(.*)$/)) {
        [full, name, module] = match;
      }
      name || (name = helpers.baseFileName(module, true, useWinPathSep));
      return `global['${name}'] = require('${module}')`;
    }).join(';');
  };

  // Compile a path, which could be a script or a directory. If a directory
  // is passed, recursively compile all '.coffee', '.litcoffee', and '.coffee.md'
  // extension source files in it and all subdirectories.
  compilePath = function(source, topLevel, base) {
    var code, file, files, j, len, results, stats;
    if (indexOf.call(sources, source) >= 0 || watchedDirs[source] || !topLevel && (notSources[source] || hidden(source))) {
      return;
    }
    try {
      stats = fs.statSync(source);
    } catch (error) {
      err = error;
      if (err.code === 'ENOENT') {
        console.error(`File not found: ${source}`);
        process.exit(1);
      }
      throw err;
    }
    if (stats.isDirectory()) {
      if (path.basename(source) === 'node_modules') {
        notSources[source] = true;
        return;
      }
      if (opts.run) {
        compilePath(findDirectoryIndex(source), topLevel, base);
        return;
      }
      if (opts.watch) {
        watchDir(source, base);
      }
      try {
        files = fs.readdirSync(source);
      } catch (error) {
        err = error;
        if (err.code === 'ENOENT') {
          return;
        } else {
          throw err;
        }
      }
      results = [];
      for (j = 0, len = files.length; j < len; j++) {
        file = files[j];
        results.push(compilePath(path.join(source, file), false, base));
      }
      return results;
    } else if (topLevel || helpers.isCoffee(source)) {
      sources.push(source);
      sourceCode.push(null);
      delete notSources[source];
      if (opts.watch) {
        watch(source, base);
      }
      try {
        code = fs.readFileSync(source);
      } catch (error) {
        err = error;
        if (err.code === 'ENOENT') {
          return;
        } else {
          throw err;
        }
      }
      return compileScript(source, code.toString(), base);
    } else {
      return notSources[source] = true;
    }
  };

  findDirectoryIndex = function(source) {
    var ext, index, j, len, ref;
    ref = CoffeeScript.FILE_EXTENSIONS;
    for (j = 0, len = ref.length; j < len; j++) {
      ext = ref[j];
      index = path.join(source, `index${ext}`);
      try {
        if ((fs.statSync(index)).isFile()) {
          return index;
        }
      } catch (error) {
        err = error;
        if (err.code !== 'ENOENT') {
          throw err;
        }
      }
    }
    console.error(`Missing index.coffee or index.litcoffee in ${source}`);
    return process.exit(1);
  };

  // Compile a single source script, containing the given code, according to the
  // requested options. If evaluating the script directly, set `__filename`,
  // `__dirname` and `module.filename` to be correct relative to the script's path.
  compileScript = function(file, input, base = null) {
    var ast, compiled, js, message, options, output, saveTo, task, tokens;
    options = compileOptions(file, base);
    try {
      task = {file, input, options};
      CoffeeScript.emit('compile', task);
      if (opts['cs3-tokens']) {
        tokens = tokensCS3(task.input, task.options);
        return printTokens(tokens);
      } else if (opts['cs3-ast']) {
        ast = directivesCS3(task.input, task.options);
        // Format output based on --format option
        output = (function() {
          var ref;
          switch ((ref = opts.format) != null ? ref.toLowerCase() : void 0) {
            case 'yaml':
            case 'yml':
              return toYAML(ast); // default to json
            default:
              return JSON.stringify(ast, null, 2);
          }
        })();
        return printLine(output);
      } else if (opts['cs3']) {
        js = compileCS3(task.input, task.options);
        task.output = js;
        CoffeeScript.emit('success', task);
        if (opts.print) {
          printLine(task.output.trim());
        } else if (opts.compile || opts.map) {
          saveTo = opts.outputFilename && sources.length === 1 ? path.join(opts.outputPath, opts.outputFilename) : options.jsPath;
          writeJs(base, task.file, task.output, saveTo, null); // Ensure we don't fall through to other conditions
        }
      } else if (opts.tokens) {
        return printTokens(CoffeeScript.tokens(task.input, task.options));
      } else if (opts.nodes) {
        return printLine(CoffeeScript.nodes(task.input, task.options).toString().trim());
      } else if (opts.ast) {
        compiled = CoffeeScript.compile(task.input, task.options);
        return printLine(JSON.stringify(compiled, null, 2));
      } else if (opts.run) {
        CoffeeScript.register();
        if (opts.prelude) {
          CoffeeScript.eval(opts.prelude, task.options);
        }
        return CoffeeScript.run(task.input, task.options);
      } else if (opts.join && task.file !== opts.join) {
        if (helpers.isLiterate(file)) {
          task.input = helpers.invertLiterate(task.input);
        }
        sourceCode[sources.indexOf(task.file)] = task.input;
        return compileJoin();
      } else {
        compiled = CoffeeScript.compile(task.input, task.options);
        task.output = compiled;
        if (opts.map) {
          task.output = compiled.js;
          task.sourceMap = compiled.v3SourceMap;
        }
        CoffeeScript.emit('success', task);
        if (opts.print) {
          return printLine(task.output.trim());
        } else if (opts.compile || opts.map) {
          saveTo = opts.outputFilename && sources.length === 1 ? path.join(opts.outputPath, opts.outputFilename) : options.jsPath;
          return writeJs(base, task.file, task.output, saveTo, task.sourceMap);
        }
      }
    } catch (error) {
      err = error;
      CoffeeScript.emit('failure', err, task);
      if (CoffeeScript.listeners('failure').length) {
        return;
      }
      message = (err != null ? err.stack : void 0) || `${err}`;
      if (opts.watch) {
        return printLine(message + '\x07');
      } else {
        printWarn(message);
        return process.exit(1);
      }
    }
  };

  // Attach the appropriate listeners to compile scripts incoming over **stdin**,
  // and write them back to **stdout**.
  compileStdio = function() {
    var buffers, stdin;
    if (opts.map) {
      console.error('--stdio and --map cannot be used together');
      process.exit(1);
    }
    buffers = [];
    stdin = process.openStdin();
    stdin.on('data', function(buffer) {
      if (buffer) {
        return buffers.push(buffer);
      }
    });
    return stdin.on('end', function() {
      return compileScript(null, Buffer.concat(buffers).toString());
    });
  };

  // If all of the source files are done being read, concatenate and compile
  // them together.
  joinTimeout = null;

  compileJoin = function() {
    if (!opts.join) {
      return;
    }
    if (!sourceCode.some(function(code) {
      return code === null;
    })) {
      clearTimeout(joinTimeout);
      return joinTimeout = wait(100, function() {
        return compileScript(opts.join, sourceCode.join('\n'), opts.join);
      });
    }
  };

  // Watch a source CoffeeScript file using `fs.watch`, recompiling it every
  // time the file is updated. May be used in combination with other options,
  // such as `--print`.
  watch = function(source, base) {
    var compile, compileTimeout, prevStats, rewatch, startWatcher, watchErr, watcher;
    watcher = null;
    prevStats = null;
    compileTimeout = null;
    watchErr = function(err) {
      if (err.code !== 'ENOENT') {
        throw err;
      }
      if (indexOf.call(sources, source) < 0) {
        return;
      }
      try {
        rewatch();
        return compile();
      } catch (error) {
        removeSource(source, base);
        return compileJoin();
      }
    };
    compile = function() {
      clearTimeout(compileTimeout);
      return compileTimeout = wait(25, function() {
        return fs.stat(source, function(err, stats) {
          if (err) {
            return watchErr(err);
          }
          if (prevStats && stats.size === prevStats.size && stats.mtime.getTime() === prevStats.mtime.getTime()) {
            return rewatch();
          }
          prevStats = stats;
          return fs.readFile(source, function(err, code) {
            if (err) {
              return watchErr(err);
            }
            compileScript(source, code.toString(), base);
            return rewatch();
          });
        });
      });
    };
    startWatcher = function() {
      return watcher = fs.watch(source).on('change', compile).on('error', function(err) {
        if (err.code !== 'EPERM') {
          throw err;
        }
        return removeSource(source, base);
      });
    };
    rewatch = function() {
      if (watcher != null) {
        watcher.close();
      }
      return startWatcher();
    };
    try {
      return startWatcher();
    } catch (error) {
      err = error;
      return watchErr(err);
    }
  };

  // Watch a directory of files for new additions.
  watchDir = function(source, base) {
    var readdirTimeout, startWatcher, stopWatcher, watcher;
    watcher = null;
    readdirTimeout = null;
    startWatcher = function() {
      return watcher = fs.watch(source).on('error', function(err) {
        if (err.code !== 'EPERM') {
          throw err;
        }
        return stopWatcher();
      }).on('change', function() {
        clearTimeout(readdirTimeout);
        return readdirTimeout = wait(25, function() {
          var file, files, j, len, results;
          try {
            files = fs.readdirSync(source);
          } catch (error) {
            err = error;
            if (err.code !== 'ENOENT') {
              throw err;
            }
            return stopWatcher();
          }
          results = [];
          for (j = 0, len = files.length; j < len; j++) {
            file = files[j];
            results.push(compilePath(path.join(source, file), false, base));
          }
          return results;
        });
      });
    };
    stopWatcher = function() {
      watcher.close();
      return removeSourceDir(source, base);
    };
    watchedDirs[source] = true;
    try {
      return startWatcher();
    } catch (error) {
      err = error;
      if (err.code !== 'ENOENT') {
        throw err;
      }
    }
  };

  removeSourceDir = function(source, base) {
    var file, j, len, sourcesChanged;
    delete watchedDirs[source];
    sourcesChanged = false;
    for (j = 0, len = sources.length; j < len; j++) {
      file = sources[j];
      if (!(source === path.dirname(file))) {
        continue;
      }
      removeSource(file, base);
      sourcesChanged = true;
    }
    if (sourcesChanged) {
      return compileJoin();
    }
  };

  // Remove a file from our source list, and source code cache. Optionally remove
  // the compiled JS version as well.
  removeSource = function(source, base) {
    var index;
    index = sources.indexOf(source);
    sources.splice(index, 1);
    sourceCode.splice(index, 1);
    if (!opts.join) {
      silentUnlink(outputPath(source, base));
      silentUnlink(outputPath(source, base, '.js.map'));
      return timeLog(`removed ${source}`);
    }
  };

  silentUnlink = function(path) {
    var ref;
    try {
      return fs.unlinkSync(path);
    } catch (error) {
      err = error;
      if ((ref = err.code) !== 'ENOENT' && ref !== 'EPERM') {
        throw err;
      }
    }
  };

  // Get the corresponding output JavaScript path for a source file.
  outputPath = function(source, base, extension = ".js") {
    var basename, dir, srcDir;
    basename = helpers.baseFileName(source, true, useWinPathSep);
    srcDir = path.dirname(source);
    dir = !opts.outputPath ? srcDir : source === base ? opts.outputPath : path.join(opts.outputPath, path.relative(base, srcDir));
    return path.join(dir, basename + extension);
  };

  // Recursively mkdir, like `mkdir -p`.
  mkdirp = function(dir, fn) {
    var mkdirs, mode;
    mode = 0o777 & ~process.umask();
    return (mkdirs = function(p, fn) {
      return fs.exists(p, function(exists) {
        if (exists) {
          return fn();
        } else {
          return mkdirs(path.dirname(p), function() {
            return fs.mkdir(p, mode, function(err) {
              if (err) {
                return fn(err);
              }
              return fn();
            });
          });
        }
      });
    })(dir, fn);
  };

  // Write out a JavaScript source file with the compiled code. By default, files
  // are written out in `cwd` as `.js` files with the same name, but the output
  // directory can be customized with `--output`.

  // If `generatedSourceMap` is provided, this will write a `.js.map` file into the
  // same directory as the `.js` file.
  writeJs = function(base, sourcePath, js, jsPath, generatedSourceMap = null) {
    var compile, jsDir, sourceMapPath;
    sourceMapPath = `${jsPath}.map`;
    jsDir = path.dirname(jsPath);
    compile = function() {
      if (opts.compile) {
        if (js.length <= 0) {
          js = ' ';
        }
        if (generatedSourceMap) {
          js = `${js}\n//# sourceMappingURL=${helpers.baseFileName(sourceMapPath, false, useWinPathSep)}\n`;
        }
        fs.writeFile(jsPath, js, function(err) {
          if (err) {
            printLine(err.message);
            return process.exit(1);
          } else if (opts.compile && opts.watch) {
            return timeLog(`compiled ${sourcePath}`);
          }
        });
      }
      if (generatedSourceMap) {
        return fs.writeFile(sourceMapPath, generatedSourceMap, function(err) {
          if (err) {
            printLine(`Could not write source map: ${err.message}`);
            return process.exit(1);
          }
        });
      }
    };
    return fs.exists(jsDir, function(itExists) {
      if (itExists) {
        return compile();
      } else {
        return mkdirp(jsDir, compile);
      }
    });
  };

  // Convenience for cleaner setTimeouts.
  wait = function(milliseconds, func) {
    return setTimeout(func, milliseconds);
  };

  // When watching scripts, it's useful to log changes with the timestamp.
  timeLog = function(message) {
    return console.log(`${(new Date()).toLocaleTimeString()} - ${message}`);
  };

  // Pretty-print a stream of tokens, sans location data.
  printTokens = function(tokens) {
    var strings, tag, token, value;
    strings = (function() {
      var j, len, results;
      results = [];
      for (j = 0, len = tokens.length; j < len; j++) {
        token = tokens[j];
        tag = token[0];
        value = token[1].toString().replace(/\n/, '\\n');
        results.push(`[${tag} ${value}]`);
      }
      return results;
    })();
    return printLine(strings.join(' '));
  };

  // Use the [OptionParser module](optparse.html) to extract all options from
  // `process.argv` that are specified in `SWITCHES`.
  parseOptions = function() {
    var o;
    o = opts = optionParser.parse(process.argv.slice(2));
    o.compile || (o.compile = !!o.output);
    o.run = !(o.compile || o.print || o.map);
    return o.print = !!(o.print || (o.eval || o.stdio && o.compile));
  };

  // The compile-time options to pass to the CoffeeScript compiler.
  compileOptions = function(filename, base) {
    var answer, cwd, jsDir, jsPath;
    if (opts.transpile) {
      try {
        // The user has requested that the CoffeeScript compiler also transpile
        // via Babel. We don’t include Babel as a dependency because we want to
        // avoid dependencies in general, and most users probably won’t be relying
        // on us to transpile for them; we assume most users will probably either
        // run CoffeeScript’s output without transpilation (modern Node or evergreen
        // browsers) or use a proper build chain like Gulp or Webpack.
        require('@babel/core');
      } catch (error) {
        try {
          require('babel-core');
        } catch (error) {
          // Give appropriate instructions depending on whether `coffee` was run
          // locally or globally.
          if (require.resolve('.').indexOf(process.cwd()) === 0) {
            console.error(`To use --transpile, you must have @babel/core installed:
  npm install --save-dev @babel/core
And you must save options to configure Babel in one of the places it looks to find its options.
See https://coffeescript.org/#transpilation`);
          } else {
            console.error(`To use --transpile with globally-installed CoffeeScript, you must have @babel/core installed globally:
  npm install --global @babel/core
And you must save options to configure Babel in one of the places it looks to find its options, relative to the file being compiled or to the current folder.
See https://coffeescript.org/#transpilation`);
          }
          process.exit(1);
        }
      }
      if (typeof opts.transpile !== 'object') {
        opts.transpile = {};
      }
      // Pass a reference to Babel into the compiler, so that the transpile option
      // is available for the CLI. We need to do this so that tools like Webpack
      // can `require('coffeescript')` and build correctly, without trying to
      // require Babel.
      opts.transpile.transpile = CoffeeScript.transpile;
      // Babel searches for its options (a `.babelrc` file, a `.babelrc.js` file,
      // a `package.json` file with a `babel` key, etc.) relative to the path
      // given to it in its `filename` option. Make sure we have a path to pass
      // along.
      if (!opts.transpile.filename) {
        opts.transpile.filename = filename || path.resolve(base || process.cwd(), '<anonymous>');
      }
    } else {
      opts.transpile = false;
    }
    answer = {
      filename: filename,
      literate: opts.literate || helpers.isLiterate(filename),
      bare: opts.bare,
      es6: opts.es6,
      header: opts.compile && !opts['no-header'],
      transpile: opts.transpile,
      sourceMap: opts.map,
      inlineMap: opts['inline-map'],
      ast: opts.ast,
      'cs3-trace': opts['cs3-trace']
    };
    if (filename) {
      if (base) {
        cwd = process.cwd();
        jsPath = outputPath(filename, base);
        jsDir = path.dirname(jsPath);
        answer = helpers.merge(answer, {
          jsPath,
          sourceRoot: path.relative(jsDir, cwd) + path.sep,
          sourceFiles: [path.relative(cwd, filename)],
          generatedFile: helpers.baseFileName(jsPath, false, useWinPathSep)
        });
      } else {
        answer = helpers.merge(answer, {
          sourceRoot: "",
          sourceFiles: [helpers.baseFileName(filename, false, useWinPathSep)],
          generatedFile: helpers.baseFileName(filename, true, useWinPathSep) + ".js"
        });
      }
    }
    return answer;
  };

  // Start up a new Node.js instance with the arguments in `--nodejs` passed to
  // the `node` binary, preserving the other options.
  forkNode = function() {
    var args, j, len, nodeArgs, p, ref, signal;
    nodeArgs = opts.nodejs.split(/\s+/);
    args = process.argv.slice(1);
    args.splice(args.indexOf('--nodejs'), 2);
    p = spawn(process.execPath, nodeArgs.concat(args), {
      cwd: process.cwd(),
      env: process.env,
      stdio: [0, 1, 2]
    });
    ref = ['SIGINT', 'SIGTERM'];
    for (j = 0, len = ref.length; j < len; j++) {
      signal = ref[j];
      process.on(signal, (function(signal) {
        return function() {
          return p.kill(signal);
        };
      })(signal));
    }
    return p.on('exit', function(code) {
      return process.exit(code);
    });
  };

  // Print the `--help` usage message and exit. Deprecated switches are not
  // shown.
  usage = function() {
    return printLine(optionParser.help());
  };

  // Print the `--version` message and exit.
  version = function() {
    return printLine(`CoffeeScript version ${CoffeeScript.VERSION}`);
  };

}).call(this);
