// Generated by CoffeeScript 2.7.0
(function() {
  // CS3 Compiler Integration
  // This module connects the CS3 parser with the ES5 backend

  // Import dependencies
  var ES5Backend, Lexer, parser;

  ({Lexer} = require('./lexer'));

  parser = require('./parser-cs3'); // Use CS3 parser

  ES5Backend = require('./index'); // ES5 backend compiled to lib/coffeescript/

  
  // Main compile function
  exports.compileCS3 = function(code, options = {}) {
    var ast, backend, error, jsCode, lexer, lexerInterface, tokenIndex, tokens;
    // Step 1: Tokenize using CoffeeScript's lexer
    lexer = new Lexer();
    tokens = lexer.tokenize(code, options);
    // Step 2: Set up parser with proper lexer interface
    tokenIndex = 0;
    // Create a lexer interface for the parser
    lexerInterface = {
      lex: function() {
        var token, tokenId, tokenType, tokenValue;
        if (tokenIndex >= tokens.length) { // EOF symbol
          return 1;
        }
        token = tokens[tokenIndex++];
        // Handle token value - may be a string, object, or String object
        tokenValue = token[1];
        if (typeof tokenValue === 'object' && (tokenValue != null)) {
          // Check if it's a String object (has valueOf or toString)
          if (tokenValue.constructor === String || tokenValue.valueOf) {
            // It's a String object with properties
            // CS3 parser expects the String object itself with all properties
            this.yytext = tokenValue;
          } else {
            // Regular object
            this.yytext = tokenValue;
          }
        } else {
          // Simple string or primitive
          this.yytext = tokenValue;
        }
        this.yylloc = token[2];
        this.yylineno = token[2] ? token[2].first_line : 0;
        this.yyleng = String(this.yytext).length;
        // Look up token ID in parser's symbol table
        tokenType = token[0];
        tokenId = parser.parser.symbolIds[tokenType];
        // If not found, try as a literal token
        if (tokenId === void 0) {
          // For literal tokens like '=', '+', etc.
          tokenId = parser.parser.symbolIds[token[1]];
        }
        // Still not found? Use the error token
        if (tokenId === void 0) {
          console.error('Unknown token:', tokenType, token[1]);
          tokenId = 2; // error token
        }
        return tokenId;
      },
      setInput: function() {
        return tokenIndex = 0;
      },
      upcomingInput: function() {
        return "";
      }
    };
    // Step 3: Parse to CS3 AST
    parser.parser.lexer = lexerInterface;
    parser.parser.yy = {}; // CS3 doesn't need yy helpers
    try {
      ast = parser.parse();
    } catch (error1) {
      error = error1;
      // Enhance error message
      if (error.message && error.message.indexOf('Object prototype') !== -1) {
        throw new Error('Parser initialization error - ensure CS3 parser is properly generated');
      }
      throw error;
    }
    // Step 4: Generate JavaScript using ES5 backend
    backend = new ES5Backend(options);
    jsCode = backend.generate(ast);
    return jsCode;
  };

  // Export a parse-only function for debugging
  exports.parseCS3 = function(code) {
    var lexer, lexerInterface, tokenIndex, tokens;
    lexer = new Lexer();
    tokens = lexer.tokenize(code, {});
    // Create lexer interface like in compileCS3
    tokenIndex = 0;
    lexerInterface = {
      lex: function() {
        var token, tokenId, tokenType, tokenValue;
        if (tokenIndex >= tokens.length) { // EOF symbol
          return 1;
        }
        token = tokens[tokenIndex++];
        // Handle token value
        tokenValue = token[1];
        if (typeof tokenValue === 'object' && (tokenValue != null)) {
          this.yytext = tokenValue;
        } else {
          this.yytext = tokenValue;
        }
        this.yylloc = token[2];
        this.yylineno = token[2] ? token[2].first_line : 0;
        this.yyleng = String(this.yytext).length;
        // Look up token ID in parser's symbol table
        tokenType = token[0];
        tokenId = parser.parser.symbolIds[tokenType];
        // If not found, try as a literal token
        if (tokenId === void 0) {
          tokenId = parser.parser.symbolIds[token[1]];
        }
        // Still not found? Use the error token
        if (tokenId === void 0) {
          console.error('Unknown token:', tokenType, token[1]);
          tokenId = 2; // error token
        }
        return tokenId;
      },
      setInput: function() {
        return tokenIndex = 0;
      },
      upcomingInput: function() {
        return "";
      }
    };
    // Set up parser
    parser.parser.lexer = lexerInterface;
    parser.parser.yy = {};
    // Parse and return the AST
    return parser.parse();
  };

  // Browser support
  if (typeof window !== 'undefined') {
    window.CoffeeScriptCS3 = {
      compile: exports.compileCS3
    };
  }

}).call(this);
