// Generated by CoffeeScript 2.7.0
(function() {
  // CS3 Compiler Integration
  // This module connects the CS3 parser with the ES5 backend

  // Import dependencies
  var ES5Backend, Lexer, packageJson, parser;

  ({Lexer} = require('./lexer'));

  parser = require('./parser-cs3'); // Use CS3 parser

  ES5Backend = require('../backends/es5/index'); // ES5 backend in lib/backends/es5/

  
  // Main compile function
  exports.compileCS3 = function(code, options = {}) {
    var ast, backend, error, jsCode, lexer, lexerInterface, tokenIndex, tokens;
    // Step 1: Tokenize using CoffeeScript's lexer
    lexer = new Lexer();
    tokens = lexer.tokenize(code, options);
    // Step 2: Set up parser with proper lexer interface
    tokenIndex = 0;
    // Create a lexer interface for the parser
    lexerInterface = {
      lex: function() {
        var token, tokenId, tokenType, tokenValue;
        if (tokenIndex >= tokens.length) { // EOF symbol
          return 1;
        }
        token = tokens[tokenIndex++];
        // Handle token value - may be a string, object, or String object
        tokenValue = token[1];
        if (typeof tokenValue === 'object' && (tokenValue != null)) {
          // Check if it's a String object (has valueOf or toString)
          if (tokenValue.constructor === String || tokenValue.valueOf) {
            // It's a String object with properties
            // CS3 parser expects the String object itself with all properties
            this.yytext = tokenValue;
          } else {
            // Regular object
            this.yytext = tokenValue;
          }
        } else {
          // Simple string or primitive
          this.yytext = tokenValue;
        }
        this.yylloc = token[2];
        this.yylineno = token[2] ? token[2].first_line : 0;
        this.yyleng = String(this.yytext).length;
        // Look up token ID in parser's symbol table
        tokenType = token[0];
        tokenId = parser.parser.symbolIds[tokenType];
        // If not found, try as a literal token
        if (tokenId === void 0) {
          // For literal tokens like '=', '+', etc.
          tokenId = parser.parser.symbolIds[token[1]];
        }
        // Still not found? Use the error token
        if (tokenId === void 0) {
          console.error('Unknown token:', tokenType, token[1]);
          tokenId = 2; // error token
        }
        return tokenId;
      },
      setInput: function() {
        return tokenIndex = 0;
      },
      upcomingInput: function() {
        return "";
      }
    };
    // Step 3: Parse to CS3 AST
    parser.parser.lexer = lexerInterface;
    parser.parser.yy = {}; // CS3 doesn't need yy helpers
    try {
      ast = parser.parse();
    } catch (error1) {
      error = error1;
      // Enhance error message
      if (error.message && error.message.indexOf('Object prototype') !== -1) {
        throw new Error('Parser initialization error - ensure CS3 parser is properly generated');
      }
      throw error;
    }
    // Step 4: Generate JavaScript using ES5 backend
    backend = new ES5Backend(options);
    jsCode = backend.generate(ast);
    return jsCode;
  };

  // Export a parse-only function for debugging
  exports.parseCS3 = function(code) {
    var lexer, lexerInterface, tokenIndex, tokens;
    lexer = new Lexer();
    tokens = lexer.tokenize(code, {});
    // Create lexer interface like in compileCS3
    tokenIndex = 0;
    lexerInterface = {
      lex: function() {
        var token, tokenId, tokenType, tokenValue;
        if (tokenIndex >= tokens.length) { // EOF symbol
          return 1;
        }
        token = tokens[tokenIndex++];
        // Handle token value
        tokenValue = token[1];
        if (typeof tokenValue === 'object' && (tokenValue != null)) {
          this.yytext = tokenValue;
        } else {
          this.yytext = tokenValue;
        }
        this.yylloc = token[2];
        this.yylineno = token[2] ? token[2].first_line : 0;
        this.yyleng = String(this.yytext).length;
        // Look up token ID in parser's symbol table
        tokenType = token[0];
        tokenId = parser.parser.symbolIds[tokenType];
        // If not found, try as a literal token
        if (tokenId === void 0) {
          tokenId = parser.parser.symbolIds[token[1]];
        }
        // Still not found? Use the error token
        if (tokenId === void 0) {
          console.error('Unknown token:', tokenType, token[1]);
          tokenId = 2; // error token
        }
        return tokenId;
      },
      setInput: function() {
        return tokenIndex = 0;
      },
      upcomingInput: function() {
        return "";
      }
    };
    // Set up parser
    parser.parser.lexer = lexerInterface;
    parser.parser.yy = {};
    // Parse and return the AST
    return parser.parse();
  };

  // CoffeeScript-Compatible API for testing
  // (Enables running test suite with 'cake test:cs3')

  // Standard compile method (alias for compileCS3)
  exports.compile = exports.compileCS3;

  // Execute compiled CS3 code
  exports.run = function(code, options = {}) {
    var compiledJS, dir, error, fs, mainModule, path, vm;
    // Use Node.js require system for execution
    vm = require('vm');
    fs = require('fs');
    path = require('path');
    mainModule = require.main;
    // Set up execution context like traditional CoffeeScript.run
    mainModule.filename = process.argv[1] = options.filename ? fs.realpathSync(options.filename) : 'repl';
    mainModule.moduleCache && (mainModule.moduleCache = {});
    dir = options.filename != null ? path.dirname(fs.realpathSync(options.filename)) : fs.realpathSync('.');
    mainModule.paths = require('module')._nodeModulePaths(dir);
    mainModule.options = options;
    options.filename = mainModule.filename;
    options.inlineMap = true;
    try {
      // Compile with CS3 pipeline
      compiledJS = exports.compileCS3(code, options);
      // Execute the compiled JavaScript
      return mainModule._compile(compiledJS, mainModule.filename);
    } catch (error1) {
      error = error1;
      throw error;
    }
  };

  // Register CS3 for .coffee file extensions
  exports.register = function() {
    // Register CS3 compile handler for .coffee files
    require.extensions['.coffee'] = function(module, filename) {
      var compiled, error, raw, stripped;
      raw = require('fs').readFileSync(filename, 'utf8');
      // Strip BOM if present
      stripped = raw.charCodeAt(0) === 0xFEFF ? raw.substring(1) : raw;
      try {
        compiled = exports.compileCS3(stripped, {filename});
        return module._compile(compiled, filename);
      } catch (error1) {
        error = error1;
        // Add filename info to error for better debugging
        error.filename = filename;
        throw error;
      }
    };
    // Also register literate extensions
    return require.extensions['.litcoffee'] = require.extensions['.coffee.md'] = require.extensions['.coffee'];
  };

  // Version compatibility
  packageJson = require('../../package.json');

  exports.VERSION = packageJson.version;

  // Browser support
  if (typeof window !== 'undefined') {
    window.CoffeeScriptCS3 = {
      compile: exports.compileCS3,
      run: exports.run
    };
  }

}).call(this);
