#!/usr/bin/env coffee

# ==============================================================================
# CS3 Create Syntax - Transform grammar.coffee to data-oriented syntax.coffee
# ==============================================================================

fs = require 'fs'
path = require 'path'
CS3PatternMatcher = require './cs3-pattern-matcher-v2'
{transformActionToClean} = require './cs3-transform-to-clean-syntax'

# Read the original grammar
grammarPath = path.join(__dirname, 'grammar.coffee')
grammarContent = fs.readFileSync(grammarPath, 'utf8')

# Create pattern matcher
matcher = new CS3PatternMatcher()

# Statistics
stats =
  totalRules: 0
  transformedRules: 0
  locCalls: 0
  blockWrapCalls: 0
  extendCalls: 0
  errors: []

# Transform a single action
transformAction = (actionStr) ->
  return null unless actionStr

  # Count special cases
  stats.locCalls++ if actionStr.match(/LOC\(/)
  stats.blockWrapCalls++ if actionStr.match(/Block\.wrap/)
  stats.extendCalls++ if actionStr.match(/\bextend\b/)

  try
    # First, handle LOC() calls - these will become $pos
    # For now, we'll strip them and add position tracking later
    cleaned = actionStr.replace(/LOC\(\d+(?:,\s*\d+)?\)\s*\(/g, '(')

    # Handle Block.wrap
    cleaned = cleaned.replace(/Block\.wrap\s*\[(.*?)\]/g, (match, content) ->
      "{$type: 'Block', statements: [#{content}]}"
    )

    # Handle extend
    cleaned = cleaned.replace(/\bextend\s+(\$\d+),\s*(.+)$/g, (match, target, props) ->
      "{$op: 'extend', target: #{target}, props: #{props}}"
    )

    # Transform with pattern matcher
    result = matcher.transformAction(cleaned)

    # Convert to clean CoffeeScript syntax (no unnecessary braces!)
    if result?
      stats.transformedRules++
      transformActionToClean(result)
    else
      # If transformation failed, keep original for now
      actionStr

  catch error
    stats.errors.push
      action: actionStr
      error: error.message
    actionStr

# Process the grammar content
lines = grammarContent.split('\n')
outputLines = []
inGrammar = false
currentIndent = 0

# We need to redefine the 'o' function for pure data
oFunctionDefined = false

for line, i in lines
  # Check if we're entering the grammar section
  if line.match(/^grammar\s*=/)
    inGrammar = true
    outputLines.push line
    continue

  # Keep non-grammar lines as is, but add our new 'o' function
  unless inGrammar
    # Replace the old 'o' function definition with one that handles pure data
    if line.match(/^o\s*=\s*\(/) and not oFunctionDefined
      outputLines.push """# CS3: Redefine 'o' to handle pure data actions instead of functions
o = (patternString, action, options) ->
  patternString = patternString.replace /\\s{2,}/g, ' '

  # CS3: action is now a data object, not a function
  # We'll process it at parse time, not here
  [patternString, action, options]
"""
      oFunctionDefined = true
      # Skip the original o function
      while i < lines.length and not lines[i+1]?.match(/^\w/)
        i++
      continue
    else
      outputLines.push line
    continue

  # Check for rule with action
  if match = line.match(/^(\s*)o\s+'([^']+)'(?:\s*,\s*(.*))?$/)
    indent = match[1]
    pattern = match[2]
    rest = match[3] or ''

    stats.totalRules++

    # Extract action if present
    if actionMatch = rest.match(/^->\s*(.+)$/)
      action = actionMatch[1]
      transformed = transformAction(action)

      # Reconstruct the line with pure data (no function)
      outputLines.push "#{indent}o '#{pattern}', #{transformed}"
    else if rest.match(/^,/)
      # Has comma but no arrow - might be multiline or data
      outputLines.push line
    else
      # No action, keep as is
      outputLines.push line
  else
    # Not a rule line, keep as is
    outputLines.push line

# Update module exports
outputContent = outputLines.join('\n')

# Replace the module.exports section
outputContent = outputContent.replace(
  /module\.exports\s*=[\s\S]*$/,
  """
  # Export the data-oriented grammar for CS3
  module.exports =
    bnf: grammar
    operators: operators.reverse()
    start: 'Root'
  """
)

# Add CS3 header
header = """
# ==============================================================================
# CS3 Syntax - Data-Oriented Grammar for CoffeeScript 3
#
# This file is automatically generated from grammar.coffee by transforming
# class-based AST node creation to data-oriented node creation.
#
# KEY DIFFERENCE: Actions are pure data objects, NOT functions!
# - Old: o 'Body', -> new Root $1
# - New: o 'Body', {$type: 'Root', body: {$ref: 1}}
#
# Transformations applied:
# - new ClassName(...) -> {$type: 'ClassName', ...}
# - $1, $2, etc -> {$ref: 1}, {$ref: 2}, etc
# - LOC() calls -> position tracking (TODO: add $pos)
# - Block.wrap -> {$type: 'Block', statements: [...]}
# - extend -> {$op: 'extend', ...}
# ==============================================================================

"""

outputContent = header + outputContent

# Write to syntax.coffee
syntaxPath = path.join(__dirname, 'syntax.coffee')
fs.writeFileSync(syntaxPath, outputContent)

# Print statistics
console.log "=" .repeat 80
console.log "CS3 SYNTAX TRANSFORMATION COMPLETE"
console.log "=" .repeat 80
console.log()
console.log "Statistics:"
console.log "  Total rules:       #{stats.totalRules}"
console.log "  Transformed:       #{stats.transformedRules}"
console.log "  LOC() calls:       #{stats.locCalls}"
console.log "  Block.wrap calls:  #{stats.blockWrapCalls}"
console.log "  extend calls:      #{stats.extendCalls}"
console.log "  Errors:            #{stats.errors.length}"
console.log()

if stats.errors.length > 0
  console.log "Errors encountered:"
  for err in stats.errors[0..5]
    console.log "  #{err.action.slice(0, 50)}..."
    console.log "    Error: #{err.error}"
  if stats.errors.length > 5
    console.log "  ... and #{stats.errors.length - 5} more"
  console.log()

console.log "Output written to: #{syntaxPath}"
console.log()
console.log "Next steps:"
console.log "  1. Review and fix any untransformed rules"
console.log "  2. Add position tracking ($pos) for LOC() replacements"
console.log "  3. Test with Solar parser"
console.log "  4. Run full test suite for validation"
console.log()
console.log "=" .repeat 80
